### ISSUE TITLE
support for glx-fshader-win is really needed!

### ISSUE THREAD

**Issue by vn971** [yshui/picom#108]
First of all, thanks for your work in keeping compton alive!
The actual feature request is: please keep support for glx-fshader-win! It's certainly used, see for example here: https://github.com/vn971/linux-color-inversion. I use it a lot in dark environment, the GLX color inversion is so much better than the RGB inversion. I think it is indeed being used by people in the wild.

Telling the system details just for statistics:

### Platform
ArchLinux amd64

### GPU, drivers, and screen setup
intel UHD Graphics 620. The video driver versions are irrelevant I guess.

### Environment
XFCE4 (latest stable version, as in ArchLinux)

### Compton version
`compton --version` gives `v5`. `pacman -Si compton` is `5.0-1`.
```
**Version:** v5

### Extensions:

* Name Pixmap: Yes
* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /etc/xdg//compton.conf
```

### Compton configuration:
```
# empty config, and this script:
compton --config /dev/null --invert-color-include '!name ~= "Wesnoth - " && !name ~= " - SMPlayer" && !name ~= " - Image Viewer" && !name ~= "Hedgewars" && !name ~= " GIMP"' --backend glx --dbus --glx-fshader-win "$(cat ~/.vn971/shift_whiteish.glsl)" --daemon
```

**Comment by yshui** [comment]
Noted!

Thanks for the feedback.

**Comment by ncortese** [comment]
I use glx-fshader-win as well, although in kind of a hacky way: when doing digital art, I'll sometimes run Compton using a shader with a postprocessing effect to see how it looks in real time. I started doing this because I found Krita's Filter Layers useful, but their selection of filters is limited and I didn't want to have to mess around with its source code just to add 1 or 2 new effects.

This kind of shader replacement stuff might be better served by a dedicated, standalone program, but until one exists, retaining glx-fshader-win would be much appreciated.

**Comment by m-ou-se** [comment]
I also use `--glx-fshader-win`, to make my terminals semi-transparent: https://gist.github.com/m-ou-se/fe96f6a7e947cf2e37d46e9012869a06

**Comment by clort81** [comment]
I also use it with black keycolor for terminal backgrounds and browser (with black css override) backgrounds.
I am wanting to figure out how to pass a time float to the shader for animated effects.

**Comment by vn971** [comment]
@m-ou-se sorry for unrelated question. I accidentally saw you're using Rust in Fusion Engineering, and it's located in Utrecht. Does the company by chance also look for new Rust devs?

I don't have professional experience with Rust, but I'm interested in the language (and have non-professional experience).

**Comment by m-ou-se** [comment]
@vn971 Feel free to contact me at mara@fusion.engineering.

**Comment by gregorlarson** [comment]
I also use the fshader, similar to vn971/linux-color-inversion
It would be nice to have the shader come from a file or files instead of trying to put the entire shader on the command-line (which doesn't feel quite right, especially for longer programs).

**Comment by baongoc124** [comment]
I also use it every day to have a darkroom mode for using computer during the night.
So please don't remove it.

**Comment by julien-h** [comment]
same here

**Comment by yshui** [comment]
I removed the deprecation message in 3e17f11d6, glx-fshader-win is no longer on the deprecation track.

I will close this issue when v8 is released.
