### ISSUE TITLE
Noticeable lag when opening/closing windows

### ISSUE THREAD

**Issue by yshui** [yshui/picom#11]
### Compton configuration:

`--config /dev/null --backend glx`

### Steps of reproduction

1. Start compton
2. Go to Firefox
3. Start to play some video on webpage
3. Right click to open popup menu
4. Click to close popup menu

### Expected behavior

Video play smoothly

### Current Behavior

There is a noticeable frame loss when the popup menu opens/closes

**Comment by aufkrawall** [comment]
Is this with Nvidia driver? It has a broken Xorg performance "by design" which makes its stutter every time some new window element appears. That even happens completely without any compositor, and doesn't happen with AMD or Intel Mesa drivers.

**Comment by yshui** [comment]
@aufkrawall I am using Nvidia, but I didn't notice this stutter without compton running.

**Comment by aufkrawall** [comment]
It gets very obvious when having this site opened in browser
https://www.vsynctester.com/
and then open some dialogues etc. With Nvidia, I even get stuttering when I hover the mouse cursor over elements of my shell which show next pop ups etc.

**Comment by tuyenpm9** [comment]
I think this is kind of urgent issue, I have lag on `glx` driver:

steps:
1. open chrome
2. right click on empty space to open chrome pop-up --> feel no lag
3. open a url, right click on hyperlink --> feed lag/delay.

expected behavior:
right click on hyperlink on browser should not have any delay/lag.

**Comment by yshui** [comment]
I think I understand this bug now. This is because `BindTexImageEXT` is _so slow_ on NVIDIA driver. When a new window comes up, compton need to call that to create a texture for it, and since it's so slow on NVIDIA, it creates a lag.

Not sure what compton can do.

**Comment by yshui** [comment]
there are reports that this isn't happening anymore. maybe it's because of changes in picom, or maybe nvidia actually fixed it?!!?!?

anyway, i wanted to keep this open as a "nvidia bad" issue, but i guess that doesn't really mean much, so closing.
