### ISSUE TITLE
[Feature request] Configurable GLSL shaders

### ISSUE THREAD

**Issue by k80w** [yshui/picom#138]
It would be amazing if you could apply custom GLSL fragment shaders to windows based on certain rules.

**Comment by dnaf** [comment]
I should clarify: while you can currently apply a GLSL shader to every window using `--glx-fshader-win`, there doesn't appear to be a way to, say, only use a shader for inactive windows, or only use a shader for windows of a certain class.

**Comment by gregorlarson** [comment]
I can apply a shader to some windows, for example:

compton --backend glx --glx-fshader-win "$(cat matrix_thirds.glsl)" --invert-color-include g:e:Firefox

- not sure if this is the scenario you we thinking of.
ref: https://github.com/gregorlarson/linux-color-inversion

**Comment by deifactor** [comment]
Yeah, I kind of want this so I can have my neovim window have transparent backgrounds for some cells (depending on background color) without having to worry about other windows that use those colors getting transparent-ified for no reason.

invert-color is a decent hack, but means you can only effectively do one 'category'.

**Comment by yshui** [comment]
Implemented by #851
