### ISSUE TITLE
Improve frame timing (a.k.a. reduce input lag)

### ISSUE THREAD

**Issue by yshui** [yshui/picom#147]
Currently, compton doesn't really pay any kind of attention to frame timing. A frame is rendered whenever the main loop is free (i.e. not events received in a round of the main loop) and there is damage.

It's amazing this worked so well as it did (because there are so many ways this could break). But, there are increasing number of reports of input lags when vsync is enabled. Most notably, window lags behind the mouse cursor when it's dragged around.

A lag of one frame is unavoidable when vsync is enabled, because the screen update has to sync with vblank, so it cannot update as soon as the mouse moves. However, the current input lag of compton seems to be far higher than one frame.

We might be able to resolve this problem by carefully scheduling frames.

**Comment by tmpm697** [comment]
I'm still using ver 5.1.

**Comment by tmpm697** [comment]
I'm still using ver 5.1 and frequently checking for new compatible versions to upgrade.

**Comment by sudopluto** [comment]
this seems like a pretty interesting issue, any recommended reading to start to figure this out?

**Comment by yshui** [comment]
addressed in #1156 #968
