### ISSUE TITLE
Huge lags caused by xrender backend

### ISSUE THREAD

**Issue by kalsan** [yshui/picom#174]
### Platform

Arch Linux x86_64

### GPU, drivers, and screen setup

HP Elitebook 8570p, Radeon HD 7550M/7570M/7650M, xf86-video-ati 1:19.0.1-1

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD TURKS (DRM 2.50.0 / 4.19.44-1-lts, LLVM 8.0.0) (0x6841)
    Version: 19.0.4
    Accelerated: yes
    Video memory: 1024MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 1023 MB, largest block: 1023 MB
    VBO free aux. memory - total: 1021 MB, largest block: 1021 MB
    Texture free memory - total: 1023 MB, largest block: 1023 MB
    Texture free aux. memory - total: 1021 MB, largest block: 1021 MB
    Renderbuffer free memory - total: 1023 MB, largest block: 1023 MB
    Renderbuffer free aux. memory - total: 1021 MB, largest block: 1021 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 1024 MB
    Total available memory: 2045 MB
    Currently available dedicated video memory: 1023 MB
OpenGL vendor string: X.Org
OpenGL renderer string: AMD TURKS (DRM 2.50.0 / 4.19.44-1-lts, LLVM 8.0.0)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 19.0.4
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.1 Mesa 19.0.4
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 19.0.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
```

### Environment

i3  version 4.16.1 (2019-01-27)

### Compton version

```
**Version:** v6.2

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /etc/xdg/compton.conf

```

### Compton configuration:
(default)

### Steps of reproduction

1. Launch i3
2. Launch compton
3. Launch telegram-desktop (Arch Linux package: telegram-desktop 1.7.0-1)
4. Minimize Telegram / change workspace / focus on another window
5. Have one of your friends type such that the string "typing..." appears in the top (with the animation)

### Expected behavior

Nothing

### Current Behavior

Entire computer starts lagging, as you type the text appears with a delay, any animation by any program (including compton's transition effect) lags, scrolling through webpages lags up to a second, YouTube becomes completely unusable etc.

Everything is back to normal as soon as the typing animation stops or when compton is terminated. Also happens with Rambox instead of Telegram Desktop, but less pronounced.

**Comment by yshui** [comment]
Is there anything going on with the CPU usage?

**Comment by yshui** [comment]
And does this happen with the `xrender` backend?

**Comment by kalsan** [comment]
Thanks for the fast reaction! CPU goes up to 10% which is normal.

It only happens with xrender backend. When using compton with glx, everything works normally.

**Comment by yshui** [comment]
@kalsan Is 10% the whole system's CPU usage?

This might just be an example of xrender's poor performance. If `glx` works without problem I suggest you just stick with that.

**Comment by kalsan** [comment]
Yes this is a good workaround for me. I'll leave the issue open since the actual bug remains.

**Comment by yshui** [comment]
closing as old, and also seems to be an legacy backend issue
