### ISSUE TITLE
HD videos lagging hard without sw-opti

### ISSUE THREAD

**Issue by resolritter** [yshui/picom#197]
### Description
I want to make a case for keeping "sw-opti".

The story here is that I'm running a 120hz monitor plugged into a weak laptop for graphics and I can't have Compton's rate be that high, because it causes all sorts of lag and frankly I don't need it. **I do not want to refresh to my sync rate** or anything above 30FPS because I don't use blur, fading or other gradual fluff to make transitions smoother. You can notice in my config below that I pretty much only enable dimming/opacity for inactive windows and have everything else turned off.

In short, I want to keep the refresh rate much lower than that of my monitor in order to boost performance in my laptop. I'm only opening a issue here because I was greeted with the following message:

`
[ 06/24/2019 19:48:33.028 swopti_init WARN ] --sw-opti is going to be deprecated. If you get real benefits from using this option, please open an issue to let us know.
`

It seems like my use-case depends a LOT on this. I think it's a very useful option to have for those of us with not-so-great machines or battery-dependent devices to save up power.

---

### Platform
Ubuntu Desktop 18.04 amd64

### GPU, drivers, and screen setup
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2)  (0x5916)
    Version: 18.0.5
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 18.0.5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

```
ii  libxxf86dga-dev:amd64                                       2:1.1.4-1
ii  libxxf86dga1:amd64                                          2:1.1.4-1
ii  libxxf86vm-dev:amd64                                        1:1.1.4-1
ii  libxxf86vm1:amd64                                           1:1.1.4-1
ii  libxxf86vm1:i386                                            1:1.1.4-1
ii  x11proto-xf86bigfont-dev                                    2018.4-4
ii  x11proto-xf86dga-dev                                        2018.4-4
ii  x11proto-xf86vidmode-dev                                    2018.4-4

ii  libegl-mesa0:amd64                                          18.0.5-0ubuntu0~18.04.1
ii  libegl-mesa0:i386                                           18.0.5-0ubuntu0~18.04.1
ii  libegl1-mesa:amd64                                          18.0.5-0ubuntu0~18.04.1
ii  libegl1-mesa-dev:amd64                                      18.2.8-0ubuntu0~18.04.2
ii  libgl1-mesa-dev:amd64                                       18.2.8-0ubuntu0~18.04.2
ii  libgl1-mesa-dri:amd64                                       18.0.5-0ubuntu0~18.04.1
ii  libgl1-mesa-dri:i386                                        18.0.5-0ubuntu0~18.04.1
ii  libgl1-mesa-glx:amd64                                       18.0.5-0ubuntu0~18.04.1
ii  libgl1-mesa-glx:i386                                        18.0.5-0ubuntu0~18.04.1
ii  libglapi-mesa:amd64                                         18.0.5-0ubuntu0~18.04.1
ii  libglapi-mesa:i386                                          18.0.5-0ubuntu0~18.04.1
ii  libgles2-mesa-dev:amd64                                     18.0.5-0ubuntu0~18.04.1
ii  libglu1-mesa:amd64                                          9.0.0-2.1build12.1build1
ii  libglu1-mesa-dev:amd64                                      9.0.0-2.1build1
ii  libglx-mesa0:amd64                                          18.0.5-0ubuntu0~18.04.1
ii  libglx-mesa0:i386                                           18.0.5-0ubuntu0~18.04.1
ii  libosmesa6:amd64                                            18.0.5-0ubuntu0~18.04.1
ii  libosmesa6:i386                                             18.0.5-0ubuntu0~18.04.1
ii  libwayland-egl1-mesa:amd64                                  18.2.8-0ubuntu0~18.04.2
ii  libwayland-egl1-mesa:i386                                   18.2.8-0ubuntu0~18.04.2
ii  mesa-common-dev:amd64                                       18.2.8-0ubuntu0~18.04.2
ii  mesa-utils                                                  8.4.0-1
ii  mesa-va-drivers:amd64                                       18.0.5-0ubuntu0~18.04.1
ii  mesa-va-drivers:i386                                        18.0.5-0ubuntu0~18.04.1
ii  mesa-vdpau-drivers:amd64                                    18.0.5-0ubuntu0~18.04.1
ii  mir-client-platform-mesa-dev:amd64                          0.31.1-0ubuntu1
```

### Environment
i3-gaps
120hz external monitor plugged through HDMI
Laptop stays always with a closed lid and its screen is disabled at startup through XRandr

### Compton version
v5-rc4-347-g387e247

### Compton configuration:
```
# Reference: https://github.com/yshui/compton/blob/next/compton.sample.conf
# https://github.com/yshui/compton/blob/next/man/compton.1.asciidoc#blur

# Environment
# (deprecated) vsync = "none";
mark-ovredir-focused = true;
vsync = false;
refresh-rate = 30;
sw-opti = true;
unredir-if-possible = false;
# unredir-if-possible-delay = 1000;
# unredir-if-possible-exclude = [];
detect-transient = true;
# GLX backend
#backend = "glx";
use-damage = true;
# glx-no-stencil = true;
# glx-copy-from-front = false;
# glx-use-copysubbuffermesa = true;
# glx-no-rebind-pixmap = true;
# glx-swap-method = "undefined";
# glx-use-gpushader4 = true;
# xrender-sync = true;
# xrender-sync-fence = true;


# Shadow
shadow = false;
# (deprecated) no-dnd-shadow = true;
# (deprecated) no-dock-shadow = true;
wintypes:
{
  tooltip = { shadow = false; full-shadow = false; };
  dock = { shadow = false; full-shadow = false; }
  dnd = { shadow = false; full-shadow = false; }
  popup_menu = { shadow = false; full-shadow = false; }
  dropdown_menu = { shadow = false; full-shadow = false; }
};

# Opacity
inactive-opacity = 0.5;
#active-opacity = 1.0;
#frame-opacity = 0.7;
#inactive-opacity-override = false;
#alpha-step = 0.06;
#inactive-dim = 0.5;
#inactive-dim-fixed = true;
opacity-rule = [
  "100:_NET_WM_STATE@[0]:32a = '_NET_WM_STATE_FULLSCREEN'",
  "100:_NET_WM_STATE@[1]:32a = '_NET_WM_STATE_FULLSCREEN'",
  "100:_NET_WM_STATE@[2]:32a = '_NET_WM_STATE_FULLSCREEN'",
  "100:_NET_WM_STATE@[3]:32a = '_NET_WM_STATE_FULLSCREEN'",
  "100:_NET_WM_STATE@[4]:32a = '_NET_WM_STATE_FULLSCREEN'",
  "100:_NET_WM_STATE@[0]:32a = '_NET_WM_STATE_FOCUSED'"
];

# Focus
focus-exclude = [
  "_NET_WM_STATE@[0]:32a = '_NET_WM_STATE_FOCUSED'"
];

# Blur
#blur-background = true;
#blur-background-fixed = true;
#blur-background-frame = true;
#blur-kern = "3x3box";
#blur-background-exclude = [
#  "window_type = 'dock'",
#  "window_type = 'desktop'",
#  "_GTK_FRAME_EXTENTS@:c"
#];

# Fading
fading = false;
```

**Comment by yshui** [comment]
Noted.

There are better ways to limit refresh rate. They will be implemented. `sw-opti` has to go.

**Comment by reaysawa** [comment]
@yshui let me know if I can help or test-drive when the time comes ^ _ ^

**Comment by yshui** [comment]
@reaysawa BTW, you should be able to just change your refresh rate using xrandr.

for example:

`xrandr --output HDMI-1 --rate 60`. You can read about xrandr here: https://wiki.archlinux.org/index.php/Xrandr

**Comment by reaysawa** [comment]
@yshui right, but I don't want to cap myself out at 60. I want to keep the refresh rate at 120hz e.g. for the games I (used to) play or... Just general smoothness of scrolling and moving the mouse pointer around.

There's just no need to refresh compton that fast because I don't get any benefit by doing it. Like I said, for only dimming and opacity stuff, maybe even 30 is too much. I want to save power when possible because I'm already running a bunch of other programming stuff at once - occasionally LSP servers and Intellij IDEA too.

Also on another note, since I just remebered something now talking about that... I am under the impression that I get occasional white flashes when switching between workspaces if I keep the rate at 120hz.

**Comment by yshui** [comment]
@reaysawa compton draws everything on your screen. if you cap compton at 60hz everything on your screen besides your pointer will refresh at 60hz.

That being said, capping refresh rate with compton is slightly more convenient when you play games, since compton automatically unredirect your screen so you get 120hz automatically (compared to running `xrandr` every time before you start your game).

**Comment by reaysawa** [comment]
@yshui oh my, the revelations! I'm a fool! I didn't know that was the case. I thought only the "effects" were applied at that rate... So it's not a "filter". Noted. : ^ )

That being the case I have no qualms about those previous thoughts, though I still of course need to limit the rate somehow below vsync.

Question: Is it possible to avoid drawing a single window/process within a non-blacklisted process? For instance, avoid drawing only Chrome's media player (e.g. on Youtube) and draw the browser itself at the capped rate. I was getting a massive lag when playing Youtube videos at fullscreen, which is what prompted the use of `--sw-opti` in the first place.

**Comment by javashin** [comment]
no problem here for me using compton --experimental-backends --backend glx   i been using this combination for a while and all the videos are fine using mpv youtube@chromium-vaapi vlc deepin-movie-reborn

**Comment by reaysawa** [comment]
@javashin Ah, I did try setting `#backend = "glx";` but it didn't make a difference. I think it might be because I didn't enable the `--experimental-backends` flag. Hmmmm... I'll try it as soon as I can. Thanks for the tip.

**Comment by javashin** [comment]
NP
