### ISSUE TITLE
Chromium under opaque windows does not rerender

### ISSUE THREAD

**Issue by perrin4869** [yshui/picom#200]
Screen capture of the problem:
https://youtu.be/IdjOYe7I4uA

### Platform
Slackware64-current

### GPU, drivers, and screen setup
NVidia GTX 760, nvidia-drivers 418.56
xf86-video-amdgpu-19.0.0-x86_64-1
xf86-video-apm-1.3.0-x86_64-1
xf86-video-ark-0.7.5-x86_64-11
xf86-video-ast-1.1.5-x86_64-5
xf86-video-ati-19.0.0-x86_64-1
xf86-video-chips-1.4.0-x86_64-1
xf86-video-cirrus-1.5.3-x86_64-5
xf86-video-dummy-0.3.8-x86_64-3
xf86-video-glint-1.2.9-x86_64-3
xf86-video-i128-1.4.0-x86_64-1
xf86-video-i740-1.4.0-x86_64-1
xf86-video-intel-20180906_25c9a2fc-x86_64-1
xf86-video-mach64-6.9.6-x86_64-1
xf86-video-mga-2.0.0-x86_64-1
xf86-video-neomagic-1.3.0-x86_64-1
xf86-video-nouveau-1.0.16-x86_64-1
xf86-video-nv-2.1.21-x86_64-3
xf86-video-openchrome-0.6.0-x86_64-3
xf86-video-r128-6.12.0-x86_64-1
xf86-video-rendition-4.2.7-x86_64-1
xf86-video-s3-0.6.5-x86_64-11
xf86-video-s3virge-1.11.0-x86_64-1
xf86-video-savage-20180625_0ece556-x86_64-1
xf86-video-siliconmotion-1.7.9-x86_64-3
xf86-video-sis-20170717_a50b2b3-x86_64-1
xf86-video-sisusb-0.9.7-x86_64-3
xf86-video-tdfx-1.5.0-x86_64-1
xf86-video-tga-1.2.2-x86_64-11
xf86-video-trident-1.3.8-x86_64-3
xf86-video-tseng-1.2.5-x86_64-11
xf86-video-v4l-0.3.0-x86_64-1
xf86-video-vboxvideo-1.0.0-x86_64-3
xf86-video-vesa-2.4.0-x86_64-3
xf86-video-vmware-13.3.0-x86_64-2
xf86-video-voodoo-1.2.5-x86_64-12
mesa-18.3.4-x86_64-1

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 2048 MB
    Total available memory: 2048 MB
    Currently available dedicated video memory: 1319 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 760/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 418.56
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 418.56
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 418.56
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment
i3 version 4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors

### Compton version
```bash
compton --config .compton.conf --diagnostics
**Version:** v6

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: .compton.conf
```

### Compton configuration:
```
backend = "glx";
vsync = true;

shadow = true;

shadow-radius = 10;
shadow-offset-x = -5;
shadow-offset-y = 0;
shadow-opacity = 0.8;
shadow-red = 0.11;
shadow-green = 0.12;
shadow-blue = 0.13;
shadow-exclude = [
  "name = 'Notification'",
  "_GTK_FRAME_EXTENTS@:c",
  "class_g = 'i3-frame'",
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_STICKY'",
  "!I3_FLOATING_WINDOW@:c"
];
shadow-ignore-shaped = true;

blur-background = false;
blur-background-fixed = true;
blur-kern = "7x7box";
blur-background-exclude = [
  "class_g = 'i3-frame'",
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

# Duplicating the _NET_WM_STATE entries because compton cannot deal with atom arrays :-/
opacity-rule = [
  "97:class_g = 'URxvt' && !_NET_WM_STATE@:32a",

  "90:_NET_WM_STATE@[0]:32a = '_NET_WM_STATE_STICKY'",
  "90:_NET_WM_STATE@[1]:32a = '_NET_WM_STATE_STICKY'",
  "90:_NET_WM_STATE@[2]:32a = '_NET_WM_STATE_STICKY'",
  "90:_NET_WM_STATE@[3]:32a = '_NET_WM_STATE_STICKY'",
  "90:_NET_WM_STATE@[4]:32a = '_NET_WM_STATE_STICKY'"
];

fading = false;
fade-delta = 7;
fade-in-step = 0.05;
fade-out-step = 0.05;
fade-exclude = [];

mark-wmwin-focused = true;
mark-ovredir-focused = true;
use-ewmh-active-win = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0;
dbe = false;
glx-no-stencil = true;
glx-copy-from-front = false;
unredir-if-possible = false;
focus-exclude = [];
detect-transient = true;
detect-client-leader = true;
invert-color-include = [];

wintypes: {
  tooltip = { fade = true; shadow = false; opacity = 1.00; focus = true; };
  dock = { shadow = false; };
  dnd = { shadow = false; };
};
```

### Steps of reproduction

Open qutebrowser, chromium and urxvt with transparency enabled (`URxvt*background:       [75]#000000`) on i3, and stack them.
Open up some youtube video on the browsers, and put them behind urxvt.

### Expected behavior

Both Chromium and qutebrowser windows will keep rerendering even behind the opaque urxvt. 

### Current Behavior

qutebrowser keep rerendering, but chromium "freezes" behind urxvt

Exactly as seen here: https://youtu.be/IdjOYe7I4uA

**Comment by yshui** [comment]
I believe this is by the design of chromium. Does this happen with applications other than chromium?

If so, please consider report this issue to chromium.

**Comment by perrin4869** [comment]
I did not notice this happening with other apps, but I didn't try many either... however, under XFCE with either xfwm4 or compiz, I could use xfce4-terminal in opaque mode over any window, including chromium... So I guess the problem is with the compositor after all?

**Comment by perrin4869** [comment]
I should try compton on xfce sometime to see what happens

**Comment by yshui** [comment]
@perrin4869 the way chromium detects if itself should rerender is weird, so it might be triggered by some WM but not others.

**Comment by masaeedu** [comment]
@yshui I'm seeing the same issue with Firefox, where the video will continue playing under a translucent terminal window for a bit, then freeze. Is there some workaround or fix for this? I'm using picom 8-2 from the Arch repo here https://www.archlinux.org/packages/community/x86_64/picom/. `picom --version` shows:

```
vgit-e553e
```

**Comment by yshui** [comment]
not a picom bug. as stated, please bring this to the chromium team
