### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by xyproto** [yshui/picom#222]
Hi,

`yshui/compton` is a fork of `chjj/compton`, which is a fork of `xcompmgr-dana`, which in turn is a fork of `xcompmgr`. ([source](https://wiki.archlinux.org/index.php/Compton)).

Now that compton has been an active fork for a while, and is used for the [Arch Linux compton package](https://www.archlinux.org/packages/community/x86_64/compton/) (which I maintain), have you considered renaming it, since that seems to be tradition? :)

Best regards, and thanks for maintaining compton,
Alexander F. Rødseth

**Comment by yshui** [comment]
Yes, I have considered renaming as well, but I don't know if now is the best time to do it. Since keeping the name might help our discoverability for existing compton users.

**Comment by xyproto** [comment]
I guess renaming it will be more confusing the longer you wait? But just keeping `compton` is also fully possible, of course.

This is just a suggestion, feel free to close this issue. Appreciate the work!

**Comment by tim77** [comment]
`compton-ng` maybe? 😊

https://github.com/yshui/compton/issues/228

**Comment by yshui** [comment]
> #228 

Huh, we got assigned a name. Maybe I should seriously start thinking of a new name now.

**Comment by jtl999** [comment]
`compton-reloaded`?

In the spirit in the title "The Matrix Reloaded". Oh wait. I ain't a movie buff, but I heard the original was better :)

**Comment by yshui** [comment]
I want a name that's short, pronounceable, and searchable. And it's quite hard to come up with a name like that. I have a couple candidates right now:

* `reXco` (revival of a X compositor): looks cool? but sounds like the name of some cooperation. 
* `reXcom`, `reXcomp`: variants of the previous one
* `ncomp`, `rcomp`: look odd?
* `comppie`, `compi`, `comppi`, `comppy`: variants of trying to make compositor sounds cute.
* something completely unrelated to the word compositor?

**Comment by onodera-punpun** [comment]
Will the X be capitalized? seems a bit odd/out-of-place for binary names. As for ideas, I don't know if `compton` is actually named after the city, but if it is you could follow this trend, some other city?

**Comment by yshui** [comment]
@onodera-punpun 
> Will the X be capitalized?

not in the binary name

**Comment by xyproto** [comment]
Leland is a neighborhood in Compton. How about `leland`?

It's also possible to pick a name from one of the famous composers, for instance Bainton after the London-born composer Edgar Bainton, whos name also ends with `ton`. How about `bainton`?

> There are only two hard things in Computer Science: cache invalidation and naming things.
-- Phil Karlton

**Comment by Clyybber** [comment]
Leland sounds like an appropriate name for a wayland fork/rebuild of compton :)
This site here lists a few cities containing `x`: https://enumerated.blogspot.com/2007/07/largest-us-cities-whose-name-contains.html

**Comment by ncmprhnsbl** [comment]
hitting the thesaurus:
here's a bunch of words vaguely related to what compton does:
```
amalgam
combo 
complex
compost
compound
conglomerate
fusion
intermixture
medley
stew
synthesis
union
olio
potpourri
mishmash
hodgepodge
jumble
hash
coalesce
mingle
relate
marry

penumbra
umbra
coolness
aplomb
serenity
shade
haze
soften
cushion
relax
tenderize
quell
subdue
temper
mellow
chill
ease
repose
calm

gauzy
lucid
lucent
gossamer
sheer
tiffany
```
just to stir the pot..

**Comment by avindra** [comment]
if rename, please keep "compton" within reasonable edit distance. its the same code and hopefully the core usage of compton remains

**Comment by reaysawa** [comment]
I like Leland. However, is it such a huge departure in approach from the forked project that it deserves a totally different name?

I think "ycompton" (yshui compton) is simple, searchable and fits the bill in terms of representing the "next evolution" of the previous project.

**Comment by avindra** [comment]
Are there any reason's the old name _shouldn't_ be kept? I was personally able to switch to yshui's version without having to change my config.... _and_ I'm using an Nvidia card.

**Comment by reaysawa** [comment]
@avindra one of the reasons is so that package maintainers can differentiate between this and the other compton. Some distributions already come with a "compton" package but it's not this forked version,

**Comment by xyproto** [comment]
Following the pattern of the xcompmgr fork, `compton-yshui` could also work.

**Comment by yshui** [comment]
## picom

I am currently in favor of `picom` (pico + composite) as the new name.

You can thumb up/down this comment to let me know if you like it. I will make a decision in 2 weeks.

**Comment by anowlcalledjosh** [comment]
"picom" sounds similar to "picons" and "picocom", both of which are (meta)packages in Debian, although there's no exact name collision as far as I know. The other potential for confusion is that it might sound like a package intended for use with a Raspberry Pi.

That's not to say it isn't a good name, though!

**Comment by xyproto** [comment]
Picom is easy to write, easy to read, easy to say and easy to search for. It even ends with "com" which can be interpreted to be short for "composer". If it's too close to "picons" or "picocom", perhaps adding a "p" would differentiate it. But as long as there is no package name conflict, it shouldn't matter too much.

"picocom" is the only Arch Linux package that has a similar name.

I think "picom" will work. Best of luck with the rename!

**Comment by trvv** [comment]
I know it's kinda edgy but IMO `lucid` sounds real good

**Comment by yshui** [comment]
@trvv there is already a Lucid Widget Library, which is kept alive, and used by emacs, so a lot of people probably would think about that when you say "lucid".

Also, the word lucid is not very searchable (currently 97M results on Google)

**Comment by yshui** [comment]
Most of the rename has been done. I will rename the repository as well soon.

**Comment by jbeich** [comment]
When `XDG_CONFIG_DIRS` is not defined `picom` still falls back to `~/.compton.conf` rather than `~/.picom.conf`:
 https://github.com/yshui/picom/blob/8e0d421ba6ab252c7e0a36fa582f7b9259ffd218/src/config_libconfig.c#L71

**Comment by adberard** [comment]
yacompton

**Comment by xyproto** [comment]
Thanks for renaming. I renamed the Arch Linux package as well, in preparation for the next release.
