### ISSUE TITLE
compton crashes with i3lock/i3lock-color and multiple monitors

### ISSUE THREAD

**Issue by bakhtiyarneyman** [yshui/picom#255]
### Platform

NixOS 19.09

### GPU, drivers, and screen setup
NVidia GTX 950, proprietary drivers v435.21, two monitor configured side-by-side with xrandr.

name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 2048 MB
    Total available memory: 2048 MB
    Currently available dedicated video memory: 358 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 950/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 435.21
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 435.21
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 435.21
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

### Environment
i3-gaps
The configuration of the machine is available here
https://github.com/niobium0/nixos-configs/blob/master/hosts/iron.nix

### picom version
> compton --version
v7

> compton --diagnostics
**Version:** v7

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: None

### Drivers (inaccurate):

NVIDIA  

### Configuration:
```
active-opacity=1.000000;
backend="xrender";
fade-delta=10;
fade-exclude=[  ];
fade-in-step=0.100000;
fade-out-step=0.100000;
fading=true;
inactive-opacity=0.600000;
mark-ovredir-focused=true;
opacity-rule=[  ];
refresh-rate=0;
shadow=true;
shadow-exclude=[  ];
shadow-offset-x=-15;
shadow-offset-y=-15;
shadow-opacity=0.750000;
vsync=false;
wintypes:{ dropdown_menu={ opacity="1.0"; }; popup_menu={ opacity="1.0"; }; };
```
### Steps of reproduction

Login and open i3lock-color. 

### Expected behavior
Business as usual.

### Current Behavior
The screen flickers every few seconds. journalctl reveals that compton has been crashing.

### Stack trace
Oct 29 02:09:03 iron systemd[1345]: Started Compton composite manager.
Oct 29 02:09:03 iron compton[29381]: [ 10/29/2019 02:09:03.114 x_fence_sync ERROR ] Failed to trigger the fence.
Oct 29 02:09:03 iron compton[29381]: [ 10/29/2019 02:09:03.114 paint_all ERROR ] x_fence_sync failed, xrender-sync-fe>
Oct 29 02:09:03 iron compton[29381]: [ 10/29/2019 02:09:03.205 x_new_id FATAL ERROR ] We seems to have run of XIDs. T>
Oct 29 02:09:03 iron systemd[1]: Started Process Core Dump (PID 29383/UID 0).
Oct 29 02:09:03 iron systemd-coredump[29384]: Removed old coredump core.compton.1000.e1bfff9ba71d4a5fabbb493cb01b4b66>
Oct 29 02:09:03 iron systemd[1345]: compton.service: Main process exited, code=dumped, status=6/ABRT
Oct 29 02:09:03 iron systemd[1345]: compton.service: Failed with result 'core-dump'.
Oct 29 02:09:03 iron systemd-coredump[29384]: Process 29381 (compton) of user 1000 dumped core.
Oct 29 02:09:03 iron systemd[1]: systemd-coredump@119829-29383-0.service: Succeeded.
Oct 29 02:09:06 iron systemd[1345]: compton.service: Service RestartSec=3s expired, scheduling restart.
Oct 29 02:09:06 iron systemd[1345]: compton.service: Scheduled restart job, restart counter is at 8.
Oct 29 02:09:06 iron systemd[1345]: Stopped Compton composite manager.

[coredump.zip](https://github.com/yshui/picom/files/3782628/coredump.zip)

### Other details
N/A

**Comment by yshui** [comment]
Does it happen _immediately every time_ you start i3lock?

Can you run compton with `--log-level=debug` and attach the logs?

**Comment by niobium0** [comment]
Thanks for paying attention to this! 

>Does it happen immediately every time you start i3lock?

Yes.


> Can you run compton with --log-level=debug and attach the logs?

Here you go.
```
[ 10/31/2019 00:09:08.368 _draw_callback DEBUG ] Exiting critical section
[ 10/31/2019 00:09:13.296 ev_handle DEBUG ] event PropertyNo serial 0x00002491 window 0x02a00003 "fish /home/bakhtiyar"
[ 10/31/2019 00:09:13.306 ev_handle DEBUG ] event PropertyNo serial 0x000024bf window 0x02a00003 "i3lock /home/bakhtiyar"
[ 10/31/2019 00:09:13.306 ev_handle DEBUG ] event PropertyNo serial 0x000024bf window 0x02a00003 "i3lock /home/bakhtiyar"
[ 10/31/2019 00:09:13.307 ev_handle DEBUG ] event PropertyNo serial 0x000024bf window 0x02a00003 "i3lock /home/bakhtiyar"
[ 10/31/2019 00:09:13.307 ev_handle DEBUG ] event PropertyNo serial 0x000024bf window 0x02a00003 "i3lock /home/bakhtiyar"
[ 10/31/2019 00:09:13.308 ev_handle DEBUG ] event CreateNoti serial 0x00002500 window 0x02c00003 "(Failed to get title)"
[ 10/31/2019 00:09:13.308 add_win DEBUG ] Adding window 0x02c00003
[ 10/31/2019 00:09:13.308 ev_handle DEBUG ] event  MapNotify serial 0x00002500 window 0x02c00003 "(Failed to get title)"
[ 10/31/2019 00:09:13.308 _draw_callback DEBUG ] Delayed handling of events, entering critical section
[ 10/31/2019 00:09:13.317 fill_win DEBUG ] Managing window 0x02c00003
[ 10/31/2019 00:09:13.317 map_win DEBUG ] Mapping (0x02c00003 "(null)")
[ 10/31/2019 00:09:13.317 win_determine_shadow DEBUG ] Determining shadow of window 0x02c00003 ((null))
[ 10/31/2019 00:09:13.317 win_set_shadow DEBUG ] Updating shadow property of window 0x02c00003 ((null)) to 1
[ 10/31/2019 00:09:13.317 map_win DEBUG ] Window (0x02c00003) has type normal
[ 10/31/2019 00:09:13.317 win_determine_shadow DEBUG ] Determining shadow of window 0x02c00003 ((null))
[ 10/31/2019 00:09:13.317 map_win DEBUG ] Window 0x02c00003 has opacity 0.000000, opacity target is 1.000000
[ 10/31/2019 00:09:13.318 _draw_callback DEBUG ] Exiting critical section
[ 10/31/2019 00:09:13.318 ev_handle DEBUG ] event   FocusOut serial 0x0000251c window 0x0100008b "i3lock /home/bakhtiyar"
[ 10/31/2019 00:09:13.318 ev_focus_out DEBUG ] { mode: NotifyGrab, detail: NotifyVirtual }

[ 10/31/2019 00:09:13.318 _draw_callback DEBUG ] Delayed handling of events, entering critical section
[ 10/31/2019 00:09:13.318 _draw_callback DEBUG ] Exiting critical section
[ 10/31/2019 00:09:13.345 x_new_id FATAL ERROR ] We seems to have run of XIDs. This is either a bug in the X server, or a resource leakage in compton. Please open an issue about this problem. compton will die.
fish: “compton --config /nix/store/k9z…” terminated by signal SIGABRT (Abort)
```

**Comment by yshui** [comment]
@niobium0 can you attach the _complete_ log file?

**Comment by niobium0** [comment]
>compton --config /nix/store/k9z43ks8c093mm262kixw47qc35qh3yx-compton.conf --log-level=debug > /tmp/compton.log.txt 2>&1

[compton.log.txt](https://github.com/yshui/picom/files/3797086/compton.log.txt)

Here you go.

**Comment by yshui** [comment]
Hmm, I cannot really understand what is going on here.

I have a guess, so I added some debug prints to catch it. Can you build from the `debug-xid-failure` branch and attach the log here?

Thanks.

**Comment by niobium0** [comment]
Sorry for the delay, here you go.

[compton.log.txt](https://github.com/yshui/picom/files/3808039/compton.log.txt)

**Comment by niobium0** [comment]
Sorry for the delay, here you go.

[compton.log.txt](https://github.com/yshui/picom/files/3808108/compton.log.txt)

**Comment by niobium0** [comment]
Is everything alright with the dump? Is there any other way I can help?

**Comment by yshui** [comment]
@niobium0 It's alright. I just hadn't got the time to look at it, sorry about that.

Looks like we encountered a connection error with X, and this connection error is somehow triggered by i3lock. I will look into this.

**Comment by pengux** [comment]
I too get this error `x_new_id FATAL ERROR ] We seems to have run of XIDs...` and I'm using bspwm. This problem seems to happen more often when I connect an external monitor.

**Comment by manuher** [comment]
I have the same issue using betterlockscreen (i3lock-color). Also getting `x_new_id FATAL ERROR ] We seems to have run of XIDs...` the moment I lock the screen.

**Comment by yshui** [comment]
@pengux @manuher @bakhtiyarneyman can you also attach your Xorg logs as well?

**Comment by yshui** [comment]
It would also be nice if you can run picom under [xtrace](https://github.com/yuq/xtrace) and attach the trace when this bug happens (beware: there will a lot of outputs)

**Comment by PandorasFox** [comment]
here's a ~4k line [gist](https://gist.github.com/PandorasFox/2eb0769651519c0ccdf6a54e8e4549b1) of my xtrace of picom. My specific invocation was `x11trace > /tmp/picom_xtrace & sleep 1; DISPLAY=:9 picom -b && ~/bin/xsecurelock.sh`.

I have a 3440x1440 primary display, and a 2160x3840 secondary portrait display. Invoking xsecurelock causes picom to immediately crash.

**Comment by yshui** [comment]
BTW,
@PandorasFox @pengux @manuher What graphic cards do you use?

**Comment by PandorasFox** [comment]
I'm using an AMD 5700XT

**Comment by yshui** [comment]
Thanks, I can reproduce this locally now.

**Comment by yshui** [comment]
Does disabling shadow help?

**Comment by PandorasFox** [comment]
Yep, setting `shadow = false` in my config file makes it no longer crash. I'll be rolling with that for now.

**Comment by yshui** [comment]
So the problem is the shadow image created by picom exceeded Xorg's maximum request length, causing the Xorg connection to shutdown.

The solution would be to send the shadow image piecemeal, shouldn't be hard.

**Comment by yshui** [comment]
Should have been fixed in `next`.
