### ISSUE TITLE
Picom Dont Compile/Link  Anymore On FreeBSD.

### ISSUE THREAD

**Issue by javashin** [yshui/picom#262]
https://gist.github.com/javashin/c01ca00938934f9875f01aca4aeef520    Build LOG

file_watch making troubles here
ld: error: undefined symbol: inotify_init1
>>> referenced by file_watch.c
>>>               src/25a6634@@picom@exe/file_watch.c.o:(file_watch_init)
>>> referenced by file_watch.c
>>>               src/25a6634@@picom@exe/file_watch.c.o:(file_watch_init)

ld: error: undefined symbol: inotify_add_watch
>>> referenced by file_watch.c
>>>               src/25a6634@@picom@exe/file_watch.c.o:(file_watch_add)
c++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

i got last version of libn , whats going on ?

last time i compiled picom was 

ls -lash /usr/local/bin/picom
194 -rwxr-xr-x  1 root  wheel   338K Nov  4 19:27 /usr/local/bin/picom

**Comment by javashin** [comment]
before this commit https://github.com/yshui/picom/commit/0e5be97f9456fcc6ed06699693b58dc4e61b9792

everything is OK. 

tested on FREEBSD 13-CURRENT

**Comment by javashin** [comment]
Thanks in Advance,

looks like file_watch is only going to work with linux .
may an option to disable this file_watch ? 
i dont use any config file anyways . maybe other people are with me too

**Comment by yshui** [comment]
@javashin I am aware of this issue. I will fix it as soon as I get off work.

**Comment by yshui** [comment]
@javashin Can you check if it builds now?

**Comment by javashin** [comment]
i would
