### ISSUE TITLE
100% opacity not working

### ISSUE THREAD

**Issue by jemand2001** [yshui/picom#264]
### Platform

Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64

### GPU, drivers, and screen setup

NVidia GTX 745, driver 418.74-1, one screen
glxinfo:
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 4096 MB
    Total available memory: 4096 MB
    Currently available dedicated video memory: 3865 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 745/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 418.74
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 418.74
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 418.74
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment

awesomewm

### picom version

vgit-42cd5 (just built)

### Configuration (relevant parts):
```conf
backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = false;

inactive-opacity = 0.8;
active-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = true;

opacity-rule= [
	      "100:class_g = 'firefox'"
]
```
### Steps of reproduction

1. open a firefox window
2. open another window on the same workspace

### Expected behavior
the firefox window does not become transparent
### Current Behavior
it does become transparent, conforming to `inactive-opacity`

### Other details

[video evidence](https://youtu.be/ulVLG-PsBDM)

**Comment by jemand2001** [comment]
i actually only switched from compton to picom because of this.
After some experiments, it actually feels like picom is using a cached version of my config file? except i don't see how it would do that, since i'm running it with --config <myfile> every time

**Comment by yshui** [comment]
@jemand2001 you can figure out which config is used by running `picom --diagnostics`

**Comment by yshui** [comment]
@jemand2001 Looks like it's indeed a problem, I will investigate.

**Comment by jemand2001** [comment]
`picom --diagnostics` says it's using the right config file, but i can see that it's not (changes i make to other clients' opacity don't show up either)

**Comment by mighty9245** [comment]
@jemand2001, try to make a change that'll be definitely working and noticabe, e. g. enable shadows and configure them to be barely transparent. if the change doesn't appear then you probably have encountered a bug in the new configuration file watching mechanism (but i'm not sure that it is working and enabled by default, haven't tested it yet).

@yshui, if you'll work with opacity-related code, could you please take a look at the last two comments in #212? i wonder does `frame-opacity` work for you or if it's indeed driver bug.

**Comment by mighty9245** [comment]
@jemand2001, try setting the `inactive-opacity-override` to false.

**Comment by jemand2001** [comment]
alright, i followed your advice (set shadows to 10 px and almost fully opaque) and it did show up -> file watcher seems to be working fine, and it does use my config file.
setting `inactive-opacity-override` to false did nothing. actually, it seems that pretty much only the transparency/opacity settings are frozen: i have a rule for a transparent discord client and changing that doesn't affect the actual transparency of the window

**Comment by jemand2001** [comment]
the discord rule worked perfectly under compton.

**Comment by mighty9245** [comment]
hm, setting `inactive-opacity-override` to false in the configuration file you provided (it's set to true there) worked for me and i got the behaviour you probably wanted to get: all unfocused window except firefox are transparent. in both cases the upper right window is focused.
![0](https://user-images.githubusercontent.com/52252283/68701575-23157c80-0598-11ea-8f73-9ebeeb7a82a2.png)
![1](https://user-images.githubusercontent.com/52252283/68701580-27419a00-0598-11ea-87c3-57fdd348de66.png)

**Comment by mighty9245** [comment]
i also tested setting `inactive-opacity-overrider` with experimental backends and with picom built from the latest commit, still works. is behaviour you wanted to get shown on my second screenshot in the previous message?

**Comment by jemand2001** [comment]
yes, that is the result i wanted. however, as you can see from the first screenshot, i do not get the same results.
Could i have an error somewhere else in my config file that is causing this? (remember, i only posted the parts of the file that i thought were relevant at the time.) However, testing just the minimal version i posted still does not give me the same result (second screenshot).
![screenshot1](https://user-images.githubusercontent.com/24275520/68702587-61576f80-0589-11ea-8473-2867aa0aaead.png)
![screenshot2](https://user-images.githubusercontent.com/24275520/68704716-09bb0300-058d-11ea-8c3a-95246862f89f.png)

**Comment by mighty9245** [comment]
**--config**, not **-conf** (second screenshot)

**Comment by jemand2001** [comment]
good catch, still nothing
![image](https://user-images.githubusercontent.com/24275520/68705270-0bd19180-058e-11ea-87b7-b7a620bba5b5.png)

**Comment by mighty9245** [comment]
even with the minimal configuration file... weird. might be a driver problem?

could you try `xprop | grep WM_CLASS` on firefox window? just to be sure

**Comment by jemand2001** [comment]
thanks for the tip! apparently firefox' windows are of class "Firefox", not "firefox".
this doesn't explain why my discord is still transparent though, but at least now one of my problems is fixed.

**Comment by mighty9245** [comment]
oh, so the issue is fixed?

you may also try other selectors, such as `class_i` which is the first field of the `WM_CLASS` (`class_g` is the second)

**Comment by jemand2001** [comment]
well, the thing i opened this ticket for is fixed.
if i may ask, is there a list of selectors and what they look for?

**Comment by mighty9245** [comment]
of course there is, you can find them and their description on the compton's man page: `man compton`, "format of conditions" section. i highly recommend to read it because it also explains not so obvious match types and operators (`=`, `*=`, `^=` and so on...)

**Comment by jemand2001** [comment]
well then. thank you so much for your help and patience today, @mighty9245
