### ISSUE TITLE
Problem when resizing windows

### ISSUE THREAD

**Issue by kberkut** [yshui/picom#276]
I'm have problem when resizing windows. Resizing is stepped. I'm saved small video for demonstrate it. [https://radikal.ru/video/esbxg32Ni9o](https://radikal.ru/video/esbxg32Ni9o)

### Platform
OS: Arch Linux x86_64 
Kernel: 5.4.2-arch1-1 

### GPU, drivers, and screen setup
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz 
GPU: AMD ATI 04:00.0 Picasso
mesa 19.2.7-1
glu 9.0.1-1
xf86-video-amdgpu 19.1.0-1

glxinfo -B
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD RAVEN (DRM 3.35.0, 5.4.2-arch1-1, LLVM 9.0.0) (0x15d8)
    Version: 19.2.7
    Accelerated: yes
    Video memory: 2048MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 1808 MB, largest block: 1808 MB
    VBO free aux. memory - total: 3026 MB, largest block: 3026 MB
    Texture free memory - total: 1808 MB, largest block: 1808 MB
    Texture free aux. memory - total: 3026 MB, largest block: 3026 MB
    Renderbuffer free memory - total: 1808 MB, largest block: 1808 MB
    Renderbuffer free aux. memory - total: 3026 MB, largest block: 3026 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 2048 MB
    Total available memory: 5120 MB
    Currently available dedicated video memory: 1808 MB
OpenGL vendor string: X.Org
OpenGL renderer string: AMD RAVEN (DRM 3.35.0, 5.4.2-arch1-1, LLVM 9.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.2.7
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.2.7
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.2.7
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment
WM: i3 

### picom version
picom v7.5
picom --diagnostics
[ 08.12.2019 06:47:39.761 register_cm FATAL ERROR ] Another composite manager is already running

I'm use gdm for login. After off gdm.service, reboot and startx I'm have same error. 

### Configuration:
```
picom -bcCG
picom -bcCG --backend xrender 
picom -bcCG --backend xrender --vsync
```

### Steps of reproduction
resize windows

**Comment by mighty9245** [comment]
first, your link is broken
second, kill running picom instance first and then run `picom --diagnostics` (@yshui, unability to query diagnostics information when another picom instance is running seems to be a bug, isn't it?)
third, you should be able to use glx backend, so use it, because it's overall better than xrender one
fourth, does it happen with `--experimental-backends` aswell?

**Comment by kberkut** [comment]
Added new screencast where you see:
1) runing "picom --experimental-backends" and resizing windows
2) showed error for one exemplar picom when run "picom --diagnostics"
3) showed resizing windows without picom

[https://radikal.ru/video/j3Vtk7WjvIL](https://radikal.ru/video/j3Vtk7WjvIL)

Resizing is stepped for each window.

picom --diagnostics

```
**Version:** v7.5
### Extensions:
* Shape: Yes
* XRandR: Yes
* Present: Present
### Misc:
* Use Overlay: Yes
* Config file used: /etc/xdg/picom.conf
### Drivers (inaccurate):
AMDGPU, Radeon 
```

**Comment by mighty9245** [comment]
does it happen if you explicitly set glx backend? (no need to record screencast to prove this)
`picom --backend glx`
`picom --backend glx --experimental-backends`

**Comment by kberkut** [comment]
Both options give the same result: the size of the windows change in steps.

PS: Despite this, it is much more pleasant to work with picom. Thanks for its development !!!

**Comment by mighty9245** [comment]
then wait for @yshui, i hope the information that we have collected will help him a bit.

can't reproduce btw, but i'm on bspwm and intel integrated graphics so it might be a driver bug

**Comment by kberkut** [comment]
I have problem with resize windows and suspend regime. When picom not loaded resize and suspend regime working perfectly.
When picom is loaded this process is have 100% load for processor:
/usr/lib/Xorg vt2 -displayfd 3 -auth /run/user/1000 /gdm/Xauthority -nolistentcp -backgroundnone -noreset -keeptty -verbose 3

**Comment by yshui** [comment]
@kberkut what if you disable shadow?

**Comment by kberkut** [comment]
> @kberkut what if you disable shadow?

After some updating of archlinux, resizing windows using picom works fine, shadows is enabled.
Thank you for create of picom! 


------------------------
picom v7.5

OS: Arch Linux x86_64 
Kernel: 5.5.7-arch1-1
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz 
GPU: AMD ATI 04:00.0 Picasso

**Comment by mighty9245** [comment]
@kberkut, you can close the issue if it's resolved

**Comment by kberkut** [comment]
Resolved.

**Comment by yshui** [comment]
@kberkut did you upgrade your GPU in between? as I suspect this is a driver related issue

**Comment by kberkut** [comment]
> @kberkut did you upgrade your GPU in between? as I suspect this is a driver related issue

Perhaps in the process of some update, the GPU driver was updated. I use a standard driver.
Now the system has installed:
glu 9.0.1-1
mesa 19.3.4-2
xf86-video-amdgpu 19.1.0-1

**Comment by yshui** [comment]
@kberkut Ok. Glad your problem is solved.

**Comment by Alexey104** [comment]
I have absolutely the same behavior on Arch and i3wm with both free and proprietary nvidia drivers(gtx 770). Tried switching between xrender/glx, tried to run with --experimental-backends, disabled shadows/blur/transparency, and nothing helps me to solve this. When resizing a window, the window is not being redrawn while the mouse cursor is moving. Only when the cursor is stopped, the window size is being visually updated. But window dragging is ideally smooth. Maybe this is because of nvidia.
