### ISSUE TITLE
i3-gaps blur glitch

### ISSUE THREAD

**Issue by Psykopear** [yshui/picom#282]
### Platform
ArchLinux x86-64

### GPU, drivers, and screen setup
`glxinfo -B` output
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2)  (0x3e9b)
    Version: 19.2.7
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.2.7
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 19.2.7
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.2.7
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment
i3-gaps

### picom version
```
$ picom --version
vgit-37532
```

### Configuration:
I can reproduce it with this configuration
```
backend = "glx";
blur:
{
  method = "gaussian";
  size = 10;
  deviation = 10;
};
```

### Steps of reproduction
1. in i3-gaps, open one or more windows with a titlebar
2. run picom

_edit:_ The problem occurs only with tiled windows, floating ones works as expected

### Expected behavior
Blur should only apply to the window and its frame

### Current Behavior
The background around the frame and windows gets blurred too

### Other details
Here is a screenshot to show the problem
![bug-picom-blur](https://user-images.githubusercontent.com/5968682/70709898-4be77980-1cde-11ea-8c38-44db9f16c984.png)

**Comment by yshui** [comment]
I suspect i3-gap is probably creating an invisible frame around the window?

**Comment by Psykopear** [comment]
I think so, if I remove the blur on the frame with:
```
blur-background-exclude = [
    "class_g = 'i3-frame'",
];
```

It works ok, the background is still blurred on the window, but the frame is not (and neither the background outside the window).

**Comment by yshui** [comment]
@Psykopear so problem solved?

**Comment by Psykopear** [comment]
Well, I would like to be able to have the blur on the frame as it is on the rest of the window, without blurring the background outside, but if this is not a problem that should be solved here in Picom you can close the issue

**Comment by Airblader** [comment]
Titlebars are not supported / working well with gaps. This occurs because of how i3 renders the frame windows where for a split window it's actually the parent container that has the frame and the title bars of all children are drawn onto that one window. This is mostly done because of  stacked layouts and we have an open issue in i3 to try and resolve this (although not an active issue).

**Comment by Psykopear** [comment]
Ok, thank you @Airblader for the comment. I'm closing this issue then.
