### ISSUE TITLE
Opacity in all apps

### ISSUE THREAD

**Issue by Sup3r-Us3r** [yshui/picom#290]
After I installed the proprietary drivers for my Nvidia video card, opacity has taken over all my apps, and what bothers me most is the Google Chrome browser, with transparency making content visibility impossible, can anyone help me? I just want to have opacity on my Termite terminal, and on my Polybar bar, that's all.

- OS: Arch Linux
- WM: i3wm
- Terminal: Termite
- Browser: Google Chrome
- Bar: Polybar

My config: https://pastebin.com/raw/qwa4T3Xr

**Comment by mighty9245** [comment]
so, before installing the proprietary drivers you was running picom with the same config fine without this issue? if yes, then it's probably a driver problem.

**Comment by Sup3r-Us3r** [comment]
@mighty9245  Yes I was running without any problem, but I don't get any error when running picom, do you know what can solve this problem?

**Comment by mighty9245** [comment]
then it's a driver problem. either picom is missing something, or it's an actual driver bug and requires either upstream report to be fixed or a workaround in picom.

**Comment by clort81** [comment]
I confirm this problem on nvidia jetson nano.  Sddenly i can't get compton transparency.
