### ISSUE TITLE
Help text percentages are not escaped correctly

### ISSUE THREAD

**Issue by asparagii** [yshui/picom#291]
Help text has not been escaped correctly at least since 9880245200eb822ca53508d9dec3e2b481d90765

If you take a look at the help message, you will notice that memory addresses are being printed instead of '%'.

```
$ picom --help
(...)
--glx-no-stencil
  GLX backend: Avoid using stencil buffer. Might cause issues
  when rendering transparent content. My tests show a 15 0x7ffd332d83b0erformance
  boost.
(...)
```

**Comment by mighty9245** [comment]
nice catch
