### ISSUE TITLE
Glx / i3: Switching to uninitiated workspace shows content of previous workspace (not desktop background)

### ISSUE THREAD

**Issue by d4h0** [yshui/picom#297]
Hi,

here is the requested information:

### Platform

Arch Linux (current) x86_64

### GPU, drivers, and screen setup

Intel HD 4600 + NVIDIA GeForce 730M (Optimus) – only the Intel GPU is used and configurated
mesa 19.3.2-2 
xf86-video-intel 1:2.99.917+899+gf66d3954-1
One laptop monitor (I didn't configure anything, besides a few Xorg settings)

glxinfo -B:

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) Haswell Mobile  (0x416)
    Version: 19.3.2
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.3.2
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 19.3.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 19.3.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
```

### Environment

I use i3-gaps

### picom version

$ picom --version
vgit-e1d9e

`picom --diagnostics` produces no output

I use this Arch Linux AUR package: [aur/picom-git 1287_Next.6.ge1d9e95_2019.12.13-1](https://aur.archlinux.org/packages/picom-git/).

I'm using the `--experimental-backends` flag

### Configuration:

```
log-level = "warn";                                             
log-file = "/home/dh/.config/picom/log.txt"                     
shadow = false;                                                 
fading = false;                                                 
vsync = true; 
backend = "glx";  

# Misc / not sure if needed                                     
detect-rounded-corners = true;                                  
detect-client-opacity = true;                                   
detect-transient = true;                                        
detect-client-leader = true;

```

### Steps of reproduction

1. start i3
2. open an application in workspace 1
3. switch to workspace 2 (which is uninitiated / has no open windows)

### Expected behavior

An empty workspace should be shown (with my desktop background)

### Current Behavior

The visual content of the previous workspace is shown (it's not possible to interact with it, however).

If I then start an application in workspace 2, that application is shown normally.

This doesn't happen with the `xrender` or `xr_glx_hybrid` backend, but these backends have problems with screen tearing (which I'd like to fix with picom).

**Comment by yshui** [comment]
Can you capture an apitrace of picom and attach it here?

**Comment by d4h0** [comment]
Yes, no problem.

Should I use "--api gl" or "--api egl"?

The command that I would run is `apitrace trace --api [gl|egl|d3d7|d3d8|d3d9|dxgi] /path/to/picom [args...]`, right?

**Comment by yshui** [comment]
@d4h0 `gl`, you can just run `apitrace trace /path/to/picom`

**Comment by Aaahh** [comment]
what are you using as a background image setter, are you using any programs that draw to the root window?

**Comment by d4h0** [comment]
@yshui: Thanks, I have used the following command:

`apitrace trace /usr/bin/picom --experimental-backends`

I have attached a zip archive with the trace file.

I started apitrace, moved to an empty i3 workspace (were the above-described problem happened), and then went back to the workspace with apitrace and exited it with ctrl-c.

[picom.zip](https://github.com/yshui/picom/files/4339728/picom.zip)

**Comment by d4h0** [comment]
@Aaahh: I'm not using any background image, my background is black. Maybe I defined that color somewhere, but I don't remember where (otherwise, this would be the default configuration. Probably of i3). 

Should I try to find out where the background color is defined?

**Comment by Aaahh** [comment]
@d4h0 try killing picom when it happens, does it go away? then restart picom
I'm having it happen to me now as well. I am fairly certain it is due to a setting in the options but I haven't narrowed it down.

**Comment by Aaahh** [comment]
Here's a picture describing the problem (I think)
I can recreate it by activating my hdmi on xrandar while picom is running (or deactivating if it's active) (happens even on xrender so I think this is another bug but related) 
![2020-03-22-1584907530_screenshot_4480x1080](https://user-images.githubusercontent.com/3966556/77259665-7a6bdd80-6c59-11ea-9fa7-28ab8c004647.jpg)

**Comment by yshui** [comment]
Can you check if this has been fixed in the latest `next` branch?

**Comment by d4h0** [comment]
@yshui: It's fixed! Thanks a milllion :)

For Arch Linux users that have this problem: You can install 'picom-git' from AUR to install the `next` branch (I had the package already installed and for some reason had to reinstall it to update Picom).

@Aaahh: The problem was something with the new backend. With the '--experimental-backends' option there was the above problem, without it there was no problem.
