### ISSUE TITLE
Shadow Problems On Blur

### ISSUE THREAD

**Issue by xcbdz** [yshui/picom#298]
### Platform

Arch Linux

### GPU, drivers, and screen setup

Intel Graphics, xf86-video-intel
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) Ivybridge Mobile  (0x166)
    Version: 19.3.2
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.2
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL core profile version string: 4.2 (Core Profile) Mesa 19.3.2
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 19.3.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 19.3.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```

### Environment

Awesome Window Manager

### picom version

`Picom vgit-e1d9e`

### Configuration:
```
# Shadow
shadow = false;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
log-level = "warn";
# log-file = "/path/to/your/log/file";
shadow-opacity = 0.0;
# shadow-red = 0.0;
# shadow-green = 0.0;
# shadow-blue = 0.0;
shadow-exclude = [
	"name = 'Notification'",
	"class_g = 'Conky'",
	"class_g ?= 'Notify-osd'",
	"class_g = 'Cairo-clock'",
	"_GTK_FRAME_EXTENTS@:c"
];
# shadow-exclude = "n:e:Notification";
# shadow-exclude-reg = "x10+0+0";
# xinerama-shadow-crop = true;

# Opacity
# inactive-opacity = 0.8;
# active-opacity = 0.8;
# frame-opacity = 0.7;
# inactive-opacity-override = false;
# inactive-dim = 0.2;
# inactive-dim-fixed = true;



blur:
{
	method = "gaussian";
	size = 20;
	deviation = 5.0;
	kernel = "11x11gaussian";
};

# blur-background = true;
# blur-background-frame = true;
blur-kern = "3x3box";
# blur-kern = "5,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1";
# blur-background-fixed = true;
blur-background-exclude = [
	"window_type = 'dock'",
	"window_type = 'desktop'",
	"_GTK_FRAME_EXTENTS@:c"
];
# opacity-rule = [ "80:class_g = 'URxvt'" ];

# max-brightness = 0.66

# Fading
fading = true;
# fade-delta = 30;
fade-in-step = 0.03;
fade-out-step = 0.03;
# no-fading-openclose = true;
# no-fading-destroyed-argb = true;
fade-exclude = [ ];

# Other
backend = "glx";
mark-wmwin-focused = true;
mark-ovredir-focused = true;
# use-ewmh-active-win = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0;
vsync = true;
# sw-opti = true;
# unredir-if-possible = true;
# unredir-if-possible-delay = 5000;
# unredir-if-possible-exclude = [ ];
focus-exclude = [ "class_g = 'Cairo-clock'" ];
detect-transient = true;
detect-client-leader = true;
invert-color-include = [ ];
# resize-damage = 1;

# GLX backend
# glx-no-stencil = true;
# glx-no-rebind-pixmap = true;
# xrender-sync-fence = true;
use-damage = true;

# Window type settings
wintypes:
{
  tooltip = { fade = true; shadow = false; opacity = 0.75; focus = true; full-shadow = false; };
  dock = { shadow = false; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 0.8; }
  dropdown_menu = { opacity = 0.8; }
};
```

### Steps of reproduction

1. Enable the blur using the blur:{ .. } just like in my config above.
2. Add opacity effect to terminals.
3. Remove gaps.
4. `shadow = false;`

### Expected behavior
There's should be no shadow effects on terminal because I already disabled it using `shadow = false;` in `picom.conf`.

### Current Behavior
There are some shadows between the terminals.
![image](https://user-images.githubusercontent.com/56459896/72301347-7643a280-36a1-11ea-9c90-1eefea6e877d.png)

### Other details

If I set the blur method to `none`, the line shadows disappeared.

![image](https://user-images.githubusercontent.com/56459896/72301474-d1759500-36a1-11ea-833f-10fd8f641ec3.png)

Edit: I'm using experimental-backends to launch picom. Just like this `picom -b --experimental-backends --dbus --config picom.conf `.

**Comment by xcbdz** [comment]
I found out that that is not actually a shadow. I think it's a blur effect in gaussian when two or more objects(docks, normal windows, etc) are next to each other. The darkening disappears when I add `gaps` or space in between. I just want to make it **flat** looking. Is there a way to disable it, @yshui ? Sorry for inconvenience.

**Comment by yshui** [comment]
@xcbdz yes, you are correct. 

there is nothing to "disable" here, picom is just doing its job applying blur as it should. 

if you want the blur to always blur your wallpaper, instead of what's underneath the window, then I could do something about it.

**Comment by xcbdz** [comment]
> there is nothing to "disable" here, picom is just

I see...so there's no way to remove the scatter effect... Thanks! I thought it was a shadow bug

> if you want the blur to always blur your wallpaper, instead of what's underneath the window, then I could do something about it.

Ooh, that is nice to have. And I think it is good to have rules for transparent clipping like exclude[]. 

Anyway thanks for maintaining picom. I'll close this issue now
