### ISSUE TITLE
Picom freezes everything on screen except the mouse cursor.

### ISSUE THREAD

**Issue by lorecast162** [yshui/picom#304]
### Platform

Arch Linux ARM armv7h
### GPU, drivers, and screen setup

xf86-video-fbturbo-git 199.f9a6ed7-4
mesa 19.3.2-2
output from glxinfo -B:
[Here](https://pastebin.com/bnjHcHxc)

### Environment

i3-gaps with polybar
### picom version

v7.5
### Configuration:
[Here](https://pastebin.com/xNme4FRs)

### Steps of reproduction

1. Run `picom`

### Expected behavior
It should work and get me some effects right?
### Current Behavior
It just freezes all my windows  and changing workspace just stays put. The only thing that moves is the mouse cursor. I can hop into a VT to terminate picom tho and everything goes back to normal.
### Other details

[Here](https://pastebin.com/RAFud84S) is a log I got from running `picom --log-level=trace --log-file=picom.log`.

[Here](https://www.youtube.com/watch?v=QKi7YxobLnA) is a video I took with my phone that shows the issue.
Note that I am using picom for the first time here.

**Comment by yshui** [comment]
Hi, can you get a stacktrace when picom freezes?

**Comment by yshui** [comment]
I have to put this on low priority as this problem manifest on a uncommon setup (ARM with fbturbo).

In the mean time, as you don't have hardware accelerated OpenGL anyway (mesa is using llvmpipe), you could try using the xrender backend instead of glx, that might give you better outcome.

**Comment by Xaymup** [comment]
I am also experiencing this issue ever since upgrading with yay. Downgrading to the previous version fixes it.

**Comment by emilBeBri** [comment]
I am also experienceing this issue

**Comment by vince6794** [comment]
Me too. Frozen desktop. 
I'm going to investigate if picom is the problem because sometimes I can interact in some way with the i3wm: I can write some command to the already opened terminal, but without receiving any response.

I'll try disabling picom for several days to see what happens.
I've observed that screen sharing also crashes the app (skype, teams, etc.) or completely freezes the system (needs a manual reboot)

**Comment by MrIvanPlays** [comment]
I'm experiencing this at random.

**Comment by emilBeBri** [comment]
It stopped happening to me after i uograded to Linux kernel 5.19 instead of default  manjaro 5.15

**Comment by yshui** [comment]
Original issue is related to missing hardware accelerated graphics. If you are experiencing this with a proper gpu driver installed, please open a new issue.
