### ISSUE TITLE
Cannot build on Ubuntu 19.10 (pkgconfig/libpcre not found)

### ISSUE THREAD

**Issue by yochaigal** [yshui/picom#305]
### Environment

Kernel: 5.3.0-26-generic x86_64 
Desktop: Xfce 4.14.1 
Distro: Ubuntu 19.10 (Eoan Ermine) 
Dependencies installed:
libxext-dev libxcb1-dev libxcb-damage0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-randr0-dev libxcb-composite0-dev libxcb-image0-dev libxcb-present-dev libxcb-xinerama0-dev libpixman-1-dev libdbus-1-dev libconfig-dev libxdg-basedir-dev libgl1-mesa-dev  libpcre2-dev  libevdev-dev uthash-dev libev-dev

Pulling repo and running build as suggested in readme results in:
```
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config libxdg-basedir --libs` -> 0
-L/usr/lib/x86_64-linux-gnu -lxdg-basedir
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config libxdg-basedir --libs` -> 0
-lxdg-basedir
Run-time dependency libxdg-basedir found: YES 1.2.0
Pkg-config binary for MachineChoice.HOST is cached.
Determining dependency 'libpcre' with pkg-config executable '/usr/bin/pkg-config'
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config --modversion libpcre` -> 1

CMake binary for MachineChoice.HOST is cached as not found
No CMake binary for machine MachineChoice.HOST not found. Giving up.
Run-time dependency libpcre found: NO (tried pkgconfig)

src/meson.build:47:1: ERROR: Dependency "libpcre" not found, tried pkgconfig
```

I have libpcre2-dev installed. Previous builds of picom worked fine.

**Comment by ilya-bystrov** [comment]
`apt-get install libpcre3-dev` solved similar issue for me (on Ubuntu 18.04)

**Comment by yochaigal** [comment]
Thanks, this resolved my issue.

**Comment by nong10** [comment]
Thanks, I met the same problem it really helps.

**Comment by rifqempul** [comment]
this should be on readme

**Comment by MainManu** [comment]
I am having the same problem on ubutnu 20.4
However, it still persists after installing libpcre3-dev
