### ISSUE TITLE
SIGUSR1 frezzes picom

### ISSUE THREAD

**Issue by bricewge** [yshui/picom#306]
### Platform

Guix 9bad3c x86_64

### GPU, drivers, and screen setup

xf86-video-intel 2.99.917-15.f66d395 with 1 or 2 monitors (doesn't matter).

### Environment
bspwm

### picom version
v7.5

### Configuration:
```
backend = "glx";
vsync = true;
```

### Steps of reproduction
1. `picom`
2. `pkill -USR1 picom`

### Expected behavior
Picom should restart correctly as with other backends.

### Current Behavior
Nothing on the display get updated anymore except the cursor. Events happen thought since after killing picom for good I can see what I did blindly while picom was frozen.

### Other details
It only happen with the `glx` backend which at the moment is the only one that remove tearing on my setup.
Fail in the same way as #304.

**Comment by yshui** [comment]
Do you have any logs?

**Comment by bricewge** [comment]
Here you go!
Got the [log](https://github.com/yshui/picom/files/4171952/picom.log) by running `picom --log-level=trace --log-file=picom.log --config=./config`. It seems that the first time I ran the command the bug didn't triggered but the subsequent ones did; it may be some fluke from my part though.

The issues I referenced contains some logs too.

**Comment by yshui** [comment]
Hmmm, i don't see anything particularly wrong in the logs. Do you know where picom is stuck at? e.g. a stack trace.

I tried repeatedly sending SIGUSR1 but i cannot reproduce this problem locally.

**Comment by bricewge** [comment]
I got you a [stacktrace](https://github.com/yshui/picom/files/4173937/gdb.txt) with its [log](https://github.com/yshui/picom/files/4173938/picom.log).

I'm here I you need more info.

**Comment by yshui** [comment]
Can you get the stacktrace when picom is stuck, not when you sent the SIGUSR1? i.e. get the stacktrace when you send it SIGINT after it's stuck.

But looks like the top of the stack is `poll()`, so it's might be in `xcb_poll_for_event()`.

**Comment by bricewge** [comment]
Ok, I think I got it this time: [gdb.txt](https://github.com/yshui/picom/files/4174522/gdb.txt), [picom.log](https://github.com/yshui/picom/files/4174524/picom.log).

**Comment by yshui** [comment]
oh no, this looks like a driver problem. I will investigate, but it's possible that we might have to take this to the upstream.

**Comment by bricewge** [comment]
Argh... That seems strange since #304 had the same issue but with a different driver: xf86-video-fbturbo-git 199.f9a6ed7-4. 
If it's really a issue from xf86-video-intel, I'm dammed, the reason in the first place that I'm using `picom` is because this driver can't be used without tearing.

**Comment by yshui** [comment]
@bricewge Can you try the latest `next`? I tried to make sure the GL context is really destroyed when picom resets, maybe that will fix the problem.

**Comment by bricewge** [comment]
Looks like we're good here.
I really wasn't expecting this issue to be fixed, thank you so much @yshui! (:
