### ISSUE TITLE
vsync_opengl_swc_init ERROR

### ISSUE THREAD

**Issue by VirajKanse** [yshui/picom#307]
### Platform
Arch Linux 86_64

### GPU, drivers, and screen setup
xf86-video-intel
mesa 19.3.2-2
glxinfo -B o/p : https://del.dog/ickanestow.txt

### Environment
i3-gaps

### picom version
7.5.2

### Configuration:
https://github.com/VirajKanse/dotfiles/blob/Dracula/.config/picom/picom.conf

### Steps of reproduction
1. open terminal & type 
2. `picom`

### Expected behavior
picom should to run as regular

### Current Behavior
` 01/28/2020 19:26:58.115 vsync_opengl_swc_init ERROR ] Failed to load a swap control extension.

[ 01/28/2020 19:26:58.116 session_init FATAL ERROR ] Failed to initialize the backend`

**Comment by sudharshanavp** [comment]
I have the same problem, picom doesn't run when using modesetting drivers with AccelMethod "none". My picom config is the same

It looks like xorg is loading the modesetting drivers for you. 

go to /etc/X11/xorg.conf.d and create a file called 20-intel.conf and add the following lines

```
Section "Device"
  Identifier "Intel Graphics"
  Driver "intel"
  Driver "AccelMethod" "uxa"
EndSection
```

**Comment by yshui** [comment]
You don't have your drivers properly installed, as you are not getting hardware accelerated opengl. Probably missing intel dri?
