### ISSUE TITLE
Firefox flicker when typing in rxvt

### ISSUE THREAD

**Issue by licaon-kter** [yshui/picom#308]
### Platform
Debian Sid 64bit x86_64

### GPU, drivers, and screen setup
nVidia GTX660Ti, 440.44

### Environment
i3

### picom version
HEAD

### Configuration:
Any

### Steps of reproduction
1. Have Firefox open
2. Open a transparent rxvt window and type

### Expected behavior
Nothing happens in Firefox

### Current Behavior
The Firefox page content flickers between all gray and content

### Other details

`git bisect` says
```
0e5be97f9456fcc6ed06699693b58dc4e61b9792 is the first bad commit
commit 0e5be97f9456fcc6ed06699693b58dc4e61b9792
Author: Yuxuan Shui <yshuiv7@gmail.com>
Date:   Sun Nov 10 18:58:01 2019 +0000

    core: watch for configuration file changes
    
    Automatically reset picom and reload the configuration when a change in
    the configuration file is detected.
    
    Signed-off-by: Yuxuan Shui <yshuiv7@gmail.com>

 src/common.h     |  2 ++
 src/file_watch.c | 97 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/file_watch.h | 10 ++++++
 src/meson.build  |  2 +-
 src/picom.c      | 15 +++++++++
 5 files changed, 125 insertions(+), 1 deletion(-)
 create mode 100644 src/file_watch.c
 create mode 100644 src/file_watch.h
``

**Comment by yshui** [comment]
Do you use `/dev/null` as config file? Is this fixed in the latest `next` branch?

**Comment by licaon-kter** [comment]
That was on text HEAD at that time, but appears fixed in next HEAD now, thanks. ;)
