### ISSUE TITLE
Move doc comments out of headers into source files

### ISSUE THREAD

**Issue by jransijn** [yshui/picom#313]
This is a bit personal preference, but I can personally understand a codebase much quicker by looking at header prototypes than by compiling and reading documentation, or reading documentation comments themselves. I prefer documentation comments in source files right before function definitions. It removes clutter in header files and also means the explanation of the code is right above the code itself, instead of in a different file.

Also, some documentation is duplicated right now (Take `win_is_fullscreen` as example).

**Comment by YoYoYonnY** [comment]
More personal preference, but I dislike `Doxygen` and prefer separate tools for doc-comment extraction and markup/cross-referencing.

**Comment by yshui** [comment]
doc comments should be in both the header and the source file.

We aren't using doxygen at the moment, it's a vestige.
