### ISSUE TITLE
OOB array access in experimental backend.

### ISSUE THREAD

**Issue by yyny** [yshui/picom#314]
I already fixed this in my local branch, but in case it doesn't go through:

`xd->alpha_pict[(int)(opacity * MAX_ALPHA)]` in the `blur` operation for the xrender back-end accesses the array out-of-bounds when `opacity < 0 || opacity > 1`.

This can happen when [`blur_opacity`](https://github.com/yshui/picom/blob/6a3d1354bed9d4c33227944a2331b0e5713668d3/src/backend/backend.c#L203) is changed.

The problem seems to be that `w->opacity` is divided by `win_calc_opacity_target(ps, w, true);` or `w->opacity_target`, while they are both <= 1.0, resulting in an increased value. Changing to a multiply fixes the problem and makes the transition look nicer too.

We probably wants tests for these kinds of regressions at some point, especially while we have 2 sets of back-ends to maintain.

**Comment by yshui** [comment]
If you have a fix, can you open a PR for it so I don't have to re-do what you have already done? 

Thanks!

**Comment by jransijn** [comment]
The fix is currently in a branch that moves around a bunch of code, but it shouldn't be that hard to merge it into the `next` branch. I'll see what I can do.

**Comment by yshui** [comment]
Reading through your PR, I realized there must be a deeper cause somewhere else.

If you want to investigate, I think you can remove the fix, but keep all the assertions, and see where the assertion is violated.
