### ISSUE TITLE
[Feature Request] Option to ignore blur on fully transparent windows

### ISSUE THREAD

**Issue by WillPower3309** [yshui/picom#316]
If picom were to have an option to not blur fully transparent window elements it allow it to present windows in the way that they were intended to be presented, while still allowing for a cool blur for partially transparent elements. Many applications have fully transparent elements intended to not appear to the user in order to shape the window (firefox menus, many game launchers, and any awesomewm widget with rounded corners are perfect examples of this). Currently picom blurs their fully transparent areas if blur is set to on. A great example of this having an undesired effect can be observed in many [awesomewm dotfiles](https://github.com/manilarome/Glorious-Dotfiles), where beautiful blurred windows have ugly blurred corners intended to not appear so as to give the window a shaped appearance. The current solution is to add the effected applications under the blur-exclude rules, but this can be annoying when dealing with windows that have elements that you want to blur, such as the aforementioned awesomewm widgets. Additionally, this presents the problem of having to constantly update the config whenever an application is downloaded that this effects.

**Comment by WillPower3309** [comment]
Here is a screenshot illustrating the issue:
![dirty](https://user-images.githubusercontent.com/13266308/74752444-acde8100-523c-11ea-815f-32a9d2738929.png)

Th effect can be observed at the corners of the bar at the bottom of the desktop

**Comment by WillPower3309** [comment]
Closing the issue as ive realized that there is a solution in awesomewm, can't blame picom for doing what its being told to

**Comment by ffs97** [comment]
@WillPower3309 I was facing the same issues. Could you let me know how'd you fix this in awesomewm? Thanks in advance

**Comment by WillPower3309** [comment]
> @WillPower3309 I was facing the same issues. Could you let me know how'd you fix this in awesomewm? Thanks in advance

For sure man! This is caused by how rounded corners are implemented in some awesomewm configs. Many users round the corners of a window inside a transparent window container without rounded corners, which allows for anti aliasing. The drawback is that compositors blur the transparent window container which is what gives the weird blurred corners. I just removed the containers in my setup, which is a branch off of my dotfiles that will soon be merged.

https://github.com/WillPower3309/awesome-dotfiles/tree/new_theme

**Comment by ffs97** [comment]
Oh got it got it. I am doing the same thing actually. I thought you had figured out how to have anti-aliased corners without the blurring from picom. Nonetheless, thanks :) Also, great setup you got there!

**Comment by WillPower3309** [comment]
> Oh got it got it. I am doing the same thing actually. I thought you had figured out how to have anti-aliased corners without the blurring from picom. Nonetheless, thanks :) Also, great setup you got there!
> 
> Edit: I see that you actually have solved the issue. I will go over your dotfiles. And gawd your setup is fiiiire. Will be stealing some things :P

Haha thanks man, appreciate it!
