### ISSUE TITLE
Opacity rule for net_wm_state_hidden no longer works

### ISSUE THREAD

**Issue by GorrillaRibs** [yshui/picom#317]
### Platform
Arch Linux (problem only appears in git master, repository package seems fine)

### GPU, drivers, and screen setup
Intel non-modesetting (integrated gpu), NVIDIA GTX 1050,  3840x2160 screen

### Environment
i3-gaps with xfce4-panel & other xfce bits

### picom version
latest git master

### Configuration:
```
backend = "glx";
#use-damage = true;
#resize-damage = 2;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
xrender-sync-fence = true;
vsync = true;
unredir-if-possible = true;
detect-transient = true;
detect-client-leader = true;
mark-wmwin-focused = true;
mark-ovredir-focused = true;
use-ewmh-active-win = true;
detect-rounded-corners = true;
detect-client-opacity = true;
shadow = true;
#shadow-radius = 10;
#shadow-offset-x = -8
#shadow-offset-y = -6;
#shadow-offset-x = 1;
#shadow-radius = 10;
#shadow-offset-x = -10;
#shadow-offset-y = -5;

log-level = "warn";
shadow-exclude = [
    "! name~=''",
    "! name = 'xfce4-panel'",
    "name = 'Notification'",
    "name = 'Plank'",
    "name = 'Docky'",
    "name = 'Kupfer'",
    "name = 'xfce4-notifyd'",
    "name *= 'compton'",
    "name *= 'picom'",
    "name *= '[i3-con]*'",
    "name *= '[i3 con] workspace *'",
    "name *= 'Ulauncher'",
#    "class_g *= 'i3-frame'",
#    "class_g = 'Firefox' && argb",
    "class_g = 'Conky'",
    "class_g = 'Plank'",
    "class_g = 'Kupfer'",
    "class_g = 'Synapse'",
    "class_g ?= 'Notify-osd'",
    "class_g ?= 'Cairo-dock'",
    "class_g ?= 'Xfce4-notifyd'",
    "class_g ?= 'Xfce4-power-manager'",
    "_GTK_FRAME_EXTENTS@:c",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];

# Fading
fading = true;
fade-delta = 3;
fade-in-step = 0.03;
fade-out-step = 0.03;
# no-fading-openclose = true;
# no-fading-destroyed-argb = true;
fade-exclude = [ ];
# Opacity
#inactive-opacity = 0.8;
# active-opacity = 0.8;
#frame-opacity = 0.7;
# inactive-opacity-override = true;
# inactive-dim = 0.2;
# inactive-dim-fixed = true;
#blur-background = true;
#blur-background-frame = true;
#blur-kern = "3x3box";
# blur-kern = "5,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1";
#blur-background-fixed = true;
blur-background-exclude = [
	"window_type = 'dock'",
	"window_type = 'desktop'",
	"_GTK_FRAME_EXTENTS@:c",
    "class_g = 'i3-frame'",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
    "name *= '[i3-con]'"
];
#opacity-rule = [ "65:class_g = 'i3-frame'" ];
opacity-rule = [ "0:_NET_WM_STATE@:32a*='_NET_WM_STATE_HIDDEN'" ];

```

### Steps of reproduction

1. Be running latest git master w/ i3wm (easiest to see here?)
2. Have this rule in config, which previously set hidden windows to opacity 0: opacity-rule = [ "0:_NET_WM_STATE@:32a*='_NET_WM_STATE_HIDDEN'" ];
3. Have a transparent window in the tabbed or stacking layout

### Expected behavior
Opacity rule applies, tabbed or stacked windows should be transparent when not shown

### Current Behavior
Rule fails, windows still displayed underneath other windows (i.e. transparent terminal displays browser window)

**Comment by yshui** [comment]
@GorrillaRibs Can you try the latest `next` and see if that fixes your problem.

**Comment by yshui** [comment]
For posterity: I think the problem is related to #266. Here, when user switches away from a window in i3, it becomes HIDDEN and loses focus _simultaneously_. The code handles focus updates the opacity_target _before_ the opacity rules are applied, therefore even if the opacity rules are applied later, the opacity_target is not changed to reflect it.

**Comment by yshui** [comment]
I cannot seem to reproduce this problem locally with i3-gaps. If this is still a problem, feel free to leave comment.

**Comment by GorrillaRibs** [comment]
Sorry for the late confirmation, but it is indeed fixed on my end too - thanks!

**Comment by mattiasJohnson** [comment]
This does not seem to work for me, I've just cloned the repo and I have the following config
```
opacity-rule = [ "80:class_g = 'URxvt'", "0:_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"  ];

inactive-dim = 0.08;
```

But when I stack terminals I see the underlying terminals instead of the background. I am running ubuntu 20.04 with a fresh version of i3-gaps-rounded https://www.github.com/jbenden/i3-gaps-rounded

**Comment by IDiamondcraft** [comment]
@mattiasJohnson I know it a bit late but you need to put your urxvt rules after _NET_WM_STATE. If you put it before, it will ignore your hidden state rules since urxvt rules is loaded before, it will have higher priority than _NET_WM_STATE. sorry if you know this already.

**Comment by mattiasJohnson** [comment]
Great thanks for the help that fixed it for me!
