### ISSUE TITLE
FPS hit in fullscreen games when two displays are connected

### ISSUE THREAD

**Issue by bno1** [yshui/picom#325]
I get a 10-15% FPS hit in Starcraft 2 (running via Wine and DXVK) when I have picom running and two displays connected. The game runs in fullscreen on one display and the other display has no application running on it, not even the XFCE panel.

If I stop picom OR disconnect/disable the second display while keeping picom running I don't see this decrease in performance.

My theory is that picom doesn't run the game in unredirected mode when there is a second display connected, but I can't find any documentation to determine if this is expected or not.

### Platform
OS: Arch linux
Computer: Lenovo Y700

### GPU, drivers, and screen setup
GPU: NVidia 960m
Driver: 440.59
Main display: Laptop screen, 1080p@60Hz
Secondary display: External monitor, 1440p@60Hz
The displays are configured side-by-side via the XFCE config tool.

### Environment
Desktop environment: XFCE with built-in compositor disabled

### picom version
v7.5

### Configuration:
```cfg
# Shadow
shadow = false;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
log-level = "warn";
# log-file = "/path/to/your/log/file";
# shadow-opacity = 0.7;
# shadow-red = 0.0;
# shadow-green = 0.0;
# shadow-blue = 0.0;
shadow-exclude = [
#       "name = 'Notification'",
#       "class_g = 'Conky'",
#       "class_g ?= 'Notify-osd'",
#       "class_g = 'Cairo-clock'",
#       "_GTK_FRAME_EXTENTS@:c"
];
# shadow-exclude = "n:e:Notification";
# shadow-exclude-reg = "x10+0+0";
# xinerama-shadow-crop = true;

# Opacity
inactive-opacity = 1;
# active-opacity = 0.8;
frame-opacity = 1;
inactive-opacity-override = false;
# inactive-dim = 0.2;
# inactive-dim-fixed = true;
blur-background = false;
blur-background-frame = false;
blur-kern = "3x3box";
# blur-kern = "5,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1";
blur-background-fixed = false;
blur-background-exclude = [
#       "window_type = 'dock'",
#       "window_type = 'desktop'",
#       "_GTK_FRAME_EXTENTS@:c"
];
# opacity-rule = [ "80:class_g = 'URxvt'" ];

# Fading
fading = false;
# fade-delta = 30;
fade-in-step = 0.03;
fade-out-step = 0.03;
# no-fading-openclose = true;
# no-fading-destroyed-argb = true;
fade-exclude = [ ];

# Other
backend = "glx";
mark-wmwin-focused = true;
mark-ovredir-focused = true;
# use-ewmh-active-win = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0;
vsync = false;
# sw-opti = true;
unredir-if-possible = true;
unredir-if-possible-delay = 0;
unredir-if-possible-exclude = [ ];
focus-exclude = [
#   "class_g = 'Cairo-clock'"
];
detect-transient = true;
detect-client-leader = true;
invert-color-include = [ ];
# resize-damage = 1;

# GLX backend
glx-no-stencil = true;
glx-no-rebind-pixmap = false;
xrender-sync-fence = true;
use-damage = true;

# Window type settings
wintypes:
{
#  tooltip = { fade = true; shadow = false; opacity = 0.75; focus = true; full-shadow = false; };
#  dock = { shadow = false; }
#  dnd = { shadow = false; }
#  popup_menu = { opacity = 0.8; }
#  dropdown_menu = { opacity = 0.8; }
};
```

### Steps of reproduction
Setup A:
1. Have two displays connected (laptop screen and external monitor in my case).
2. Start picom.
3. Start a full screen game on one display. Make sure there is nothing running on the other display.
4. Check the frame rate.

Setup B:
1. Have two displays connected.
2. Make sure that picom or any other compositor is NOT running.
3. Start a full screen game on one display. Make sure there is nothing running on the other display.
4. Check the frame rate.

Setup C:
1. Have one display connected (only laptop screen in my case).
2. Start picom.
3. Start a full screen game.
4. Check the frame rate.

### Expected behavior
I expect the game frame rate to be the same on all 3 setups.

### Current Behavior
When picom is running with two displays connected (setup A) there is a 10-15% FPS hit compared to setups B and C. Setups B and C don't exhibit any significant frame rate difference between them.

**Comment by aruhier** [comment]
It was fixed for me with that: https://github.com/yshui/picom/pull/187
But it doesn't work anymore (I don't know since when, I didn't do the bisect).

**Comment by bno1** [comment]
@aruhier I tried the `next` branch just now and I don't see any performance loss when using 2 displays, so I think it's working for me. Thanks for pointing this out!
