### ISSUE TITLE
Shadow does not respect opacity settings with experimental backends if window size is small enough

### ISSUE THREAD

**Issue by OliverLew** [yshui/picom#331]
**Update** Apr 2: See a few comments below for a more accurate description of this issue. In short, the opacity setting is violated when the window size goes under twice the shadow radius.

### Platform

Archlinux linux-lts
### GPU, drivers, and screen setup

AMD ATI Radeon Vega 8 (integrated)
local/mesa 19.3.4-2
local/xf86-video-amdgpu 19.1.0-1 (xorg-drivers)
local/xf86-video-vesa 2.4.0-2 (xorg-drivers xorg)
```
name of display: :1
display: :1  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD RAVEN (DRM 3.35.0, 5.4.22-1-lts, LLVM 9.0.1) (0x15dd)
    Version: 19.3.4
    Accelerated: yes
    Video memory: 1024MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 826 MB, largest block: 826 MB
    VBO free aux. memory - total: 3032 MB, largest block: 3032 MB
    Texture free memory - total: 826 MB, largest block: 826 MB
    Texture free aux. memory - total: 3032 MB, largest block: 3032 MB
    Renderbuffer free memory - total: 826 MB, largest block: 826 MB
    Renderbuffer free aux. memory - total: 3032 MB, largest block: 3032 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 1024 MB
    Total available memory: 4096 MB
    Currently available dedicated video memory: 826 MB
OpenGL vendor string: X.Org
OpenGL renderer string: AMD RAVEN (DRM 3.35.0, 5.4.22-1-lts, LLVM 9.0.1)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.3.4
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.3.4
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.3.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```
### Environment

AwesomeWM (git package)
### picom version

v7.5
```
**Version:** v7.5

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/oliver/.config/picom.conf

### Drivers (inaccurate):

AMDGPU, Radeon
```
### Configuration:
```
// This is a minimal one
shadow = true;
shadow-opacity = 0.1;
shadow-red = 1;
```

### Steps of reproduction

1. I moved away my own awesome config files and use the minimal picom config file above. I am using red shadow for better visibility.
2. Start picom with `picom --experimental-backends`

### Expected behavior
Any shadow would has 0.1 opacity, which is very faint. Starting picom without experimental backends behaves like this.
### Current Behavior
See the screenshot below. the dock(wibox), tooltip and menu has much more opaque shadows.

![](https://images2.imgbox.com/fe/6f/OuxTutrc_o.png)

**Comment by yshui** [comment]
Can you capture a trace of picom with `apitrace`?

**Comment by OliverLew** [comment]
@yshui Sorry I'm not really familiar with using these debug tools, I can't get `apitrace` working with picom. I ran `apitrace trace /usr/bin/picom [arguments]` and quit picom with Ctrl+C or `pkill`. Ctrl+C ends up with  core dump (I don't know which one it is, picom or apitrace) and `pkill` ends up with a really small trace file with 0 frames. 
However I can generate a trace file for mpv with no problem.
Am I quiting picom in a wrong way?

BTW, I also reproduced this with a almost vanilla (no personal configs) arch linux VM with the following command (with latest next branch HEAD)
```
picom --experimental-backends --config /dev/null -c -o 0.1 --shadow-red 1.0 --shadow-radius 32
```

**Comment by yshui** [comment]
@OliverLew Ah, I see, you are using the xrender backend. Does this same problem happen if you use the glx backend? If it does, you can get a trace from the glx backend, as apitrace works with opengl.

Sorry for not noticing that.

**Comment by OliverLew** [comment]
@yshui Silly me, I actually know apitrace is for opengl apps that's why I tested with mpv :) but I forgot the default backend is not glx.
This is my trace file [picom.trace.tar.gz](https://github.com/yshui/picom/files/4317219/picom.trace.tar.gz) with the following command. I opened the menu on top left corner and triggered the tooltip on the top right. It still ends with core dump though so not sure if the trace data is valid.
```
$ apitrace trace picom --experimental-backends --backend glx --config /dev/null -c -o 0.1 --shadow-red 1.0 --shadow-radius 32
apitrace: loaded into /usr/bin/apitrace
apitrace: unloaded from /usr/bin/apitrace
apitrace: loaded into /usr/bin/picom
apitrace: tracing to /home/oliver/Documents/trace/picom.trace
apitrace: attempting to read configuration file: /home/oliver/.config/apitrace/gltrace.conf
^Capitrace: unloaded from /usr/bin/picom
Segmentation fault (core dumped)
```

**Comment by OliverLew** [comment]
@yshui I found out something more accurate about the issue (and confirm it happens in both glx and xrender backends):
```
$ picom --config /dev/null --experimental-backends --backend xrender --shadow --shadow-opacity 0.1 --shadow-offset-x 50 --shadow-offset-y 50 --shadow-radius 100
```
![Peek 2020-04-02 23-31](https://user-images.githubusercontent.com/12032219/78268723-2c00ed80-753b-11ea-889b-c16307ebd388.gif)
It looks like the shadow opacity goes "wrong" if the window size <= twice shadow radius

**Comment by OliverLew** [comment]
@yshui Just pinging to say I still have this issue now (with latest git version). When you are available, could you check if you are able to reproduce what I had done in the previous comment?

**Comment by OliverLew** [comment]
It's fixed in v9.
