### ISSUE TITLE
Time uniform of glsl shaders

### ISSUE THREAD

**Issue by yshui** [yshui/picom#332]
It is implemented in #330 for old glx backend. Implement it for the new one as well.

**Comment by mighty9245** [comment]
wait, but first you need to implement custom window shaders for new glx backend :thinking:

**Comment by yshui** [comment]
@mighty9245 Yes, that's correct

**Comment by Asmageddon** [comment]
Seems like this issue has been forgotten about for 2y.

**Comment by yshui** [comment]
@Asmageddon it's already been implemented
