### ISSUE TITLE
Desaturation

### ISSUE THREAD

**Issue by kuba-orlik** [yshui/picom#335]
I use a grayscale filter on my android phone to keep it from being addictive. My eyes pretty much adjusted to it and now every "normal" screen seems like it has its saturation pushed to 200%. I've been looking for a way to decrease saturation on my desktop, as well. The only way I've found was to use Compiz and enable its "Opacity, Brightness and Saturation" plugin. I use it to desaturate windows to a varying degree, depending on the windows' titles (so a Firefox window that currently displays a social network is completely b/w, for example). But Compiz is quite buggy, so I set out to search for alternatives.

I am drawn to the lightweight nature of Picom and from what I gather it already has the capacity to influence window saturation when "dimming" an inactive window (please correct me if I'm wrong). I think it would be terrific if Picom had an option to desaturate some (or all windows) to a specified degree

### Platform

Manjaro Desktop

### Environment

Xfce

**Comment by yshui** [comment]
This can be easily achieved by using a shader.

For example:

```
picom --backend glx --glx-fshader-win \
"uniform sampler2D tex;
void main() {
    vec4 color = texture2D(tex, gl_TexCoord[0].xy);
    gl_FragColor = vec4(vec3(0.2126 * color.r + 0.7152 * color.g + 0.0722 * color.b), 1);
}"
```

**Comment by kuba-orlik** [comment]
That works, thanks!

**Comment by kuba-orlik** [comment]
I have trouble putting the shader in the `.conf` file. What's the correct way to do that?

**Comment by yshui** [comment]
@kuba-orlik See https://www.hyperrealm.com/libconfig/libconfig_manual.html#String-Values

**Comment by kuba-orlik** [comment]
I did set up the .conf file according to the libconf documentation:

```
vsync = true;
backend = "glx";
detect-rounded-corners = true;
detect-client-opacity = true;
use-damage=true;
fade-in-step=0.175
fade-out-step=0.1
glx-fshader-win="#version 130"
"// took inspiration from https://stackoverflow.com/questions/1395073/hlsl-pixel-shader-change-image-color-for-specific-hue"
""
"uniform sampler2D tex;"
"uniform float opacity;"
""
"uniform vec3 lumCoeff = vec3(0.2125, 0.7154, 0.0721);"
""
"vec4 Desaturate(vec4 color, float Desaturation)"
"{"
"    vec3 grayXfer = vec3(0.3, 0.59, 0.11);"
"    float grayf = dot(grayXfer, color.rgb);"
"    vec3 gray = vec3(grayf, grayf, grayf);"
"    return vec4(mix(color.rgb, gray, Desaturation), color.a * opacity);"
"}"
""
"void main()"
"{ "
"    vec4  cInput; "
"    cInput = texture2D(tex, gl_TexCoord[0].xy);"
""
"    vec4 inputColor = texture2D(tex, gl_TexCoord[0].xy);"
"    vec4 resultColor;"
"    resultColor = cInput;"
""
"    gl_FragColor = Desaturate(inputColor, 0.5);"
"}"
"";
```

But the shader isn't loaded and there's no warnings when starting picom. I think I'm missing something?

**Comment by yshui** [comment]
@kuba-orlik Ah, sorry, I made a bad assumption. `--glx-fshader-win` is actually only available as a command line option, not a config file one.

**Comment by mighty9245** [comment]
@yshui, we could change behavior of `--glx-fshader-win` to wait for path to a file containing shader instead of the shader itself and make it available through configuration file, i think this behavior is better than current.

**Comment by kuba-orlik** [comment]
That'd be very useful!

12 Mar 2020 21:47:27 mighty9245 <notifications@github.com>:

**Comment by rixx** [comment]
+1, if there was a way to pass this config in a less clumsy way, that would be very appreciated.
