### ISSUE TITLE
Grayscale filter shader not working with the experimental backend

### ISSUE THREAD

**Issue by jenav** [yshui/picom#337]
### Summary
The Grayscale filter from the [wiki](https://github.com/yshui/picom/wiki/Shader-Shop) is not working with the GLX experimental backends. Picom keeps running but windows don't go black and white. 
It does work if I use the old GLX backend.

### Platform
Debian 10 amd64

### GPU, drivers, and screen setup
Intel HD Graphics 530. 2 monitors side-by-side.
modesetting driver
xserver-xorg-core: 1.20.4

````
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2)  (0x1912)
    Version: 18.3.6
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.3.6
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 18.3.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
````

### Environment
wm: dwm

### picom version
latest git: 5d7ff71

### Configuration:
It doesn't seem to matter:

```
log-level = "trace";
backend = "glx";
```

### Steps of reproduction
1. Run picom with the old backend and watch the magic happen:
````
$ picom --config ~/.config/picom/picom.conf --glx-fshader-win "uniform sampler2D tex; uniform float opacity; void main() { vec4 color = texture2D(tex, gl_TexCoord[0].xy); gl_FragColor = vec4( vec3(0.2126 * color.r + 0.7152 * color.g + 0.0722 * color.b) * opacity, color.a * opacity); }"
````

2. Run picom with the new backend and stare at colors:
````
$ picom --experimental-backends --config ~/.config/picom/picom.conf --glx-fshader-win "uniform sampler2D tex; uniform float opacity; void main() { vec4 color = texture2D(tex, gl_TexCoord[0].xy); gl_FragColor = vec4( vec3(0.2126 * color.r + 0.7152 * color.g + 0.0722 * color.b) * opacity, color.a * opacity); }"
````

### Expected behavior
Windows go black and white.

### Current Behavior
Windows don't go black and white.

### Stack trace
[trace-new_glx_backend.log](https://github.com/yshui/picom/files/4330932/trace-new_glx_backend.log)
[trace-old_glx_backend.log](https://github.com/yshui/picom/files/4330933/trace-old_glx_backend.log)

**Comment by mighty9245** [comment]
`[ 03/13/2020 23:54:20.766 get_cfg WARN ] --glx-fshader-win is being deprecated, and might be removed in the future. If you really need this feature, please report an issue to let us know`

looks like `--glx-fshader-win` isn't implemented in experimental backends at all and there is only deprecation message stub

**Comment by mighty9245** [comment]
ok, i just build picom from the commit you linked and now nothing really happens. probably deprecation message was removed but feature wasn't implemented yet?

**Comment by yshui** [comment]
Yes, custom shaders are only supported in the old backends currently. There is plan to add it to the new ones.
