### ISSUE TITLE
[Feature Request] Selective Opacity

### ISSUE THREAD

**Issue by Aaahh** [yshui/picom#338]
### Environment
i3-gaps

It would be nice to have opacity selective, as in

full opacity:
![2](https://user-images.githubusercontent.com/3966556/76671036-7e697280-656a-11ea-9698-bddf7c067448.jpg)
90 opacity:
![3](https://user-images.githubusercontent.com/3966556/76671038-7f020900-656a-11ea-97d8-c7fc9624e793.jpg)

90 opacity on black:
![1](https://user-images.githubusercontent.com/3966556/76671060-993be700-656a-11ea-90e6-4b7852794c33.jpg)

it could be done as a contrast thing or just in general on pixels darker than the rest of the window. Just a thought

**Comment by Aaahh** [comment]
somewhat similar https://github.com/yshui/picom/issues/336

**Comment by mighty9245** [comment]
i guess it will be hard to implement this in a way it will work good. i mean no matter what algorithm or strategy you will use for this, sometimes (or often) you'll get a load of glitches and artifacts

**Comment by Aaahh** [comment]
I was thinking some kind of glgx filer but I also have no idea how windows
are drawn with pic ok

**Comment by yshui** [comment]
@Aaahh I am not sure what you are asking for? How is this opacity selective?

**Comment by Aaahh** [comment]
@yshui the images in the website are not make transparent like the rest of the window. What I want is similar to  https://github.com/yshui/picom/issues/295 so I guess I'll close this.

**Comment by yshui** [comment]
@Aaahh ah, do you want to have different opacity value for different windows? If so, you can have a look at `opacity-rules` and `active-opacity`/`inactive-opacity`. there is also a tool, `picom-trans`, which lets you set the opacity for each window manually.
