### ISSUE TITLE
frame opacity doesn't work with experimental xrender backend

### ISSUE THREAD

**Issue by mighty9245** [yshui/picom#342]
picom built from last commit
`picom --experimental-backends --backend xrender --frame-opacity 0.5`

frame changes it's color but there is no opacity
hmu if you can't reproduce this and need additional info on my setup

**Comment by yshui** [comment]
Cannot reproduce:

![a](https://user-images.githubusercontent.com/366851/76938148-02ff1c80-68ee-11ea-9114-c6329faaf7f8.png)

**Comment by mighty9245** [comment]
ok, i'll post additional info and screenshots when i'll be at home. could it be a driver issue since it's xrender, not glx?

**Comment by yshui** [comment]
@mighty9245 my screenshot is from xrender.

**Comment by mighty9245** [comment]
@yshui, hey, can you please test with opaque terminal? i mean you probably have terminal background opacity configured somewhere. what if you make terminal background opaque?

**Comment by yshui** [comment]
@mighty9245 
> what if you make terminal background opaque?

still works.

**Comment by mighty9245** [comment]
weird... well, that's what i have
![image](https://user-images.githubusercontent.com/52252283/76955295-f5b05500-6922-11ea-8824-16f83e30ea00.png)

you can see how the picom was launched and the results: two instances of kitty have background_opacity set to 1.0 (which means opaque background) and the third one has background_opacity set to 0.95 (which means barely transparent) but in this case frame opacity applied correctly and i can see background through it. the same for issue persists for all opaque windows (e. g. browser)

specs:
arch linux x86_64 5.5.9-arch1-2
picom built from 33a5cc604fb1dcca0abcad7c6b308973021440a2
modesetting driver
intel uhd graphics 620

do you need anything else?

**Comment by yshui** [comment]
@mighty9245 and the glx background doesn't have this problem?

**Comment by mighty9245** [comment]
@yshui, yeah, running the same command but setting backed to glx works just fine, every window got it's transparent frame.

**Comment by mighty9245** [comment]
@yshui, hey, looks like i found the root cause. if window doesn't have any transparent parts it has 24bit depth, adding transparent parts to it (e. g. changing background opacity in terminal) changes it's depth to 32bit. as a workaround i changed xrender's copy method to set visual to 0x1b3 and depth to 32 for every window and the issue is gone. however, i don't know how to fix this in a decent way. 

also idk if problem is really in depth or in visual, because changing depth without changing visual causes picture creation failure. i think they are tied.

**Comment by yshui** [comment]
I think you are right.
