### ISSUE TITLE
blur-background-frame has no effect

### ISSUE THREAD

**Issue by Sorixelle** [yshui/picom#345]
### Platform
NixOS

### GPU, drivers, and screen setup
AMD RX 5700, xf86-video-amdgpu 19.0.1, single 1920x1080@60hz monitor
Output of `glxinfo -B`:
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD NAVI10 (DRM 3.36.0, 5.5.9, LLVM 9.0.1) (0x731f)
    Version: 19.3.3
    Accelerated: yes
    Video memory: 8192MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 7828 MB, largest block: 7828 MB
    VBO free aux. memory - total: 8093 MB, largest block: 8093 MB
    Texture free memory - total: 7828 MB, largest block: 7828 MB
    Texture free aux. memory - total: 8093 MB, largest block: 8093 MB
    Renderbuffer free memory - total: 7828 MB, largest block: 7828 MB
    Renderbuffer free aux. memory - total: 8093 MB, largest block: 8093 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8192 MB
    Total available memory: 16368 MB
    Currently available dedicated video memory: 7828 MB
OpenGL vendor string: X.Org
OpenGL renderer string: AMD NAVI10 (DRM 3.36.0, 5.5.9, LLVM 9.0.1)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.3.3
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.3.3
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.3.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment
Using awesomewm

### picom version
**Version:** v7

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No (Another compositor is already running)
* Config file used: None

### Drivers (inaccurate):

AMDGPU, Radeon 

### Configuration:
```
# fading
fading = true;
fade-delta    = 5;
fade-in-step  = 0.028;
fade-out-step = 0.03;
fade-exclude  = [];

# blur
blur-background         = true;
blur-background-exclude = [];

# opacity
active-opacity   = 1.0;
inactive-opacity = 1.0;
inactive-dim     = 0.0;
opacity-rule     = [];

wintypes:
{
  dock          = { shadow = false; };
  dnd           = { shadow = false; };
  popup_menu    = { opacity = 1.0; };
  dropdown_menu = { opacity = 1.0; };
};

# other options
backend = "glx";
vsync = true;
refresh-rate = 0;
blur:
{
  method = "gaussian";
  size = 20;
  deviation = 7.5;
};
blur-background-frame = true;

glx-no-stencil = true;
glx-no-rebind-pixmap = true;
```

### Steps of reproduction
1. Enable `blur-background-frame` in the config.
2. Start picom, and open a fully opaque window with a transparent titlebar.

### Expected behavior
The background of the titlebar should be blurred.

### Current Behavior
The background of the titlebar is not blurred.

### Other details
As an example, in this image, the window on the left (kitty) has a transparent background, and it's titlebar is blurred. The window on the right (firefox) has a fully opaque window, but it's transparent titlebar is not blurred.

![Image](https://i.imgur.com/JnEgHQe.png)

If I understand the manpage correctly, the `blur-background-frame` option is supposed to cause firefox's titlebar to be blurred, despite firefox being fully opaque, but this doesn't seem to be happening.

**Comment by yshui** [comment]
Can you try the latest `next` branch? I have recently fixed a similar problem, which might have fixed this as well.

**Comment by Sorixelle** [comment]
Issue still seems to exist on latest commit at time of writing (`0fa0c352307f1a34f261419ce4a2f2a45a9ba85d`).

**Comment by manilarome** [comment]
I'm also having this issue. Glad I found a workaround. I add an opacity rule for the window_types so picom can apply the blur.

```
	"99:window_type = 'normal'",		# Add a tiny bit of opacity to all normal windows to apply blur
	"99:window_type = 'dialog'",		# Add a tiny bit of opacity to all dialog windows to apply blur
	"99:window_type = 'popup_menu'",	# Add a tiny bit of opacity to all popup_menu windows to apply blur
	"99:window_type = 'notification'"	# Add a tiny bit of opacity to all popup_menu windows to apply blur
```

**Comment by mighty9245** [comment]
what if you set `frame-opacity` to a value less than 1, e. g. 0.5?

**Comment by manilarome** [comment]
> what if you set frame-opacity to a value less than 1, e. g. 0.5?

So I commented this `"99:window_type = 'normal'",` in my opacity rule and set `frame-opacity = 0.5;` The blur works.

**Comment by mighty9245** [comment]
but i have other problem - frame of transparent window (e. g. terminal with transparent background set in terminal's config` is blurred when blur-background-frame is not enabled :thinking:

need to investigate on this a little

**Comment by Sorixelle** [comment]
Setting `frame-opacity` to a value less than 1 does cause the titlebar to be blurred, but also (obviously) reduces the overall opacity of the titlebar, which isn't what I want.

@mighty9245 It is a wm trick, awesomewm allows full control over basically every aspect of the window manager, background colour (and, hence, transparency) of titlebars included. I've created a "minimal" (ie. barely modified default) config for awesomewm [here](https://gist.github.com/Sorixelle/e006b0e52851850391df396f5bfd5662) that gives transparent titlebars. Place the two files in `~/.config/awesome`, and change `<USER>` on line 51 of `rc.lua` to be your username. This should give you an awesomewm instance with transparent titlebars. [This page](https://awesomewm.org/apidoc/documentation/07-my-first-awesome.md.html) should detail enough of the controls tdo get you going.

**Comment by manilarome** [comment]
@Sorixelle set it to `0.99`, then. That 0.01 transparency is unnoticeable. 

![image](https://user-images.githubusercontent.com/40349590/77248768-edd01800-6c76-11ea-80af-285dae9cb091.png)

**Comment by mighty9245** [comment]
i guess picom incorrectly determines window mode? @yshui

kitty with opaque background with awesomewm's transparent frame
```
[ 03/22/2020 16:04:07.904 paint_all_new INFO ] Window 0x0060000e((null)): trans
[ 03/22/2020 16:04:07.904 paint_all_new INFO ] 0x0060000e: blurring bg
```

kitty with transparent background with awesomewm's transparent frame
```
[ 03/22/2020 16:04:07.904 paint_all_new INFO ] Window 0x0080000e((null)): frame_trans
[ 03/22/2020 16:04:07.904 paint_all_new INFO ] 0x0080000e: blurring frame
```

**Comment by mighty9245** [comment]
investigated on this a litte: blurring routine is the same no matter frame_opacity value, but extra routine when frame_opacity is set to a value less than 1 makes blur to be visible/to render :thinking:

**Comment by yshui** [comment]
@Sorixelle @manilarome Should have been fixed in `next`.

**Comment by Sorixelle** [comment]
Yep, that fixed it. Thanks!

**Comment by manilarome** [comment]
Thanks!
