### ISSUE TITLE
Can no longer match _NET_WM_STATE_FULLSCREEN on _NET_WM_STATE

### ISSUE THREAD

**Issue by sam-lunt** [yshui/picom#350]
I had used an entry in `focus-exclude` to detect when `_NET_WM_STATE_FULLSCREEN` was part of `_NET_WM_STATE`, which allowed videos to played in full-screen without becoming opaque. At some point, this stopped working.

### Platform
Arch Linux 5.5.10-arch1-1 amd64

### GPU, drivers, and screen setup
AMD RX 590, admgpu from mesa 19.3.4-2, two monitors configured side-by-side
xf86-video-amdgpu 19.1.0-1
xf86-video-vesa 2.4.0-2

```
$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: Radeon RX 590 Series (POLARIS10, DRM 3.36.0, 5.5.10-arch1-1, LLVM 9.0.1) (0x67df)
    Version: 19.3.4
    Accelerated: yes
    Video memory: 8192MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 7993 MB, largest block: 7993 MB
    VBO free aux. memory - total: 8116 MB, largest block: 8116 MB
    Texture free memory - total: 7993 MB, largest block: 7993 MB
    Texture free aux. memory - total: 8116 MB, largest block: 8116 MB
    Renderbuffer free memory - total: 7993 MB, largest block: 7993 MB
    Renderbuffer free aux. memory - total: 8116 MB, largest block: 8116 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8192 MB
    Total available memory: 16384 MB
    Currently available dedicated video memory: 7993 MB
OpenGL vendor string: X.Org
OpenGL renderer string: Radeon RX 590 Series (POLARIS10, DRM 3.36.0, 5.5.10-arch1-1, LLVM 9.0.1)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.3.4
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.3.4
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.3.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment
bspwm 0.9.9-1

### picom version
```
$ picom --version
v7.5

$ picom --diagnostics                                                                                                                                                                   <<<
**Version:** v7.5

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/sam/.config/picom.conf

### Drivers (inaccurate):

AMDGPU, Radeon
```

### Configuration:
```
backend = "glx";
glx-no-stencil = true

shadow = false

active-opacity = 1;
inactive-opacity = 0.7;
frame-opacity = 0.8;

inactive-dim = 0.5;

opacity-rule = [
    "90:class_g = 'kitty' && focused",
    "60:class_g = 'kitty' && !focused",
];

focus-exclude = [
    "_NET_WM_NAME@:s = 'rofi'",
    "name = 'i3lock'",
    "_NET_WM_STATE@:a *= '_NET_WM_STATE_FULLSCREEN'",
    "MY_ALWAYS_FOCUS@:s = 'on'"
];

inactive-opacity-override = false;
inactive-dim-fixed = false;

blur-background = true;
blur-background-fixed = false;

blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'"
];

use-ewmh-active-win = true;

mark-wmwin-focused = true;
mark-ovredir-focused = false;

detect-client-opacity = false;

unredir-if-possible = false;

fading = true;
fade-delta = 5;
fade-exclude = [ ];

wintypes:
{
    utility = { focus = true; } # needed for Firefox search suggestions
    dropdown_menu = { opacity = 1; }
    popup_menu = { opacity = 1; }
};
```

### Steps of reproduction
1. Maximize a video
2. Focus on a window on the other monitor

### Expected behavior
The video maintains the same level as transparency (i.e. fully opaque) as when it was focused.

### Current Behavior
The video becomes the level of transparency as other inactive windows.

**Comment by mighty9245** [comment]
recently there was a commit that *should* fix *similiar* issue. could you please try to build picom from latest commit and see if issue is still here?

**Comment by sam-lunt** [comment]
Thanks for the quick reply.

I tried using the [picom-git](https://aur.archlinux.org/packages/picom-git/) package from the AUR, which builds the `next` branch (most recent commit 2523829f4c3281cfdc8629ca7a7cf9298bc3090a from earlier today). The behavior is the same, however.

Do you think it could be a change to the way that _NET_WM_STATE is matched? The other `focus-exclude` entries work. For example, I addded the `MY_ALWAYS_FOCUS` property and if I set that with `xprop -f MY_ALWAYS_FOCUS 8s -set MY_ALWAYS_FOCUS on`, it correctly excludes it from the focus rules.

**Comment by mighty9245** [comment]
what if you change your rule a little to `"_NET_WM_STATE@:32a *= '_NET_WM_STATE_FULLSCREEN'"`

unfortunately i don't have a second monitor to test your scenario

**Comment by sam-lunt** [comment]
I had originally had it like that, but I also tried `"_NET_WM_STATE@:16a *= '_NET_WM_STATE_FULLSCREEN'"` and `"_NET_WM_STATE@:8a *= '_NET_WM_STATE_FULLSCREEN'"`. Both of those options caused a warning to be printed, while `32` didn't, so I assumed that the `32` was redundant.

Anyway, I'm now having trouble reproducing it. The original config works with both `picom` and `picom-git`. Removing the `"_NET_WM_STATE@:a *= '_NET_WM_STATE_FULLSCREEN'"` line causes it to behave as before, and putting it back fixes it. I'll close this for now and see if it happens again. Thanks for the help.
