### ISSUE TITLE
Artifacts when blur-background-frame is enabled on old backends

### ISSUE THREAD

**Issue by yshui** [yshui/picom#352]
Moving windows in this setup leaves a trail is the frame region. Only happens to non-transparent windows.

Example of this problem:

https://imgur.com/MVKp41q

**Comment by mighty9245** [comment]
should we even care about old backends?

**Comment by yshui** [comment]
Depends on how complex is the fix.

**Comment by absolutelynothelix** [comment]
closing as stale.
