### ISSUE TITLE
Is there a way to disable fading when switching workspace?

### ISSUE THREAD

**Issue by vtdmhd** [yshui/picom#354]
This is a duplicate of https://github.com/chjj/compton/issues/314

--no-fading-openclose still doesn't prevent the fading during desktop switching

**Comment by yshui** [comment]
Not possible.

Switching desktop is basically your window manager hiding all the windows from one desktop and showing you windows from another. No window is being opened or closed, so of course `--no-fading-openclose` won't affect this.

And there is no way to distinguish between switching desktops and "normal" window hiding.

**Comment by jypma** [comment]
Just wanted to add, from the linked issue, that the following indeed disables fading entirely (including when switching workspaces):
```
--fade-in-step=1 --fade-out-step=1 --fade-delta=0
```

**Comment by davidpeach** [comment]
> Just wanted to add, from the linked issue, that the following indeed disables fading entirely (including when switching workspaces):
> 
> ```
> --fade-in-step=1 --fade-out-step=1 --fade-delta=0
> ```

Thank You.
Worked for me:

```
picom --fade-in-step=1 --fade-out-step=1 --fade-delta=0
```

**Comment by ardishco-the-great** [comment]
> Just wanted to add, from the linked issue, that the following indeed disables fading entirely (including when switching workspaces):

--fade-in-step=1 --fade-out-step=1 --fade-delta=0

this quite literally disabled my compositor.

**Comment by eclairevoyant** [comment]
> > --fade-in-step=1 --fade-out-step=1 --fade-delta=0
> 
> this quite literally disabled my compositor.

I just tested it from my end, it disables the fadein effect but transparency is still present. Honestly if that disables your compositor, you should reproduce it and check logs and possibly report it as a new bug if applicable.
