### ISSUE TITLE
Wrong shadow-exclude names

### ISSUE THREAD

**Issue by ghost** [yshui/picom#355]
Picom did not exclude the shadows on Plank and Conky. So I opened up **picom.conf** and changed **Conky** to **conky** (lowercase) as well as **Plank** to **plank** (also lowercase). 

After restarting picom everything works as expected.

I'm on newest Arch + XFCE4.

**Comment by yshui** [comment]
Can you paste your config file?

**Comment by yshui** [comment]
no response
