### ISSUE TITLE
Cursor movement not rendered at monitors refresh rate when it's greater than 60hz on glx renderer

### ISSUE THREAD

**Issue by Hatsor** [yshui/picom#367]
### Platform
Arch Linux 5.5.13-zen

### GPU, drivers, and screen setup
    AMD Vega64, single Dell 1440p 155hz monitor configured with xrandr on i3 launch
    Mesa 20.0.2
    xf86-video-amdgpu 19.1.0-1 
    name of display: :0
    display: :0  screen: 0
    direct rendering: Yes
    Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: Radeon RX Vega (VEGA10, DRM 3.36.0, 5.5.13-zen1-1-zen, LLVM 9.0.1) (0x687f)
    Version: 20.0.2
    Accelerated: yes
    Video memory: 8192MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
    Memory info (GL_ATI_meminfo):
    VBO free memory - total: 7181 MB, largest block: 7181 MB
    VBO free aux. memory - total: 8026 MB, largest block: 8026 MB
    Texture free memory - total: 7181 MB, largest block: 7181 MB
    Texture free aux. memory - total: 8026 MB, largest block: 8026 MB
    Renderbuffer free memory - total: 7181 MB, largest block: 7181 MB
    Renderbuffer free aux. memory - total: 8026 MB, largest block: 8026 MB
    Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8192 MB
    Total available memory: 16368 MB
    Currently available dedicated video memory: 7181 MB
    OpenGL vendor string: X.Org
    OpenGL renderer string: Radeon RX Vega (VEGA10, DRM 3.36.0, 5.5.13-zen1-1-zen, LLVM 9.0.1)
    OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.0.2
    OpenGL core profile shading language version string: 4.60
    OpenGL core profile context flags: (none)
    OpenGL core profile profile mask: core profile

    OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.0.2
    OpenGL shading language version string: 4.60
    OpenGL context flags: (none)
    OpenGL profile mask: compatibility profile

    OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.0.2
    OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

### Environment
i3-gaps with polybar

### picom version
**Version:** v7.5

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/hatsor/.config/picom.conf

### Drivers (inaccurate):

AMDGPU, Radeon`

### Configuration:
Default configuration, only changed renderer to glx

### Steps of reproduction
1. Install picom
2. Copy default configuration
3. Change renderer to glx

### Expected behavior
Cursor refreshes at monitor refresh rate like with xrender

### Current Behavior
Cursor seems to be stuck on 60hz. Games, videos and even Brave browser seem to me refreshing at the appropriate rate

**Comment by Ropid** [comment]
Are you using variable refresh on your monitor (FreeSync)? I remember when the program's name changed from "compton" to "picom", I had a problem because of FreeSync. That might be what you are seeing.

The "mesa" package ships with a "drirc" config entry for compton that makes sure that the driver ignores variable-refresh for compton. But there's no entry for the new name "picom". I needed to create an entry myself. I've added it to my user's `~/.drirc` file, like this:

```
<driconf>
    <device>

        <!-- Adaptive sync blacklist follows below: -->
        <application name="picom" executable="picom">
            <option name="adaptive_sync" value="false" />
        </application>
        
    </device>
</driconf>
```

Mesa's main file is in `/usr/share/drirc.d/00-mesa-defaults.conf` if you want to take a look at what's going on in there. If you search for `adaptive_sync`, you'll see there's entries there for many different compositors and other programs.

**Comment by Hatsor** [comment]
I was indeed using variable refresh rate on my monitor. Upon adding the config file like you provided and rebooting my machine, the problem went away and it was now fixed.
Many thanks, for the tip, this might prove useful in the future too for some other applications.
