### ISSUE TITLE
Discussion of technical config settings

### ISSUE THREAD

**Issue by aufkrawall** [yshui/picom#37]
At first: Thanks a lot for maintaining Compton, yshui. I don't know what I would do without it with free drivers and an Xorg session.

`glx-no-rebind-pixmap` It doesn't do any harm for me with proprietary Nvidia drivers and Mesa (RadeonSI). It doesn't increase performance in my benchmarks either. Perhaps it's only measurable with really slow GPUs? Safe to activate it by default, though?

`vsync` My opinion would be to make `opengl` the default setting since it shows lower input latency than the other modes with Mesa drivers (apart from DRM, which is currently not activated by default when compiling). Sometimes people tend to force other vsync modes on top of compositing (like that forcecompositionpipeline mess with Nvidia), but I don't see why an application shouldn't care for vsync on its own, assuming driver bugs aren't normal. And it's plausible to assume that a compositor should enable vsync by default.

`glx-swap-method`I notice that setting it to `buffer-age` helps my GPU driver to stick to lower clocks to save power, contrary to any other possible value. I've also never encountered any problem with it and also other compositors use it by default. I always wonder why so many people don't have it in their configs. Perhaps because its description is a bit misleading?

`paint-on-overlay` Is said to help against flickering with `unredir-if-possible` and doesn't seem to cause any issues?

`unredir-if-possible` Gnome-Mutter automatically turns off compositing for fullscreen windows for best performance. However, it also offers applications to block turning off compositing in fullscreen, which Compton does not. If it's enabled by default, I think it would be a good idea to also exclude at least browsers by default too via `unredir-if-possible-exclude` to maintain transparency features etc.

**Comment by yshui** [comment]
First, thank you for sharing this information, it is very useful.

> vsync

Problem is `opengl` does not seem to work for everyone, especially for those using the xrender backend. I agree we want vsync by default, but that would require some work.

> glx-swap-method

Yes, `buffer-age` is the best option here. But some users have encountered problem with `buffer-age` before. I want to put in some kind of blacklisting based on hardware and driver versions, before enabling `buffer-age` by default.

> paint-on-overlay

Yes, this should be on by default, if supported.

> unredir-if-possible

It is said to cause some flickering, so I'm not sure.

> [GNOME] also offers applications to block turning off compositing in fullscreen

I'm curious, how does applications block unredirecting?

> to maintain transparency features etc.

When a transparent window is visible, `unredir-if-possible` shouldn't be triggered.

**Comment by jrudess** [comment]
One of the reasons I don't use `glx-swap-method=buffer-age` is that it doubles CPU utilization on my system compared to `glx-swap-method=1`

This slowdown only happens for me with compton underneath virtualbox, and not on my native-desktop with nvidia (gtx980).

**Comment by yshui** [comment]
@jrudess Yes, that is why I was talking about adding some kind of blacklisting functionality. Honestly, the vboxvideo driver is probably not one of the best video drivers.

**Comment by aufkrawall** [comment]
Could it be that the latest changes have fixed the flicker of `unredir-if-possible`?

**Comment by yshui** [comment]
@aufkrawall I don't think so? Why?

Maybe the latest changes might have just broken `unredir-if-possible` entirely.

**Comment by aufkrawall** [comment]
It still nicely disables compositing. Anyhow, for some reason I can't reproduce the "missing" flickering anyway. Really weird, I was absolutely certain.

But: I think the "old" Compton didn't re-enable compositing when on top of a fullscreen window something transparent is rendered. E.g. the volume overlay when pressing my media keyboard buttons wasn't treated as transparent and thus there was no flicker. Would it be possible to restore that behavior, or is that not related to Compton and might be due to a change in KDE Plasma?

**Comment by yshui** [comment]
Hmm, I think that need to be configurable. Can you open a new issue for that?

**Comment by aufkrawall** [comment]
Sure.

**Comment by aufkrawall** [comment]
@yshui Could you please reconsider automatically activating `--vsync-use-glfinish` when `GLX_MESA_swap_control` is used for v6? I don't think we have any evidence that it can cause harm with Mesa drivers, it only reduces input latency.

**Comment by yshui** [comment]
closing as this is a dicussion not an issue, and most of the config options discussed has since changed and become irrelevant.
