### ISSUE TITLE
possible mem leak

### ISSUE THREAD

**Issue by MerrinX** [yshui/picom#372]
#360 # Platform
Arch Qtile WM

### GPU, drivers, and screen setup
Nvidia 1080, 3 monitors side by side, one is tilted on the side.
    Please include the version of the video drivers (xf86-video-*) and mesa.
    Please also paste the output of `glxinfo -B` here.
 --> Nvidia 440.64
Not running Mesa drivers

### Environment

picom ver 7.5

### Configuration:
```
# Performance related
backend = "glx";

glx-no-stencil = false;
glx-copy-from-front = false; # When enbled on intel GPU: screen broken until compton is killed.
glx-swap-method = 1

unredir-if-possible = true

# === Rules ===
shadow-exclude = [ 
    "class_g ?= 'Visualizer'",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
    "window_type *= 'menu'",
    "window_type = 'utility'",
    "window_type = 'dock'",
    "window_type = 'dropdown_menu'",
    "window_type = 'popup_menu'"
]

opacity-rule = []

focus-exclude = [
    "class_g ?= 'Steam'",
    "class_g ?= 'Discord'",
    "_NET_WM_WINDOW_TYPE@:a *= 'MENU'",
    "window_type *= 'menu'",
    "window_type = 'utility'",
    "window_type = 'dropdown_menu'",
    "window_type = 'popup_menu'"
]

fade-exclude = []

# === Shadows ===
shadow = false;
no-dnd-shadow = true;
no-dock-shadow = false;
clear-shadow = false;
detect-rounded-corners = false;

shadow-radius = 14;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.3;

fading = true;
fade-delta = 10;
no-fading-openclose = false
```

### Expected behavior
To run flawless
### Current Behavior
Gets hung up after a while, need to restart application to free mem, it seems, not physical memory, only gpu. also have small graphic glitches on the screen, that is annoying.

**Comment by mighty9245** [comment]
glxinfo provides some information about video memory, i guess you can see if you really run out of video memory after running picom for a while with `glxinfo | grep memory`

**Comment by MerrinX** [comment]
I can install it and see, but i do not think i need to, My ram is fine, after a while i need to close firefox and reopen, then everything works.
My laptop runs the same apps, config, but no nvidia graphic card. can there be something in my picom.conf?

**Comment by yshui** [comment]
As you are using NVIDIA, you can check GPU memory usage with `nvidia-smi`

**Comment by yshui** [comment]
Or https://github.com/Syllo/nvtop

**Comment by MerrinX** [comment]
To my suprize, when i try to run, it say Driver not loaded... had to install the dkm package from Arch, my bad.. Now everything is fine, I will close this.
