### ISSUE TITLE
Duplicated frame and popup window and window frames in Chrome, VSCode

### ISSUE THREAD

**Issue by melangue** [yshui/picom#378]
### Platform
Ubuntu Desktop 19.10 amd64

### GPU, drivers, and screen setup
AMD Vega M, Three 1920x1080 monitors side by side.

Xrandr command:
```
xrandr --output DisplayPort-1 --auto --output HDMI-A-1 --left-of DisplayPort-1 --output DisplayPort-2 --right-of DisplayPort-1
```

`glxinfo -B` output:

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD VEGAM (DRM 3.33.0, 5.3.0-46-generic, LLVM 9.0.0) (0x694e)
    Version: 19.2.8
    Accelerated: yes
    Video memory: 4096MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 3538 MB, largest block: 3538 MB
    VBO free aux. memory - total: 3932 MB, largest block: 3932 MB
    Texture free memory - total: 3538 MB, largest block: 3538 MB
    Texture free aux. memory - total: 3932 MB, largest block: 3932 MB
    Renderbuffer free memory - total: 3538 MB, largest block: 3538 MB
    Renderbuffer free aux. memory - total: 3932 MB, largest block: 3932 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 4096 MB
    Total available memory: 8192 MB
    Currently available dedicated video memory: 3538 MB
OpenGL vendor string: X.Org
OpenGL renderer string: AMD VEGAM (DRM 3.33.0, 5.3.0-46-generic, LLVM 9.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.2.8
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.2.8
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment
BSPWM

### picom version
Picom version
vgit-bdf80

### Configuration:
```
unredir-if-possible = false;
backend = "glx";
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
vsync = true;
```

### Steps of reproduction
1. Open VSCode/Chrome
2. Right click anywhere which popups a selection window

### Expected behavior
App window and popup windows work as expected - i.e. they are not duplicated.

### Current Behavior
Main app window is duplicated and shown in the top left corner of the first monitor, along with the popup menu. Both the duplicated app window and the popup window are not interactive. They disappear when I kill picom.

It seems to not be connected with using bspwm as the window manager - same things is happening both in Awesome and herbsluftwm.

The duplicated app window/popup window does not disappear when the app/menu is closed, it persists on screen above every other window.

### Stack trace
No ouput from picom when right clicking or drawing the window.

### Other details
Here is a screenshot:
![image](https://user-images.githubusercontent.com/14099001/79122622-75053d00-7d98-11ea-8931-6264107aa14b.png)

Here is a video showing the issue:
https://imgur.com/a/hkYh0a3

If you need additional information - please let me know, I will be happy to provide anything you need.

**Comment by yshui** [comment]
Can you get a trace of picom? https://github.com/yshui/picom/wiki/Reporting-issues#capture-a-trace

**Comment by melangue** [comment]
I have sent it via an e-mail as I can't seem to be able to add this file type to a github comment.

**Comment by yshui** [comment]
@melangue you can zip the file first.

**Comment by melangue** [comment]
True, my bad. Here it is zipped.
[picom.1.zip](https://github.com/yshui/picom/files/4474679/picom.1.zip)

**Comment by melangue** [comment]
Got any news on this?

**Comment by melangue** [comment]
Today I have rebuilt picom from source and the issue seems to be completely gone now.  
Not sure if you have fixed or did any recent updates to VSCode did but it seems to be working so I am closing this issue.
