### ISSUE TITLE
Draw shadow under the entire window

### ISSUE THREAD

**Issue by GOKOP** [yshui/picom#383]
With compton I used shadow to get smoothly edged dimmed background under conky windows (so that they're readable on all my wallpapers) and also to have shadow under my polybar which has transparent border. This worked because compton painted shadow under the entire window, but with picom they're only painted where the window ends, so it looks very bad with transparent windows.

Is there a way to get old compton behavior back?

This is my config: https://pastebin.com/BK7vsLdh

I use NVIDIA GTX 960 with propertariary driver version 440.82 on Artix Linux (basically Arch without systemd) with bspwm but I don't think that's relevant

**Comment by mighty9245** [comment]
look for `full-shadow` in the manual

**Comment by GOKOP** [comment]
Thanks!
