### ISSUE TITLE
inactive-dim doesn't work

### ISSUE THREAD

**Issue by GOKOP** [yshui/picom#384]
### Platform
Artix Linux (Arch without systemd)

### GPU, drivers, and screen setup
NVidia GTX 960, propertariary driver 440.82

### Environment
bspwm

### picom version
7.5

### Configuration:
https://pastebin.com/SfANcZgf

### Steps of reproduction

1. Set inactive-dim to a non-zero value
2. Run picom

### Expected behavior
Inactive windows are dimmed
### Current Behavior
Inactive windows aren't dimmed

### Other details
It happens both with and without experimental backends disabled

**Comment by mighty9245** [comment]
set `mark-ovredir-focused` to false

**Comment by GOKOP** [comment]
Works, thank you!

**Comment by AeliusSaionji** [comment]
@mighty9245 is this not a bug?
If you `focus exclude override redirect`, which I believe is meant to do the exact same thing, inactive dim still works and you still get the desired effect of marking ovredirect windows focused.
