### ISSUE TITLE
Experimental backends feature parity

### ISSUE THREAD

**Issue by yshui** [yshui/picom#385]
Right now I think most of the old backend features have been implemented in the new ones. This issue is used to track what's left.

Feel free to shout if I missed anything.

|Feature | xrender | glx |
|-----------|:----------:|:----:|
|Opacity (including active/inactive opacity) | :heavy_check_mark:  | :heavy_check_mark: |
|Frame opacity| :heavy_check_mark:  | :heavy_check_mark: |
|Dimming| :heavy_check_mark:  | :heavy_check_mark: |
|Shadow| :heavy_check_mark:  | :heavy_check_mark: |
|Blur| :heavy_check_mark:  | :heavy_check_mark: |
|Vsync| :heavy_check_mark:  | :heavy_check_mark: |
|Custom Shader| :no_entry_sign:  | #386  |

**Comment by absolutelynothelix** [comment]
closing as done.
