### ISSUE TITLE
Implement custom shader support in experimental glx backend

### ISSUE THREAD

**Issue by yshui** [yshui/picom#386]
It's decided in #108 that we are going to keep the custom shader support, so we are going to add it to the new backends.

Some considerations must be made to provide a stable and usable interface to the shaders. We should probably look at other custom shader interfaces to learn what to do.

**Comment by gorbit99** [comment]
Hey, I was thinking about some effects the shaders would be good for, but I noticed that there's no way to gain access to the texture that's right under transparent window, or around it even. It would be great for aesthetic effects, like making the colours under those windows less saturated for visibility, or applying an ice sheet like effect. I haven't looked through the code yet to see how the whole thing works, so I'm not sure if there are technical limitations, but either this or custom compositing shader/function would be a great addition.

**Comment by tryone144** [comment]
> We should probably look at other custom shader interfaces to learn what to do.

Maybe [slop's](https://github.com/naelstrof/slop) interface for custom shaders can serve as inspiration: https://github.com/naelstrof/slop#shaders (and the [runtime code](https://github.com/naelstrof/slop/blob/ae8401870fec8663327b03526b48d6381ed0eedf/src/slop.cpp#L247-L324))
