### ISSUE TITLE
picom fails to reinitialize itself on config update on xfce

### ISSUE THREAD

**Issue by absolutelynothelix** [yshui/picom#392]
a while ago i noticed that picom throws this error when exits:
```
X Error of failed request:  GLXBadPixmap
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  23 (X_GLXDestroyPixmap)
  Serial number of failed request:  672
  Current serial number in output stream:  841
```
initially this seemed harmless, but today i discovered that looks like picom can't reinitialize itself on configuration file update, it just throws this error and won't restart.

this happens only with glx backend (both old and new), and looks like it's somehow related to xfce, since it works on bspwm just fine.

basically reproducible with:
```
picom --config /dev/null --backend glx
picom --experimental-backends --config /dev/null --backend glx
```
then hit ctrl-c.

vanilla picom built from latest commit.

**Comment by yshui** [comment]
Can't seems to reproduce the problem here.

**Comment by mighty9245** [comment]
@yshui, maybe you need some additional info? idk what else i can do to point to some particular cause.

**Comment by yshui** [comment]
Is your build a debug build?

**Comment by mighty9245** [comment]
nah, it's release build. but on debug build there is no additional info, the same message is printed.

**Comment by yshui** [comment]
Weird. Maybe some pixmaps were not freed during shutdown

**Comment by mighty9245** [comment]
hmu if you have an idea of fix that i can try :)

**Comment by absolutelynothelix** [comment]
related, i guess: #984

the error is still here, though now it has different style, but picom doesn't fail to reinitialize itself on configuration file change anymore so i'm closing this.
