### ISSUE TITLE
segfault on closing firefox pip window

### ISSUE THREAD

**Issue by mighty9245** [yshui/picom#393]
1. open a youtube video in picture-in-picture in firefox
2. move pip window around, resize it
3. close it using it's close button
and picom segfaults with some probability (not always)

in this particular example i tried this two times and in second time picom segfaulted:
```
workstation:~/Documents/picom/yshui-picom$ ./build/src/picom --experimental-backends
[ 05/02/2020 16:54:14.083 parse_config_libconfig WARN ] Invalid blur method dual_kawase, ignoring.
[ 05/02/2020 16:54:21.738 win_clear_flags WARN ] Flags cleared on a destroyed window 0x00802fe6 (Picture-in-Picture)
[ 05/02/2020 16:54:21.744 win_clear_flags WARN ] Flags cleared on a destroyed window 0x00802fe6 (Picture-in-Picture)
picom: ../src/backend/backend.c:270: paint_all_new: Assertion `!(w->flags & WIN_FLAGS_SHADOW_NONE)' failed.
Aborted (core dumped)
```

i have no idea how to extract a decent stack trace, since ~~i'm dumb~~ there is a lot of threads and all of them have weird stack traces, so i attach a coredump. picom should be built with debug symbols (i did `meson --buildtype=debug . build` when building).
[core.zip](https://github.com/yshui/picom/files/4567882/core.zip)

some thoughts: firefox picture-in-picture window is an utility window and these windows has shadows drawn by something else (just like menus, tooltips, etc. i'm not sure what draws them exactly, maybe xfce? but i have compositing disabled). i also have `shadow = false;` set for `utility` wintype. can these two things conflict somehow?

btw this issue may be a duplicate, because i've seen several issues with the same assertion failure...

**Comment by tryone144** [comment]
I think I've found a fix/workaround for issue https://github.com/yshui/picom/issues/394 which is most likely a duplicate of this one. However I can't reproduce this specific case with the firefox pip window.

Can you try if [this PR](https://github.com/tryone144/picom/tree/fix/clear-shadow-stale-on-unmap) https://github.com/yshui/picom/pull/479 also fixes the assertion failure for you?

**Comment by mighty9245** [comment]
i'm not sure that i'll be able to test it since i don't have a linux environment anymore. closing this because there are other issues like this one.
