### ISSUE TITLE
Shadow on bars

### ISSUE THREAD

**Issue by yshui** [yshui/picom#4]
Shadow of fullscreen window is drawn over docks and bars. This is unlikely what the user wants.

**Comment by OrdinaryMagician** [comment]
I used to work around this with shadow-exclude-reg so it wouldn't cover my tint2, but it doesn't seem to have any effect anymore.

**Comment by tryone144** [comment]
Can now be achieved by the `clip-shadow-above` wintype option for `dock` (see example config). Closing.
