### ISSUE TITLE
Very bad performance and lag in VirtualBox

### ISSUE THREAD

**Issue by tiiiecherle** [yshui/picom#40]
### Platform
archlinux in virtualbox

### GPU, drivers, and screen setup
vboxvideo

### Environment
openbox and mate

### Compton version
v3 with additional commits
[https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/compton&id=611a4d7d3012745b7243df25e1036f0e50ec7f78](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/compton&id=611a4d7d3012745b7243df25e1036f0e50ec7f78)
and latest git

### Compton configuration:
```
# running with empty config file
```

### Steps of reproduction
Login to a desktop environment and start compton &

### Expected behavior
no lag, no performance issues

### Current Behavior
the whole desktop gets almost unusable with a really bad lag.

### Other details
I´m using archlinux and the problem started with version 3.0-2 which cherrypicked a commit from github. The latest git version still has the issue. Downgrading the package to 3.0-1 solves it.

According to [the changes made](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/compton&id=611a4d7d3012745b7243df25e1036f0e50ec7f78) it must be related to changes before that point.

**Comment by tiiiecherle** [comment]
Thanks for the fast answer. Yes, I just rechecked that `3.0-1` is working fine and `3.0-2` is not. Both with empty config file.

**Comment by yshui** [comment]
@tiiiecherle OK, can you do a bisect between c0d7f9d915cb621 (bad) and 16f202f4a0fa6a4a1af6a0b1c519cf3758027c63 (good) then?

**Comment by yshui** [comment]
@tiiiecherle BTW, do you have a video of what the lag looks like?

**Comment by tiiiecherle** [comment]
> @tiiiecherle OK, can you do a bisect between [c0d7f9d](https://github.com/yshui/compton/commit/c0d7f9d915cb621d162efc03cf76388c0a16c2e4) (bad) and [16f202f](https://github.com/yshui/compton/commit/16f202f4a0fa6a4a1af6a0b1c519cf3758027c63) (good) then?

sorry, I don`t know what that means or how to do that.

**Comment by tiiiecherle** [comment]
> @tiiiecherle BTW, do you have a video of what the lag looks like?

No, I don`t. But for example you click on the openbox background and you can not use the opening window as it is selected not fast enough. moving around windows or opening apps is very slow.

**Comment by yshui** [comment]
OK, then. Can you try 5694e759328e519ee4d48dfca8cd5f805c4ac671 and see if that works?

**Comment by yshui** [comment]
@tiiiecherle can you try checking out compton from this repository at that commit, build it and run it?

**Comment by tiiiecherle** [comment]
It would be very nice if you could give me the exact steps / commands how to do that.
Then I will try it out and report back tomorrow. Thanks

**Comment by Anthony25** [comment]
If you're running on Archlinux, install `compton-git` in AUR but edit the PKGBUILD to replace the source by this one:

```
source=(git+"https://github.com/yshui/compton.git#commit=5694e75")
```

**Comment by jrudess** [comment]
Would you mind also trying source=(git+"https://github.com/yshui/compton.git#commit=56f7dd36") ?

I'm also seeing vbox perf issues in #41 and that commit is the last one with the higher performance for my setup.

**Comment by tiiiecherle** [comment]
Sure, I tried, but it gives me an error during building...

```
==> Beginne build()...
Error during basic setup:

Neither directory contains a build file meson.build.
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
Error making: compton-git

```

**Comment by jrudess** [comment]
Ah I forgot.  You'll need to checkout an older version of the PKGBUILD:
```
git checkout c69151e34f044e7f024ef3abb937cc35c83c303d
```
And then comment out a license install line:
```
  # install license
  #install -D -m644 "LICENSES/MIT" "$pkgdir/usr/share/licenses/$_gitname/LICENSE-MIT"
```

**Comment by tiiiecherle** [comment]
Thanks for the heads-up. I did this and indeed with this build everything is working fine. Hope this helps.

**Comment by tiiiecherle** [comment]
Thank you. But I´m sorry to tell you that neither compton-git-next nor compton-3.0-3 are solving the issue. It still persists with both of them.

**Comment by yshui** [comment]
@tiiiecherle Did you pass `--xrender-sync-fence` to compton?

**Comment by tiiiecherle** [comment]
Just tried, the issue still persists with or without using the option.

**Comment by tiiiecherle** [comment]
As I have to give my macbook into repairs for a not-working usb-c port on monday I took some time to filter out the commit causing my issue. I don`t know if it was the right way to do it but I took the old PKGBUILD as decribed in [this](https://github.com/yshui/compton/issues/40#issuecomment-436803607) comment and tried all of these sources...

```
#source=(git+"https://github.com/yshui/compton.git#branch=next")                                            # not working
#source=(git+"https://github.com/yshui/compton.git#commit=50e2259404344a5a3932b8e3873e1c047f31056b")        # not working
#source=(git+"https://github.com/yshui/compton.git#commit=796b0e0448b7233ef18a0c04a7ebe368fdc418ba")        # not working
#source=(git+"https://github.com/yshui/compton.git#commit=be09a9a8357dcd581947f4330036dcb57f791847")        # not working
#source=(git+"https://github.com/yshui/compton.git#commit=d7b5104fd4d3e224ad56920fa5aca91762f9ff17")        # not working
#source=(git+"https://github.com/yshui/compton.git#commit=309a4cec79035c2d873ace7e763ea1c4a0bf6bfd")        # not working

#source=(git+"https://github.com/yshui/compton.git#commit=93dd2d92fd8bc0605119f3862f927b67ae75722e")        # working
#source=(git+"https://github.com/yshui/compton.git#commit=db700f9be1ee7c9e9e7febe337cdb207f9ef34a2")        # working
#source=(git+"https://github.com/yshui/compton.git#commit=df63cab39a1c2ff995ed55186193949b54e55682")        # working
#source=(git+"https://github.com/yshui/compton.git#commit=e13bc7fc51e394c6a0b681c1d0017a9f3326a81a")        # working
#source=(git+"https://github.com/yshui/compton.git#commit=551d48783658323f221b87813b4d84bc76d0e969")        # working
```

As it turned out that the last working commit is [551d48783658323f221b87813b4d84bc76d0e969](https://github.com/yshui/compton/commit/551d48783658323f221b87813b4d84bc76d0e969) and with commit [309a4cec79035c2d873ace7e763ea1c4a0bf6bfd](https://github.com/yshui/compton/commit/309a4cec79035c2d873ace7e763ea1c4a0bf6bfd) the issue starts. Hope this helps.

**Comment by yshui** [comment]
@tiiiecherle Thanks for your effort at diagnosing this problem. Based on your finding, I have some hypothesis about what might be the problem. 

Can you test  a4d351f and see if that fixes your problem?

**Comment by yshui** [comment]
@tiiiecherle If you can confirm that works, I will update the branch to include that commit.

**Comment by tiiiecherle** [comment]
Yes, using this in the PKGBUILD works without the issue.

`source=git+"https://github.com/yshui/compton.git#commit=a4d351f051a039112babe5883eff6ca3da97a6aa")`

Thanks for looking into it.

**Comment by yshui** [comment]
@tiiiecherle Merged into `next` now

**Comment by tiiiecherle** [comment]
Perfect, thanks for alle the help, just tried next and the issue is solved. Have a good day and a nice weekend ;)

**Comment by tiiiecherle** [comment]
Would be really nice to see an updated stable version in archlinux including the fix. Thanks in advance

**Comment by yshui** [comment]
Reopening this since it's reported again.

@tiiiecherle what has changed?

**Comment by dustinwilson** [comment]
I am getting this issue as well where the performance is terrible in virtualbox. Going through this thread I tried 683cda0, and it works just fine so something added between then and now has caused virtualbox to croak. I'll go through the commits from 683cda0 until I reach one that doesn't work anymore like @tiiiecherle did before and report back to you what I find.

**Comment by tiiiecherle** [comment]
@dustinwilson that's great, thanks a lot.

**Comment by dustinwilson** [comment]
Sorry about the wait. I could only test this on a computer I use at work. The first commit I found to cause a great deal of lag starting from 683cda0 is 94b1bc0. That means that the last commit to work (at least for me with Manjaro Xfce in Virtualbox) is 68873ef.

After I went up the tree from 683cda0 and found the first one to not work I tried each of the releases since then and none of them work either, so it looks like whatever was changed in 94b1bc0 is what has Virtualbox confused.

**Comment by yshui** [comment]
@dustinwilson if that's the case, can you run `compton --diagnostics`?

**Comment by dustinwilson** [comment]
**Version:** v4-rc1-54-g94b1bc0

### Extensions:

* Name Pixmap: Yes
* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/dw/.config//compton/compton.conf

**Comment by yshui** [comment]
@dustinwilson perhaps you have a different config file at `/home/dw/.config//compton.conf` or `/etc/xdg/compton.conf`? because the config file at `/home/dw/.config//compton/compton.conf` will NOT be picked up before 94b1bc0

**Comment by tiiiecherle** [comment]
@dustinwilson thanks for looking into this,
@yshui I don't have another config file besides an empty one at `/etc/xdg/compton.conf` and the problem persits with the latest compton version. Thanks for looking into it in advance.

**Comment by yshui** [comment]
@tiiiecherle that means, before 94b1bc0, the config file at `/etc/xdg/compton.conf` will be used, that could explain the performance change

**Comment by tiiiecherle** [comment]
Just to avoid misunderstandings. Yesterday I tried the latest version of compton (7.3-1)
- with an empty config file at `/etc/xdg/compton.conf` (no other config files)
- with an empty config file at `/home/$USER/.config/compton/compton.conf` (no other config files)

In both setups the issue persists. Downgrading back to 5.1-1 and empty config file at `/etc/xdg/compton.conf` (no other config files) works.

**Comment by dustinwilson** [comment]
Sorry about the lack of response on this. I haven't had a chance to test this at work as I haven't been at the computer I can test on. @yshui is right in that the config file at `/etc/xdg/compton.conf` is used then. Since it has no blurring it runs just fine. I plan on going through the commit list again and finding one where it does work so we can pinpoint where the issue starts.

**Comment by yshui** [comment]
there seems to be a lot of problems with vbox's driver. i probably should consolidate them into a single issue. this one is old so i am closing this. if you are still experiencing problems with vbox, search the issue list first, and only open a new one if there isn't one about vbox open already. thanks.
