### ISSUE TITLE
Screen tearing (vsync) problems with new version/config

### ISSUE THREAD

**Issue by hoschi** [yshui/picom#405]
### Platform
Arch 64bit

### GPU, drivers, and screen setup

* nvidia 440.82-12
* mesa 20.0.6-2
* One big 34" ultra wide screen: 3440x1440

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 4096 MB
    Total available memory: 4096 MB
    Currently available dedicated video memory: 3592 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 1050 Ti/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 440.82
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 440.82
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 440.82
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment

Xfce4, X11, Xmonad as window manager

### picom version

7.5

### Configuration:

See: https://gist.github.com/hoschi/1206b19e0813cc210aba0f38aa805135
Only the `compton.conf` with version 7.5 works without any screen tearing or vsync problems. What doesn't work is:
* `compton.conf` with v8
* `picom.conf` with either v7.5 or v8

### Problem description

I tried to update my system this weekend and installed new picom version. With that I tried to migrate my configuration as well. But this resulted in heavy screen tearing problems with normal applications and especially with video. What works at the moment is only 7.5 with the `compton.conf` from Gist.

Without picom running at all, I have the same screen tearing issues, I don't know if this is normal.

**Comment by hoschi** [comment]
I forgot to mention the output when I start `picom` with current config:
```
~ > picom
[ 10.05.2020 17:27:50.797 open_config_file_at WARN ] This compositor has been renamed to "picom", the old config file paths is deprecated. Please replace the "compton"s in the path with "picom"
[ 10.05.2020 17:27:50.797 parse_config_libconfig WARN ] Option `no-dock-shadow` is deprecated, and will be removed. Please use the wintype option `shadow` of `dock` instead.
[ 10.05.2020 17:27:50.797 parse_config_libconfig WARN ] Option `no-dnd-shadow` is deprecated, and will be removed. Please use the wintype option `shadow` of `dnd` instead.
[ 10.05.2020 17:27:50.797 parse_config_libconfig WARN ] Option `menu-opacity` is deprecated, and will be removed.Please use the wintype option `opacity` of `popup_menu` and `dropdown_menu` instead.
[ 10.05.2020 17:27:50.797 parse_config_libconfig WARN ] vsync option will take a boolean from now on. "opengl-swc" is interpreted as "true" for compatibility, but this will stop working soon
[ 10.05.2020 17:27:50.797 parse_config_libconfig WARN ] glx-swap-method has been deprecated since v6, your setting "undefined" should be removed.
[ 10.05.2020 17:27:50.871 swopti_init WARN ] --sw-opti is going to be deprecated. If you get real benefits from using this option, please open an issue to let us know.
[ 10.05.2020 17:27:50.875 x_fence_sync ERROR ] Failed to trigger the fence.
[ 10.05.2020 17:27:50.875 paint_all ERROR ] x_fence_sync failed, xrender-sync-fence will be disabled from now on.
```

**Comment by Elserjo** [comment]
> I forgot to mention the output when I start `picom` with current config:
> 
> ```
> ~ > picom
> [ 10.05.2020 17:27:50.797 open_config_file_at WARN ] This compositor has been renamed to "picom", the old config file paths is deprecated. Please replace the "compton"s in the path with "picom"
> [ 10.05.2020 17:27:50.797 parse_config_libconfig WARN ] Option `no-dock-shadow` is deprecated, and will be removed. Please use the wintype option `shadow` of `dock` instead.
> [ 10.05.2020 17:27:50.797 parse_config_libconfig WARN ] Option `no-dnd-shadow` is deprecated, and will be removed. Please use the wintype option `shadow` of `dnd` instead.
> [ 10.05.2020 17:27:50.797 parse_config_libconfig WARN ] Option `menu-opacity` is deprecated, and will be removed.Please use the wintype option `opacity` of `popup_menu` and `dropdown_menu` instead.
> [ 10.05.2020 17:27:50.797 parse_config_libconfig WARN ] vsync option will take a boolean from now on. "opengl-swc" is interpreted as "true" for compatibility, but this will stop working soon
> [ 10.05.2020 17:27:50.797 parse_config_libconfig WARN ] glx-swap-method has been deprecated since v6, your setting "undefined" should be removed.
> [ 10.05.2020 17:27:50.871 swopti_init WARN ] --sw-opti is going to be deprecated. If you get real benefits from using this option, please open an issue to let us know.
> [ 10.05.2020 17:27:50.875 x_fence_sync ERROR ] Failed to trigger the fence.
> [ 10.05.2020 17:27:50.875 paint_all ERROR ] x_fence_sync failed, xrender-sync-fence will be disabled from now on.
> ```

as i can see, you are using deprecated vsync option in yor config. try just:

`vsync = true;`

**Comment by hoschi** [comment]
> Only the compton.conf with version 7.5 works without any screen tearing or vsync problems.

The only working configuration is actually the one with the deprecated `vsync` option. For me the new `vsync = true` doesn't work.

**Comment by StringBeany** [comment]
I am also experiencing tearing, with versions 8-1 and 8-2 in Manjaro Xfce using vsync=true in picom.conf.

Downgrading to 7.5-3 is enough to fix the issue for me.

**Comment by andersondanilo** [comment]
I was also experiencing tearing after waking up from suspension, now i am using the option "--experimental-backends" and everything looks fine so far. (I am using AwesomeWM)

**Comment by aakodadi** [comment]
> I was also experiencing tearing after waking up from suspension, now i am using the option "--experimental-backends" and everything looks fine so far. (I am using AwesomeWM)

Worked for me too on i3-wm and AMD APU Ryzen 5 PRO 3350G (xf86-video-amdgpu 21.0.0-1)

**Comment by KnowHowGaming** [comment]
> I was also experiencing tearing after waking up from suspension, now i am using the option "--experimental-backends" and everything looks fine so far. (I am using AwesomeWM)

worked for me and i am on Openbox with some crappy laptop (idk the specs)
