### ISSUE TITLE
Please use the display environment variable

### ISSUE THREAD

**Issue by MerrinX** [yshui/picom#408]
### Platform
Xorg with DWM

### GPU, drivers, and screen setup
Nvidia 1080

### Environment
DWM

### Steps of reproduction
I used to start picom with -d flag to get it on all monitors, but now it say; -d is removed, please use the display enviroment variable. What does that mean? I got 3 monitors.

**Comment by mighty9245** [comment]
it means you should export `DISPLAY` environment variable. either globally (e. g. by adding `export DISPLAY=...` to your `.bash_profile` or `.profile`), or locally (e. g. by starting picom with `DISPLAY=... picom ...`).

not sure if syntax is the same, but you may try setting `DISPLAY` to the thing you used to pass to `-d`.

**Comment by MerrinX** [comment]
Right now im using this in my xinitrc;
if [ -f /usr/bin/picom ]; then
	 picom -b -d :0 & 
fi
How do you suggest i change it, i am not following you

**Comment by mighty9245** [comment]
try this one: `DISPLAY=":0" picom -b &`

again: are you sure that picom doesn't work as expected if you don't explicitly configure it to use display `:0`? what if you'll just get rid of this option and launch picom like `picom -b &`?

**Comment by MerrinX** [comment]
It works, but i get lag, when running something on fullscreen on one screen and then using the other screen, just by moving my mouse to another screen create lag.

**Comment by mighty9245** [comment]
so when you started picom with `picom -b` there was the lag you described and starting picom with `picom -b -d :0` used to fix it? that sounds like an issue.

**Comment by MerrinX** [comment]
I have used the same config file, and used to start picom with the -d flag before and had no issue, and now i do, and i can not use the -d flag anymore

**Comment by mighty9245** [comment]
does replacing `picom -b -d :0 &` with `DISPLAY=":0" picom -b &` fix your issue?

**Comment by MerrinX** [comment]
Actually it did... what makes the difference?
