### ISSUE TITLE
Blur effect goes away from the window frame.

### ISSUE THREAD

**Issue by s0nny7** [yshui/picom#413]
### Platform
Debian Sid amd64

### GPU, drivers, and screen setup
Intel HD 530 (6700K), kernel modesetting driver 1.20.8, one monitor connected by onboard DP

xf86-video-intel 2.99.917+git20200226-1

name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) HD Graphics 530 (SKL GT2) (0x1912)
    Version: 20.0.6
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 530 (SKL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.0.6
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.0.6
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.0.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

### Environment
xfce4, with picom as default compositor, xfwm4 as window manager only

### picom version
vgit-e553e

### Configuration:
shadow = true;
shadow-radius = 15;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-exclude = [
  #"name = 'Notification'",
  #"_GTK_FRAME_EXTENTS@:c",
  "class_g = 'Conky'",
  "class_g ?= 'Notify-osd'",
  "class_g = 'Cairo-clock'",
  "class_g = 'Telegram'"
];
fading = false
fade-in-step = 0.03;
fade-out-step = 0.03;
inactive-opacity = 1;
frame-opacity = 0.7;
inactive-opacity-override = false;
active-opacity = 1;
focus-exclude = [ "class_g = 'Cairo-clock'" ];
blur-method = "gaussian"
blur-strength = 3
blur-background-frame = true
blur-background-exclude = [
  #"_GTK_FRAME_EXTENTS@:c",
  #"window_type = 'desktop'",
  "window_type = 'dock'"
];
backend = "glx";
vsync = true
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0
detect-transient = true
detect-client-leader = true
use-damage = true
log-level = "warn";
wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = false; };
  dock = { shadow = false; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 0.8; }
  dropdown_menu = { opacity = 0.8; }
};

### Steps of reproduction
1. just enable blur and shadow for window to check

### Expected behavior
blur effect inside window frame

### Current Behavior
blur effect displays away from window frame

### Stack trace
not crashed

### Other details
![image](https://user-images.githubusercontent.com/6442118/82239859-09505a00-996c-11ea-9a84-5cc05edfeb23.png)

**Comment by arking7** [comment]
@yshui since you mentioned that the problem might have been fixed, I really want to know if there is anything about the possible solution to the problem. I want to help to fix the bug, but I would like to learn more details about the cause or other issues about the same problem.

**Comment by tryone144** [comment]
I've managed to find some time to test this with XFCE4/xfwm4:

The "blurred frame" is offset exactly the top+bottom / left+right frame extents, but only for non-transparent windows (i.e. those where only the frame has to be blurred).
Reverting https://github.com/yshui/picom/commit/fb3305fb9bf7801f0b8608cd92f90d8b548688a8 fixes the issue.

@yshui This raises the question, if the window geometry returned by xcb does or does not actually include the frame extents. Should this be interpreted differently for a reparenting / non-reparenting window manager or is there another reason? I could reproduce the same issue with MATE/marco.

With awesome however, the frame extents aren't included in the geometry, but the height of the titlebar seems to be added twice. This needs some further investigation.

**Comment by arking7** [comment]
@tryone144 Thank you very much for the fix, it eliminates the extra blurry lines perfectly. ;D
