### ISSUE TITLE
Feature Request: Transparent clipping for specific windows.

### ISSUE THREAD

**Issue by xyzshantaram** [yshui/picom#419]
Transparent clipping is great, but sometimes it makes certain items misbehave, such as highlighted text, and so it would be nice if we got the option to only turn it on for certain windows (terminals and text editors and the like) instead of the all-or-nothing approach picom takes right now.

![image](https://user-images.githubusercontent.com/22570968/82959141-a77b9a00-9fd4-11ea-883f-972b53045663.png)
Image: misbehaving highlighted text.

Thanks in advance.

**Comment by OnionHat** [comment]
It would be great if we could do `shadow-exclude` but just for transparent clipping.
```
transparent-clipping-exclude = [
    ...
]
```

**Comment by absolutelynothelix** [comment]
closing as implemented in #738.
