### ISSUE TITLE
Large blur effect causes gpu lag (esp. kernel blur) even at idle

### ISSUE THREAD

**Issue by Kartoffelsaft** [yshui/picom#449]
### Platform
Ubuntu 20.04
Dell XPS 13

### GPU, drivers, and screen setup
Intel UHD graphics 620
A single 1920x1080 screen @ 60hz
i965-va-driver
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) UHD Graphics 620 (KBL GT2) (0x5917)
    Version: 20.0.8
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.0.8
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.0.8
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.0.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment
i3-gaps

### picom version
vgit-fd6ff

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes* Config file used: None

### Configuration:
```
// With 15x15 kernel (Yes I know I can use a config file)
picom --blur-method kernel --backend glx --experimental-backends --blur-kern '15,15,0.0,0.0,0.0,5.2128623625220705,17.00896879022241,25.2326840508547,29.464967285727013,29.464967285727013,25.2326840508547,17.00896879022241,5.2128623625220705,0.0,0.0,0.0,0.0,0.0,0.0,15.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,15.0,0.0,0.0,0.0,0.0,17.00896879022241,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,17.00896879022241,0.0,0.0,11.03493716289379,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,11.03493716289379,0.0,25.2326840508547,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,25.2326840508547,7.1373795560996385,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,13.008810743676655,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,15.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,13.008810743676655,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,7.1373795560996385,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,0.0,25.2326840508547,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,25.2326840508547,0.0,11.03493716289379,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,11.03493716289379,0.0,0.0,17.00896879022241,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,17.00896879022241,0.0,0.0,0.0,0.0,15.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,5.2128623625220705,17.00896879022241,25.2326840508547,29.464967285727013,29.464967285727013,25.2326840508547,17.00896879022241,5.2128623625220705,0.0,0.0,0.0' 
// With 201x201 box (roughly same performance impact)
picom --blur-method box --blur-size 100 --backend glx --experimental-backends
```

### Steps of reproduction

1. run a gpu usage measuring tool (intel_gpu_top in my case)
2. run picom with a very large blur effect

### Expected behavior

low gpu usage when nothing on screen is changing 
input response time shouldn't be much more noticeable than without a blur effect or with a small one

### Current Behavior

~15% gpu usage when nothing is changing
~50% usage when something is
the former feels like it has a laggy response to input and the latter feels like it's running at 20 fps

### Other details
for reference, it is at ~1% with no blur and ~2% with a 3x3 kernel blur when nothing is changing, and ~5% for both when something is.

if I pass --refresh-rate N to picom some transparent windows become much better to use (like my terminal) and some become much, much worse (like firefox with blurredfox). I use the letter N because this applies for basically any number I tried (30, 90, 120, and 244). I have a 60Hz screen.

xrender and the glx xrender hybrid both basically have the same effect that blur would with compton (i.e. this issue but even worse).

**Comment by muneebusmani** [comment]
bruh so sad to see that this problem hasnt been fixed since 2020 i have the same issue i cant use any kinda blur in picom it causes so much input lag for me too

**Comment by yshui** [comment]
@muneebusmani use dual_kawase blur

**Comment by muneebusmani** [comment]
@yshui thanks dude that worked, i didn't knew that ibhagwan's fork was merged because i heard that dual_kawase wasn't in the original picom, btw there are no hints for dual_kawase when we do picom --help, it only shows gaussian, box and kernel.
