### ISSUE TITLE
Picom with experimental-backends crash when changing focus

### ISSUE THREAD

**Issue by owlsome2501** [yshui/picom#465]
### Platform

Arch Linux 5.7.11 amd64

### GPU, drivers, and screen setup

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) HD Graphics 630 (KBL GT2) (0x591b)
    Version: 20.1.5
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 630 (KBL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.1.5
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.1.5
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.1.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```
### Environment

i3-gaps 4.18.2
bspwm 0.9.10
### picom version

vgit-72990 and vgit-e553e
### Configuration:
```
## picom.conf only 4 lines
shadow = true;
shadow-exclude = [
    "focused != 1"
];
```

### Steps of reproduction

1. edit picom.conf and add `focused != 1` into `shadow-exclude`
2. start picom with `experimental-backends`
3. change focus in wm, picom will crash with `segmentation fault`

### Stack trace

```
Stack trace of thread 2789573:
#0  0x000055b14252d55a n/a (picom + 0x2755a)
#1  0x000055b142535027 n/a (picom + 0x2f027)
#2  0x000055b14253af46 n/a (picom + 0x34f46)
#3  0x000055b142512199 n/a (picom + 0xc199)
#4  0x00007fb6a880a033 ev_invoke_pending (libev.so.4 + 0x5033)
#5  0x00007fb6a880d902 ev_run (libev.so.4 + 0x8902)
#6  0x000055b1425103d9 n/a (picom + 0xa3d9)
#7  0x00007fb6a8983002 __libc_start_main (libc.so.6 + 0x27002)
#8  0x000055b1425113fe n/a (picom + 0xb3fe)
```

**Comment by mighty9245** [comment]
can reproduce, segfaults with this:
```
picom: ../src/backend/backend.c:270: paint_all_new: Assertion `!(w->flags & WIN_FLAGS_SHADOW_NONE)' failed.
```

**Comment by botiapa** [comment]
can reproduce

**Comment by tryone144** [comment]
Can you try if [this](https://github.com/tryone144/picom/tree/fix/clear-shadow-stale-on-unmap) fixes the issue (in particular https://github.com/tryone144/picom/commit/ee7ce065f3b95d6429ef62c028ad4e1118670028)?

**Comment by owlsome2501** [comment]
thank you very much! :)
tryone144@ee7ce06 really make it better.
But I noticed that there is a lag between fading in of  new window and its shadow(use i3wm scratchpad).
I can reproduce this bug on tryone144@32754b0. Maybe something in this commit delay the shadow.

**Comment by tryone144** [comment]
Seems indeed be related to mapping and updating window flags in a single step. If you do it before the focus-check you end up without a shadow image in this specific instance. If you do it after, you start the mapping logic one frame to late, so the focus rule won't be applied yet.
It looks like this is a case where there is a "benefit to keep them separate"...

**Comment by tryone144** [comment]
If you'd like to test: I've [updated the fix](https://github.com/tryone144/picom/tree/fix/clear-shadow-stale-on-unmap), so the focus-rule should now work without a lag.

**Comment by owlsome2501** [comment]
It works perfectly! (^^)
