### ISSUE TITLE
Disable fade-in but leave fade-out

### ISSUE THREAD

**Issue by blaxpy** [yshui/picom#466]
I'm trying to achieve the behavior where background is not visible for several milliseconds when opening/closing windows. 

### Environment
bspwm

### Configuration:
Background is visible when closing a window:
```
fading = false
```

Background is visible when opening a new window:
```
fading = true
fade-in-step = 1
fade-out-step = 0.99
fade-delta = 10
```

### Current Behavior
Setting `fading = false` or `no-fading-openclose = true` prevents background visibility when opening a new window. But the background is shown when closing a window in the area of the closed window.

Setting `fade-in-step = 1` does not achieve instant window display when opening a new window, background is shown in the area of the opened window. Setting `fade-out-step = 0.99` prevents background visibility when closing a window.

### Expected behavior
Setting `fade-in-step = 1` opens new windows instantly and prevents background visibility.

**Comment by yshui** [comment]
I don't quite understand what you mean by "background visibility", do you have a clip showing what is actually happening?

**Comment by blaxpy** [comment]
GIF for the first configuration:
[Without fading](https://imgur.com/Nwz2r5M)
GIF for the second:
[With fading](https://imgur.com/Na3mOFU)

**Comment by yshui** [comment]
Hmm, maybe there is a single frame delay even when `fade-in-step = 1`. But even if that's fixed, there is no guarantee you won't see the background. Because everything involved (window manager, compositor, and the application) all has to work correctly to prevent the background from showing.

**Comment by blaxpy** [comment]
Did some tests with firefox. The background was visible without fading when I quickly opened several firefox windows. I see your point.
Decided to change the background color with hsetroot:
```
hsetroot -solid '#fdf6e3'
```
Thank you! Closing the issue.
