### ISSUE TITLE
Picom incorrectly parses exclude rules with && symbol

### ISSUE THREAD

**Issue by rharish101** [yshui/picom#470]
### Platform
Arch Linux, with latest updates as of 2020-08-24.

### GPU, drivers, and screen setup
Intel HD Graphics 530 in an Nvidia Optimus setup with an Nvidia GTX 960M.
Mesa 20.1.6, xf86-video-intel 1:2.99.917+908+g7181c5a4 and Nvidia blob version 450.66.
`glxinfo -B` output:
```
name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) HD Graphics 530 (SKL GT2) (0x191b)
    Version: 20.1.6
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 530 (SKL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.1.6
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.1.6
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.1.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment
i3-gaps (4.18.2) within an Xfce session.

### picom version
`picom --version` output: vgit-e553e.
`picom --diagnostics` output:
```
**Version:** vgit-e553e

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No (Another compositor is already running)
* Config file used: /home/rharish/.config/picom/picom.conf

### Drivers (inaccurate):

modesetting,  
```

### Configuration:
[~/.config/picom/picom.conf](https://github.com/yshui/picom/files/5116083/picom.conf.txt)

### Steps of reproduction
1. Try out this config and observe the shadows. They should be missing.
2. Comment lines 68 and 69 😎 in the config.
3. Run Picom with this new config. The shadows should be visible.

### Expected behavior
Shadows are visible except where defined in the `shadow-exclude` list.

### Current Behavior
Shadows are gone everywhere. The logs mention that every shadow is disabled by the shadow-exclude rule, but this is not the case as in the config. Picom is either interpreting the compund rules wrong, or I have used the wrong syntax.

This used to work previously, but I did a large update of packages, one of which was libconfig, and then this started happening. I tried rolling back libconfig, but it wasn't fixed. I also tried the latest git version of Picom (through the [picom-git package](https://aur.archlinux.org/packages/picom-git/)), but it didn't solve it. I suspected that some package update was the culprit, but the logs seem to imply that Picom is parsing the rules wrong.

### Stack trace
`picom --log-level TRACE` output: [logs](https://github.com/yshui/picom/files/5116076/logs.txt)

**Comment by AitBits** [comment]
I'm seeing similar issue with opacity-rule. It may be the case that other rules are also affected?

**Comment by yoarch** [comment]
As AitBits mentioned it. This [archlinux topic](https://bbs.archlinux.org/viewtopic.php?pid=1922659#p1922659) seems to talk about the same issue.

**Comment by tryone144** [comment]
This issue should be fixed in `next`. Can you please check if this indeed fixes it for you?

**Comment by Ropid** [comment]
@tryone144 Things seem fixed here for me. The `&&` rule that previously caused a problem for me looked like this:

```
shadow-exclude = [
    "class_g ^= 'firefox' && window_type = 'utility'",
];
```

**Comment by rharish101** [comment]
@tryone144 Yes, the current `next` branch fixes this. I tried the [picom-git](https://aur.archlinux.org/packages/picom-git/) AUR package, and it works perfectly. Now we just need a release with this commit.
