### ISSUE TITLE
What is the difference of --no-use-damage and --use-damage?

### ISSUE THREAD

**Issue by tonijarjour** [yshui/picom#475]
`no-use-damage = true;
max-brightness = 1.0;` gives a warning.

`use-damage = false;
max-brightness = 1.0;` doesn't give a warning.

**Comment by tryone144** [comment]
Probably because `no-use-damage` is not a config-file option; therefore the default of `use-damage = true;` is used.
If you want to use the config file use `use-damage = false;`. On the command line you can use `--no-use-damage` instead.
