### ISSUE TITLE
Windows Disappearing when using glx backend

### ISSUE THREAD

**Issue by rahulaggarwal965** [yshui/picom#477]
### Platform

Arch Linux 5.4.60-1-lts amd64

### GPU, drivers, and screen setup
Nvidia RTX 2060, nvidia-drivers (LTS) 450.66-16 (14 LTS)
Intel UHD Graphics 630, mesa 20.1.6-1
Two monitors configured side by side with xrandr, system has hybrid graphics and the Nvidia GPU is used for rendering to the HDMI output.

Output of glxinfo -B

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) UHD Graphics 630 (CFL GT2) (0x3e9b)
    Version: 20.1.6
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics 630 (CFL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.1.6
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.1.6
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.1.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment
bspwm 

### picom version
vgit-00346

### Configuration:
```
# GLX backend
backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = false;
glx-no-rebind-pixmap = true;

# Blur
#blur-background = true;
#blur-method = "dual_kawase";
#blur-strength = 3;
#blur-background-exclude = [
#    "class_g = 'slop'"
#];

# Fading
fading = true;
fade-delta = 4;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-exclude = [ ];

# Other
mark-wmwin-focused = true;
mark-ovredir-focused = true;
use-ewmh-active-win = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0;
vsync = true;
dbe = false;
unredir-if-possible = true;
focus-exclude = [ ];
detect-transient = true;
detect-client-leader = true;

# Fix Borders
use-damage = false;

# XSync
xrender-sync-fence = true;
```

### Steps of reproduction
1. Run picom with the above config using experimental backend glx
2. Send window to another desktop (in bspwm)
3. Watch as 1 or more windows disappear on the new desktop

### Expected behavior
Windows should not disappear when switching desktops

### Current Behavior
Windows disappear when switching desktops. This only happens with the glx backend and if log-level is set to debug, the windows do not disappear. Xrender backend is completely fine at all times. Even when blur is disabled on the glx backend, bug still appears.

### Other details
Here is a video I recorded of the problem.
https://youtu.be/YO22RBBcVfg

EDIT:
Now I get this bug no matter how I use picom, glx or xrender

**Comment by yshui** [comment]
The window do come back when you mouse move it?

Can you attach a debug log?
