### ISSUE TITLE
Big Frames in planner app

### ISSUE THREAD

**Issue by Magnus512** [yshui/picom#488]
### Platform

ArchLinux 
### GPU, drivers, and screen setup
NVidia GTX 960 
nvidia-drivers 450.66
two monitors configured side-by-side with xrandr

name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 2048 MB
    Total available memory: 2048 MB
    Currently available dedicated video memory: 1740 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 960M/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 450.66
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 450.66
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 450.66
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
### Environment
Awesome WM
### picom version

vgit-e553e
### Configuration:
[picom.log](https://github.com/yshui/picom/files/5213361/picom.log)

### Steps of reproduction
Open planner app 

### Expected behavior
Getting planner app open with normal frame

### Current Behavior
Open planner app and getting big frames around the window

### Other details
![frame](https://user-images.githubusercontent.com/7065012/93006548-c584f000-f51a-11ea-8b37-36e5ab4424dc.png)

**Comment by yshui** [comment]
what does it look like when picom is not running?

**Comment by Magnus512** [comment]
> what does it look like when picom is not running?

The same :O T_T

**Comment by mighty9245** [comment]
@Magnus512, then it's not a picom issue. probably a wm one.

**Comment by Magnus512** [comment]
> wm

I tried more than one wm
