### ISSUE TITLE
Frame-Opacity to Zero

### ISSUE THREAD

**Issue by bajaco** [yshui/picom#506]
Hello,

I'm curious whether the minimum frame-opacity being 0.1 is a technical constraint or if something could be changed to allow for a value of 0.0. My interest in this is so I can set my openbox theme's borders to a particular width, thus creating an invisible margin between applications.

But perhaps I should be searching for a different window manager.

**Comment by absolutelynothelix** [comment]
done in #655 (included in [the v9-rc1 pre-release](https://github.com/yshui/picom/releases/tag/v9-rc1)).

closing as done.
