### ISSUE TITLE
dual_kawase - Invalid blur method

### ISSUE THREAD

**Issue by qautomotive** [yshui/picom#508]
### Environment
fluxbox

### picom version
v8.1

### Configuration:
```
N/A no config stipulated
```

### Steps of reproduction
$ picom --experimental-backends --backend glx --vsync --config /dev/null --blur-method dual_kawase --blur-strength 5
picom: unrecognized option '--blur-strength'
$ picom --experimental-backends --backend glx --vsync --config /dev/null --blur-method dual_kawase
[ 10/14/2020 08:59:00.468 get_cfg WARN ] Invalid blur method dual_kawase, ignoring.

1.
2.

### Expected behavior
See dual_kawase
### Current Behavior
No blur

### Other details
I did **not** build from source. Is building from source necessary for me to action the below:
https://github.com/yshui/picom/issues/32#issuecomment-683979875

**Comment by tryone144** [comment]
v8.1 does not yet include the dual-filter kawase blur algorithm. If you don't want to wait until v9 ships out, you have to build the `next` branch yourself.

**Comment by chebro** [comment]
> Iyou have have to build the `next` branch yourself.

Is the next branch WIP? I tried building it today and the built binary fails with segmentation fault
