### ISSUE TITLE
Config include directive, or multiple config files?

### ISSUE THREAD

**Issue by OJFord** [yshui/picom#510]
### picom version
`vgit-2c9e7`

As far as I can tell, this is not currently a feature, but sorry if I've just missed it.

I'd like to be able to include `/etc/xdg/picom.conf` from my `$XDG_CONFIG_HOME/picom/picom.conf`, as a sort of starting point from which I override some changes.

Motivation being that I added a single option to my conf, and observed that picom 'stopped working', no errors, removed the single option, no change; couldn't work out else I'd done that affected it. It took me some time (embarrasingly long, really) to work out it was the _existence_ of my config file, essentially configuring it to do nothing.

The defaults are perhaps a bit surprising if you've previously known the system default conf, but understandable. I'm not suggesting a change in behaviour for an empty config file, but I would like to do something like:

```conf
include = /etc/xdg/picom.conf
# ...
```

to explicitly include any configuration defined elsewhere. Subsequent configuration to then _override_ anything already set by the included conf.

Again, sorry if this is possible and I've just missed it. Cheers.

**Comment by yshui** [comment]
@OJford No worries.

picom uses libconfig, and libconfig has an include directive: https://www.hyperrealm.com/libconfig/libconfig_manual.html#Include-Directives

**Comment by OJFord** [comment]
Splendid, many thanks!
