### ISSUE TITLE
How to make focus exclude pattern match any app except terminal?

### ISSUE THREAD

**Issue by 4kanesora** [yshui/picom#517]
As the title, simple question here :-)
I tried a regex '^(?!Alacritty).*$' but it seems can't work.

**Comment by yshui** [comment]
Can you paste your entire focus exclude rule?

**Comment by mighty9245** [comment]
something like `"!class_g = 'Alacrityy'"`

**Comment by absolutelynothelix** [comment]
closing as stale.
