### ISSUE TITLE
X video memory leaks when use Java Swing application

### ISSUE THREAD

**Issue by gnayils** [yshui/picom#532]
### Platform
CentOS 7.6 SP1 x86_64

### GPU, drivers, and screen setup
NVidia Quadro P1000, nvidia-driver 455.28, one monitor with resolution 3840x2160

### Environment
fvwm 2.6.5

### picom version
**Version:** v8.2

### Extensions:
* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:
* Use Overlay: No (Another compositor is already running)
* Config file used: None

### Drivers (inaccurate):
NVIDIA

### Configuration:
```
picom --backend xrender --xrender-sync-fence --vsync --no-use-damage
```

### JDK version:
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

### Steps of reproduction
1. Start the picom with the command: picom --backend xrender --xrender-sync-fence --vsync --no-use-damage
2. Save below Java code to DialogSwitchTest.java, then compile it use the command: javac  DialogSwitchTest.java
```
import javax.swing.*;

public class DialogSwitchTest {

    static JDialog dialogA = new JDialog();
    static JDialog dialogB = new JDialog();

    static JDialog currentDialog;

    public static void main(String[] args) {
        JButton buttonA = new JButton("Switch to DialogB");
        buttonA.addActionListener((e) -> switchDialog());
        buttonA.setBounds(0, 0, 200, 50);
        dialogA.getContentPane().setLayout(null);
        dialogA.getContentPane().add(buttonA);
        dialogA.setBounds(0, 0, 1920, 1920);

        JButton buttonB = new JButton("Switch to DialogA");
        buttonB.addActionListener((e) -> switchDialog());
        buttonB.setBounds(0, 0, 200, 50);
        dialogB.getContentPane().setLayout(null);
        dialogB.getContentPane().add(buttonB);
        dialogB.setBounds(0, 0, 1920, 1920);

        currentDialog = dialogA;
        switchDialog();
    }

    public static void switchDialog() {
        currentDialog.dispose();
        if(currentDialog == dialogA) {
            currentDialog = dialogB;
        } else {
            currentDialog = dialogA;
        }
        SwingUtilities.invokeLater(() -> currentDialog.setVisible(true));
    }
}
```
3. Open a terminal, use the command to monitor the video memory: watch -n 1 nvidia-smi
4. Execute the Java code by the command: java -Dsun.java2d.opengl=true DialogSwitchTest
5. Hit the switch button in the dialog quickly, observe the video memory that used by X, it will increased significantly, and it never drop down even if close the Java application

**Comment by yshui** [comment]
Why do you think this is a picom issue?

**Comment by gnayils** [comment]
When I start the Java application without picom running, hit the switch button quickly, it's fine, the X's video memory doesn't even change.

**Comment by yshui** [comment]
If you can, run `picom` under [xtrace](https://github.com/yshui/xtrace) and attach the output here. I think picom probably didn't free up some resources, `xtrace` output will help verify if that's the case.

you use `xtrace` like this: `xtrace -ologfile picom [picom arguments]`

**Comment by gnayils** [comment]
Here is the trace log for the picom.
[picom-trace.log](https://github.com/yshui/picom/files/5463515/picom-trace.log)
By the way, it seems missing to deploy the misc.proto file to /usr/local/share/xtrace directory during xtrace installation.

**Comment by yshui** [comment]
> By the way, it seems missing to deploy the misc.proto file to /usr/local/share/xtrace directory during xtrace installation.

Thanks for pointing this out!

**Comment by yshui** [comment]
Looks like some of the window data is outright not freed. Can you run `picom` through valgrind and see if there's any memory leaks?

**Comment by gnayils** [comment]
OK, I will do it on next monday.

**Comment by gnayils** [comment]
valgrind output for picom: [valgrind-out.txt](https://github.com/yshui/picom/files/5472970/valgrind-out.txt)

**Comment by yshui** [comment]
Hmm, looks like my suspicion isn't true. But I spotted a few other memory leaks, so that was at least helpful.

**Comment by yshui** [comment]
Does the `--experimental-backends` have the same problem?

**Comment by gnayils** [comment]
Yes, it does.
picom started by the command: `picom --experimental-backends --xrender-sync-fence`

**Comment by yshui** [comment]
Hmm, could you run `picom --experimental-backends --backend=dummy`, repeat what you did, Ctrl-C picom, then upload picom's log here?

**Comment by gnayils** [comment]
Nothing output to the terminal during repeat switch dialog, just below two lines at picom started.
`bash-4.2$ picom --experimental-backends --backend=dummy
[ 12/01/2020 17:14:53.330 x_fence_sync ERROR ] Failed to trigger the fence (X error 136 XSyncBadFence request 134 minor 15 serial 356)
[ 12/01/2020 17:14:53.330 paint_all_new ERROR ] x_fence_sync failed, xrender-sync-fence will be disabled from now on.
^Cbash-4.2$ `

**Comment by gnayils** [comment]
If start with `--xrender-sync-fence`, there something output to the terminal:
```
bash-4.2$ picom --experimental-backends --backend=dummy --xrender-sync-fence
[ 12/01/2020 17:32:05.541 win_clear_flags WARN ] Flags cleared on a destroyed window 0x0080dbde ( )
[ 12/01/2020 17:32:11.673 win_clear_flags WARN ] Flags cleared on a destroyed window 0x0080e29e ( )
[ 12/01/2020 17:32:11.840 win_clear_flags WARN ] Flags cleared on a destroyed window 0x0080e2ce ( )
^Cbash-4.2$ 
```

**Comment by yshui** [comment]
Hmm, so looks like picom is not leaking pixmaps. Is `--xrender-sync-fence` required to reproduce this bug?

**Comment by gnayils** [comment]
I tried different start args for picom, here is the result:
start picom with: `picom --experimental-backends --xrender-sync-fence`, memory leaks: `yes`
start picom with: `picom --experimental-backends --backend=dummy`, memory leaks: `yes`
start picom with: `picom --experimental-backends`, memory leaks: `no`
start picom with: `picom --experimental-backends --backend glx`, memory leaks: `no`
start picom with: `picom --experimental-backends --backend xrender`, memory leaks: `no`
start picom with: `picom --backend glx`, memory leaks: `no`
start picom with: `picom --backend xrender`, memory leaks: `no`
start picom with: `picom --backend glx --xrender-sync-fence`, memory leaks: `yes`
start picom with: `picom --backend xrender --xrender-sync-fence`, memory leaks: `yes`
start picom with: `picom --backend glx --vsync`, memory leaks: `yes`
start picom with: `picom --backend xrender --vsync`, memory leaks: `no`

**Comment by yshui** [comment]
@gnayils That's very thorough, thanks a lot.

**Comment by absolutelynothelix** [comment]
currently there are no known leaks in picom. if you think you found a leak in picom, please create a new issue.

closing as stale.
