### ISSUE TITLE
Shadow exclusion for conky on i3 or any titling window manager

### ISSUE THREAD

**Issue by tobeypeters** [yshui/picom#533]
Is there anyway to turn off shadows and blurring for conky widgets, if you are running picom and conky on i3?  The only way to get conky to display in i3 "correctly" is by setting own_window_type to "override" and no matter what I do I can't get the shadows to go away.

**Comment by mighty9245** [comment]
you have to use `shadow-exclude` and `blur-background-exclude` with conky's class, roughly `class_g = 'Conky'`

**Comment by tobeypeters** [comment]
Those options don't seem to work, if you have own_window_type set to 'override'.  At least, on i3, setting it to 'override' is the only way for conky widgets to display "correctly".  Otherwise, the widgets get treated as an i3 window and they get tiled.  You can make them a floating window.  But, then you have conky widgets floating on top of your applications.  Setting the window type to 'override' embeds them in the 'desktop' window, like we want.

**Comment by mighty9245** [comment]
if you want to get rid of shadows and blurring you have to use `shadow-exclude` and `blur-background-exclude` with a corresponding class (iirc it's `Conky` by default, but you can set your own in the conky's config). your problem with tiling of conky's widget is related to the wm and you should configure it to work correctly.
