### ISSUE TITLE
inactive-dim/inactive-opacity do not affect other windows of the same program

### ISSUE THREAD

**Issue by mtjn** [yshui/picom#534]
### Platform
EndeavourOS LInux x86_64

### GPU, drivers, and screen setup
AMD Ryzen 5 Pro 4650U with Radeon Graphics (12)
Built-in laptop screen 1920x1080
Driver: amdgpu

from glxinfo -B:
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD RENOIR (DRM 3.39.0, 5.9.1-arch1-1, LLVM 10.0.1) (0x1636)
    Version: 20.2.1
    Accelerated: yes
    Video memory: 512MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 279 MB, largest block: 279 MB
    VBO free aux. memory - total: 3011 MB, largest block: 3011 MB
    Texture free memory - total: 279 MB, largest block: 279 MB
    Texture free aux. memory - total: 3011 MB, largest block: 3011 MB
    Renderbuffer free memory - total: 279 MB, largest block: 279 MB
    Renderbuffer free aux. memory - total: 3011 MB, largest block: 3011 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 512 MB
    Total available memory: 3584 MB
    Currently available dedicated video memory: 279 MB
OpenGL vendor string: X.Org
OpenGL renderer string: AMD RENOIR (DRM 3.39.0, 5.9.1-arch1-1, LLVM 10.0.1)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.2.1
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.2.1
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.2.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment
lightdm + i3-gaps

### picom version
version: vgit-dac85 (package from pacman: picom-8.2-1)

### Configuration:
https://pastebin.com/ckMMkTmj

### Steps of reproduction
Set values for `inactive-opacity` or `inactive-dim` <1.0

### Expected behavior
All inactive windows are dimmed, including windows from the same application

### Current Behavior
Only inactive windows from different applications are dimmed. If two instances of xfce4-terminal, the inactive instance will not be dimmer or made opaque.

#### Terminal window one active, terminal 2 inactive but fully opaque
![2020-10-30-17:33:18-screenshot](https://user-images.githubusercontent.com/26892660/97660346-8e8a7f80-1a71-11eb-8d3b-765481ef3a2d.png)

#### Firefox window one active, Firefox 2 inactive but fully opaque
![2020-10-30-17:33:21-screenshot](https://user-images.githubusercontent.com/26892660/97660351-91857000-1a71-11eb-8cf3-deb561207506.png)

**Comment by tryone144** [comment]
Both, firefox and your terminal emulator, most likely set `

**Comment by mtjn** [comment]
Thanks, did the trick! Sorry, I did look through the sample config file but missed this setting.

**Comment by jpribyl** [comment]
Seems like most people would probably expect the default on this config option to be false- it just got me too because I copied my conf from `/usr/share/doc/picom/picom.conf.example` without paying too much attention. Guess I'll submit a PR :smile:
