### ISSUE TITLE
page allocation failure

### ISSUE THREAD

**Issue by safocl** [yshui/picom#537]
archlinux x86_64

NVidia GTX 1650 nvidia-drivers 455.38, one monitor 1080p
mesa 20.2.1

```
--> glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 4096 MB
    Total available memory: 4096 MB
    Currently available dedicated video memory: 3306 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 1650/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 455.38
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 455.38
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 455.38
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

i3-wm 4.18.3
```

--> picom --version
vgit-dac85
```
```
--> picom --diagnostics
**Version:** vgit-dac85

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No (Another compositor is already running)
* Config file used: /home/safff/.config/picom.conf


### Drivers (inaccurate):

NVIDIA
```
### Configuration:
[config](http://ix.io/2DsM)

### Steps of reproduction
this bug appears at any time the PC is running.

### Current Behavior
The graphical interface is completely frieze, but everything else continues to work (sound, keyboard response, etc.), hangs the same action NUM LOCK.
It feels like Xorg is starting to slow down very hard.

### journalctl
[journalctl -b](http://ix.io/2DsX)

**Comment by tryone144** [comment]
The system log shows a page allocation failure in the nvidia driver. See [this post](https://bbs.archlinux.org/viewtopic.php?id=260131) for a possible work-around on arch.

[This post](https://forums.developer.nvidia.com/t/455-23-04-page-allocation-failure-in-kernel-module-at-random-points/155250) on the official nvidia forum mentions an experimental [patch](https://forums.developer.nvidia.com/t/455-23-04-page-allocation-failure-in-kernel-module-at-random-points/155250/55) for the 455.38 driver that hasn't made it into the stable release yet.

**Comment by safocl** [comment]
ok.
