### ISSUE TITLE
Question: Any improvements with --experimental-backends for glx, NVIDIA users?

### ISSUE THREAD

**Issue by kwand** [yshui/picom#543]
A question on this line in the README:

> Currently, new backends feature better vsync with the xrender backend and improved input lag with the glx backend (for non-NVIDIA users). The performance should be on par with the old backends.

I've searched around, including reading the Wiki and past issues - though I very likely missed more than a few things - my interpretation of the above is, assuming that it is still accurate and up-to-date, there are currently no performance improvements for NVIDIA users with the new backends (glx)?

_(Or have there been some changes in the past months that do benefit NVIDIA users?_

_I did read in the wiki that there are some difficulties/obstacles due to how NVIDIA implements drivers - though I didn't fully understand what I was reading, so this might be a misinterpretation)_

**Comment by yshui** [comment]
At the moment there aren't any improvements for NVIDIA users. @kwand
