### ISSUE TITLE
Ignore blur for some windows

### ISSUE THREAD

**Issue by Ohio2** [yshui/picom#545]
I just want to know, is it possible, i wanna use discover overlay but it just blurs out some parts of the screen.

**Comment by kdarkhan** [comment]
What you want is `blur-background-exclude` config.
I don't have discover-overlay installed so you will need to find how to specify it yourself.
The list is a comma separated. Here is my `~/.config/picom.conf` for example.
```
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'mpv'",
  "name = 'conky'",
  "name = 'mpv'",
  "class_g = 'zoom'",
  "window_type = 'desktop'",
  "window_type = 'utility'"
];
```

**Comment by tryone144** [comment]
This should work for [discover-overlay](https://github.com/trigg/Discover):
```
blur-background-exclude = [
  "class_g = 'Discover-overlay'",
];
```

**Comment by Ohio2** [comment]
Thanks alot tryone, for both the `tryone` fork and your answer!
