### ISSUE TITLE
Tearing when back from sleep/screensaver

### ISSUE THREAD

**Issue by ghost** [yshui/picom#55]
### Platform
Archlinux - latest

### GPU, drivers, and screen setup
intel - hd630

### Environment
just X and minimal wrapper to call X

### Compton version
v4-rc1-14-gf834cf2

### Compton configuration:
Really doesn't matter.

### Steps of reproduction
1. put pc to sleep or let it fall into screensaver mode (black screen), I use slcock to lock screen
2. press any key to bring it back
3. check xorg.log will see some pauses like below:
```
[   281.243] (II) systemd-logind: got pause for 13:66
[   281.243] (II) systemd-logind: got pause for 13:64
[   281.243] (II) systemd-logind: got pause for 13:72
[   281.243] (II) systemd-logind: got pause for 13:65
[   281.243] (II) systemd-logind: got pause for 13:73
```
4. now every X apps has slow response on and start tearing - means like compton has never started, but in background it is actually running: `ps aux | grep compton`
Note: base on my test, mostly when you got pause you have the issue but sometime put X in sleep and wake it up doesn't have this issue, so it has random element.

### Expected behavior
compton can also be woke up in an consistent way.
### Current Behavior
sometime and somehow put X into sleep mode also make we losing compton function.
### Other details

I use KMS mode, no intel kernel options when booting, no fastboot, also disabled fastboot in bios.
I use silent boot options in kernels - but I don't think these options bring problem.

I haven't tested to kill compton and manually re-call it when issue happens.

I start compton in `.xinitrc`: `compton --config $HOME/.config/compton.conf &>/dev/null 2>&1 &
`

**Comment by yshui** [comment]
What is in your `compton.conf`?

**Comment by tuyenpm9** [comment]
I use exactly compton.conf from here: https://github.com/yshui/compton/issues/34#issue-375708445

At first I also believe this is hardware/driver issue, that's why I removed most kernel options relative to intel driver.

I have to admit with few tests with modesettings driver I don't have the issue but need more tests, but I don't have consistent compton.conf of modesettings driver to completely eliminate tearing.

**Comment by tuyenpm9** [comment]
Should we listen of socket of X to start placeholder xorg.service then put hook into suspend@.target like https://wiki.archlinux.org/index.php/Power_management#Suspend/resume_service_files to restart compton.service after suspend. Haven't implemented.

**Comment by clapbr** [comment]
I am not sure it's the same problem I have but sometimes when my pc sleeps/wake everything stutters hard, specially chromium, until I restart compton. Maybe the solution above would solve those kinds of problems. I have an AMD gpu though, not an Intel one.

**Comment by tuyenpm9** [comment]
If it `stutters`, all X apps will be affected, video tearing etc..

**Comment by yshui** [comment]
most likely a driver issue. closing because this is old.
