### ISSUE TITLE
Regression: xinerama-shadow-crop removes shadow under i3bar

### ISSUE THREAD

**Issue by sersorrel** [yshui/picom#554]
### Platform
Ubuntu Desktop 18.04 amd64

### GPU, drivers, and screen setup

nvidia gtx 1050, nvidia-drivers 455.45, two monitors with xrandr
```console
$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 4096 MB
    Total available memory: 4096 MB
    Currently available dedicated video memory: 3039 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 1050/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 455.45.01
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 455.45.01
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 455.45.01
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment

i3wm 4.19

### Configuration:
```
backend = "glx";
# backend = "xr_glx_hybrid";

vsync = true;

# Attempt to unredirect when a fullscreen window is detected for improved performance.
# unredir-if-possible = true;
# Don't unredirect windows that asked for compositing.
unredir-if-possible-exclude = [
	"_NET_WM_BYPASS_COMPOSITOR@:c = 2",
	"class_g = 'Totem'"
];

shadow = true;
# https://github.com/chjj/compton/issues/408
shadow-exclude = [
	"class_g = 'i3-frame'",
	"class_g = 'i3bar'",
	# don't draw shadows for hidden windows (e.g. those in other tabs), but only if they're not floating
	# the update-notifier window is always "hidden", even when it's visible, so this hack is required
	# "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
	# originally:
	# "_NET_WM_STATE@[0]:32a *= '_NET_WM_STATE_HIDDEN' && !I3_FLOATING_WINDOW@:c = 1",
	# "_NET_WM_STATE@[1]:32a *= '_NET_WM_STATE_HIDDEN' && !I3_FLOATING_WINDOW@:c = 1",
	"_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN' && !I3_FLOATING_WINDOW@:c = 1"
	# "_GTK_FRAME_EXTENTS@:c", # avoid double shadows on some windows?
];
# shadow-exclude-reg = "x31+0-0"; # don't draw shadows under i3bar
xinerama-shadow-crop = true; # don't draw shadows across displays

# Step the fade every 5ms.
fade-delta = 5;
# Only fade certain windows.
wintypes:
{
	tooltip = { fade = true; };
	notify = { fade = true; };
}
```

### Steps of reproduction
1. run picom

### Expected behavior
picom should draw shadows under (or I guess over, really) i3bar, like it used to

### Current Behavior
since commit a56d66b4f35d975276935305dc381dc070f39922 it no longer does so if xinerama-shadow-crop is enabled

**Comment by yshui** [comment]
Do you have before/after screenshots?

**Comment by sersorrel** [comment]
Before: ![image](https://user-images.githubusercontent.com/9433472/101026270-9d7fb880-356e-11eb-9f7a-d9742449999f.png)

After: ![image](https://user-images.githubusercontent.com/9433472/101026364-b7210000-356e-11eb-8bee-9ca35609665a.png)

**Comment by yshui** [comment]
Not sure exactly what is going on here...

Can you update to the latest `next` branch, then [capture a apitrace](https://github.com/yshui/picom/wiki/Reporting-issues#capture-a-trace)? May or may not help me find out why, but worth a try.

**Comment by sersorrel** [comment]
apitrace: https://sorrel.sh/public/defe8e75-5c3c-4f92-a831-4f54ef3d75d9-picom-trace-8be379d.zip

I now notice that (at least on latest `next`) the issue isn't "shadows aren't drawn under i3bar", it's "windows that existed before picom was started don't have shadows until they're moved or resized" – if I untile and retile the windows in i3 (which implies a move and potentially a resize), then the shadow reappears.

**Comment by yshui** [comment]
@sersorrel i see, this is probably because picom thought the window is on the wrong monitor.

**Comment by yshui** [comment]
@sersorrel I think I fixed it, can you give it a try?

**Comment by sersorrel** [comment]
It seems like 3c38b36 fixed this for the primary monitor, but there are issues on the other monitor: existing floating windows always get shadows immediately, but existing tiled windows on the second monitor don't (and newly-created windows on the second monitor also don't get shadows). Also, floating windows that cross the border between the two monitors only draw a shadow on the primary (left) monitor:

![image](https://user-images.githubusercontent.com/9433472/101245686-62b08880-3706-11eb-89c2-82e00fc99dfc.png)

(everything still behaves like it should once windows are moved/resized)

**Comment by yshui** [comment]
@sersorrel can you try again?

**Comment by sersorrel** [comment]
Looks like that fixed it! Thank you so much :)
