### ISSUE TITLE
opacity = false ?

### ISSUE THREAD

**Issue by doleovit** [yshui/picom#556]
### Platform
void

### Environment
bspwm

### picom version
picom-8.2_1

### Configuration:
```
# glx or xrender
backend = "glx";

# core 
glx-no-rebind-pixmap = true;
unredir-if-possible = true;
glx-no-stencil = true;
use-damage = true;
vsync = true;

# nope
shadow = false;

# nope
fading = false;

# ugly; don't want that
opacity-rule = [ 
"100:class_g" 
];
```

thanks for your work. everything works as it should. at least in my case. for now. however, i do not depend on transparency/opacity on behalf of "picom", because urxvt's pseudo - transparency is really enough. i need the compositor for this "core" stuff, not for anything else. 

i search .. and search .. ad infinitum. but i can't find a simple killswitch like that:

opacity = false

how can this transparency/opacity stuff be completely disabled?

**Comment by yshui** [comment]
not sure what you mean. what is still transparent with your configuration?

**Comment by doleovit** [comment]
i do not want to waste your time. you're working hard. the only gui i have is ff, and even without the ugly opacity-rule in this configuration, there's no transparency in ff (panels/menus). 

what i meant: why there is no simple "killswitch" like:

``opacity = false``

metaphor: instead of sending an "impulse" and then "suppressing" it (i guess), there should be the possibility to not send the "impulse" in the first place. 

it would also be - measured by the amount of possible (if not too much) options - more intuitive for the user, if there would be an option, called .. "opacity = false". i miss that, if i do `man picom | less` ,  /opacity. 

so there are 2 reasons for this question. but not _that_ important. thx anyway & stay healthy.

**Comment by yshui** [comment]
@doleovit I think by default there is no opacity enabled, so having this option probably isn't that helpful.

**Comment by doleovit** [comment]
@yshui  uh .. that's what i needed to understand. it's that simple. sry. 

"opacity-rule above, i expell you into the bit emptied nirvana!" 

thx (again).
