### ISSUE TITLE
FR: blur-method = "kawase";

### ISSUE THREAD

**Issue by zdmgmail** [yshui/picom#563]
### Expected behavior

![gaussian](https://user-images.githubusercontent.com/50515839/101780617-bae5f100-3b31-11eb-8cec-9e26cb1a2229.png)

![gaussian1010](https://user-images.githubusercontent.com/50515839/101788418-081a9080-3b3b-11eb-8cd7-92b4166fb1e2.png)

![kawase](https://user-images.githubusercontent.com/50515839/101780631-bde0e180-3b31-11eb-8ad7-37f264def618.png)

the first picture is picom, `blur-method = "gaussian";`
the second picture is picom , `blur-method = "gaussian"; blur-deviation = 10 blur-size = 10`
the third picture is compton,  `blur-method = "kawase";`

both opacity=50

hope can blur like `kawase` in the third pic,  come from `https://github.com/tryone144/compton`

**Comment by tryone144** [comment]
When using a recent build from the `next` branch, you can use the dual-filter kawase blur with the experimental glx backend (see https://github.com/yshui/picom/issues/32#issuecomment-683979875 and https://github.com/yshui/picom/pull/382).
Use it with `--experimental-backends` and
```
backend = "glx";
blur-method = "dual_kawase";
blur-strength = 7;
```
in your config.
The old parameter "kawase" still works but has been deprecated in favor of "dual_kawase" to better reflect that the underlying algorithm uses in fact two two different kawase-filters.
