### ISSUE TITLE
Redirected Issue

### ISSUE THREAD

**Issue by mohammeder55** [yshui/picom#566]
**Platform**: Ubuntu Desktop 20.04 amd64

**Environment**: KDE + AwesomeWM

I was redirected by this [fork](https://github.com/jonaburg/picom) of picom, as someone thought this should be reported here.

When trying to build from source:
```
$ meson --buildtype=release . build
```
I get something along the lines of `libpcre not found`. It turned out that I had to install `libpcre3-dev` instead of `libpcre2-dev` to make things work.

**Comment by yshui** [comment]
> install libpcre3-dev instead of libpcre3-dev

a typo?

**Comment by mohammeder55** [comment]
Should be alright now

**Comment by yshui** [comment]
oh my, package naming in debian is dumb...
