### ISSUE TITLE
Report inactivity to systemd's logind?

### ISSUE THREAD

**Issue by Diaoul** [yshui/picom#574]
More like a discussion / feature request: is it possible for picom to report inactivity to systemd somehow?

Context: I want to use logind's capability to suspend my computer after a period of inactivity. For that I would like to use [IdleAction](https://www.freedesktop.org/software/systemd/man/logind.conf.html#IdleAction=) however it requires *that user sessions correctly report the idle status to the system*.
Looks like without a DE, the state isn't reported correctly.
I've stumbled upon https://github.com/systemd/systemd/pull/14925 that implements a `SetType` method to change session type (take a look at the associated issue).

Is picom the right place to implement this? The inactive dim works great, I would love to plug that into logind!

**Comment by yshui** [comment]
This is not something picom could/should do.

**Comment by Diaoul** [comment]
Where would this be better implemented? In the WMs?

```bash
journalctl -u systemd-logind.service -f
```
Shows
```
Dec 22 12:07:35 local systemd-logind[382]: New session c1 of user lightdm.
Dec 22 12:07:46 local systemd-logind[382]: New session 2 of user diaoul.
Dec 22 12:07:46 local systemd-logind[382]: Removed session c1.
```

**Comment by tryone144** [comment]
@Diaoul If your WM doesn't implement something like that you might be able to "abuse" something like `xautolock` to send a message to logind (instead of starting the screenlocker).
Keeping track of system-idle / user-idle is not the task of an X compositor.

**Comment by Diaoul** [comment]
Yeah I think I'll just use `xautolock`. Too bad I can't leverage on what's already on my system. Thanks!
