### ISSUE TITLE
Picom displays black lines under windows when blur effect is enabled

### ISSUE THREAD

**Issue by Monsterovich** [yshui/picom#587]
### Platform
Linux Mint 20.1

### GPU, drivers, and screen setup
```
name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) HD Graphics 520 (SKL GT2) (0x1916)
    Version: 20.3.4
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 520 (SKL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.3.4 - kisak-mesa PPA
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.3.4 - kisak-mesa PPA
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.3.4 - kisak-mesa PPA
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment
Xfce 4.14

### picom version
master

### Configuration:
https://pastebin.com/mXXUCG2V

### Steps of reproduction

Run picom

### Expected behavior

No graphical artifacts.

### Current Behavior

See video below.

https://user-images.githubusercontent.com/3750982/106625039-f4aa0580-657e-11eb-8154-8a4eed71413c.mp4

### Other details

This bug doesn't appear when --experimental-backends flag is used.

**Comment by tryone144** [comment]
The legacy backends tend to produce these artifacts behind blurred backgrounds when `use-damage = true;` is set (see https://github.com/yshui/picom/issues/50).
IIRC, this is a design problem and fixed in the new experimental backends (with `--experimental-backends`) as you've already found out.
