### ISSUE TITLE
frame-opacity does not make entire frame transparent

### ISSUE THREAD

**Issue by branden-akana** [yshui/picom#590]
### Platform
Arch Linux 5.10.11 x86_64

### GPU, drivers, and screen setup
NVidia GeForce RTX 3070, driver version 460.39, dual-monitor setup w/ `xrandr`
```
$ glxinfo -B

name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8192 MB
    Total available memory: 8192 MB
    Currently available dedicated video memory: 7718 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce RTX 3070/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 460.39
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 460.39
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 460.39
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment
WM: openbox
no DM

### picom version
vgit-3680d

### Configuration:
```
# General Settings

backend = "glx";
use-damage = true;
# vsync = true;
xrender-sync-fence = true;
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
detect-transient = true;
detect-client-leader = true;
unredir-if-possible = true;
glx-no-rebind-pixmap = true;

corner-radius = 4;
rounded-corners-exclude = [
#	"class_g != 'Termite'",
	"class_i = 'tint2'"
];
shadow = false;

# Opacity Settings

inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 0.8;
inactive-opacity-override = false;
detect-client-opacity = true;
opacity-rule = [
	"80:class_g = 'Termite'",
];

# Fade Settings

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-exclude = [ ];
focus-exclude = [ "class_g = 'Cairo-clock'" ];

# Blur Settings

blur: {
	method = "dual_kawase";
	#method = "dual_kawase";
	strength = 9;
};
blur-background-fixed = false;
blur-background-exclude = [
	"window_type = 'desktop'",
	"class_i = 'tint2'"
];
blur-background = true;
blur-background-frame = true;

```

### Steps of reproduction
1. Use an Openbox theme that has window borders (set `border-width = >0` in the theme's `themerc`)
2. Set `frame-opacity` to any number <1 in `~/.config/picom.conf`

### Expected behavior
The entire frame should be transparent according to the value of `frame-opacity`.

### Current Behavior
The frame becomes transparent except for the bottom and right borders.

### Other details
`frame-opacity = 1`
![](https://i.imgur.com/Xg79NA9.png)

`frame-opacity = 0.8`
![](https://i.imgur.com/rBOqxej.png)

`frame-opacity = 0`
![](https://i.imgur.com/Sfm7ByO.png)

Using `inactive-opacity` or `inactive-opacity` does make the frame transparent correctly, but I'd prefer if I didn't have to make the entire window transparent.

Initially I thought this was some kind of bevel effect but there doesn't seem to be any option like that in Openbox, and I don't think it's a GTK issue either because I see this issue on Discord, Spotify, etc.

Any help with this would be appreciated.

**Comment by mighty9245** [comment]
the entire frame is transparent. the problem is that it's misplaced (take a careful look at the last screenshot and see blurred lines on your wallpaper). are you using experimental backends? anyway, try the same thing with and without `--experimental-backends` flag.

**Comment by branden-akana** [comment]
> the entire frame is transparent. the problem is that it's misplaced (take a careful look at the last screenshot and see blurred lines on your wallpaper). are you using experimental backends? anyway, try the same thing with and without `--experimental-backends` flag.

The problem occured with and without `--experimental-backends`.

Apparently I "accidentally" fixed this problem by changing how I start Openbox in my `~/.xinitrc` from
```
exec openbox-session
```
to
```
exec dbus-launch openbox-session
```
which I had to do to fix an entirely separate issue I was having with another program. So the frame transparency not looking correct might be the result of my dbus session bus not running.

Anyway I'll close this unless someone else thinks this is still a notable issue.

Thanks

**Comment by mighty9245** [comment]
i think it's a notable issue and it should be reopened, tracked down and fixed.

**Comment by tryone144** [comment]
This seems to be the same underlying problem as in https://github.com/yshui/picom/issues/413

However, interesting that this can be fixed for you by running in a dbus session.
