### ISSUE TITLE
the daemon option in config has no effect

### ISSUE THREAD

**Issue by tleydxdy** [yshui/picom#621]
### Platform

Artix Linux

### GPU, drivers, and screen setup

Intel/laptop monitor

### Environment

dwm

### picom version

vgit-dac85

### Configuration:
```
daemon = true;
vsync = true;
log-level = "warn";
```

### Steps of reproduction

1. install picom from arch repo
2. create the config as above
3. run picom in terminal
4. it does not fork to background
5. run picom -b in terminal
6. it does fork to background
7. change log-level to info
8. run picom in terminal
9. log-level changed to info, showing that the config is loaded

**Comment by yshui** [comment]
`daemon` isn't a configuration file option, i will update the man page to make it clearer.
