### ISSUE TITLE
Rounded corners do nothing

### ISSUE THREAD

**Issue by victorbnl** [yshui/picom#622]
### Platform

Arch Linux

### GPU, drivers, and screen setup

NVIDIA GTX 1050 Ti

`xf86-video-vesa 2.5.0-1`

<details>
<summary>glxinfo -B</summary>

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) UHD Graphics 630 (CFL GT2) (0x3e9b)
    Version: 21.0.3
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics 630 (CFL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.0.3
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.0.3
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

</details>

### Environment

i3-gaps

### picom version

```
$ picom --version
vgit-dac85
```

### Configuration:

```
corner-radius = 30;
```

<details>
<summary>Full config</summary>

```
# Shadows
shadow = true;
shadow-radius = 20;
shadow-opacity = 1;
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-exclude = [
	"name = 'Notification'",
	"class_g = 'Polybar'",
	"class_g ?= 'Notify-osd'",
	"class_g = 'Cairo-clock'",
	"_GTK_FRAME_EXTENTS@:c"
];

# Opacity
inactive-opacity = 1;
frame-opacity = 1;
active-opacity = 1;
inactive-dim = 0;

# Rounded corners
corner-radius = 30;
```

</details>

### Steps of reproduction

1. Install picom from the arch community repo
2. Set a corner-radius

### Expected behavior

Corners of windows are rounded

### Current Behavior

Nothing happens

### Stack trace

It doesn't crash

### Other details

![image](https://user-images.githubusercontent.com/39555268/116811455-b73b2100-ab49-11eb-9da6-3fb768b75def.png)

Sorry if this issue already exists, I searched in the current issues I promise, but there are many x)

**Comment by amirhossein-ka** [comment]
i thing you should use another fork of picom
i use [this fork](https://github.com/ibhagwan/picom) and it's working well!

**Comment by victorbnl** [comment]
I'll try thanks, even though that's not resolving the issue on this version, it could be a great reference to fix it!

**Comment by fiplox** [comment]
Same problem here on Arch dwm. Using same version of picom.

**Comment by amirhossein-ka** [comment]
or also you can get picom-git for rounded corners 😅
see [this](https://github.com/polybar/polybar/pull/2359) (:

**Comment by fiplox** [comment]
right, so picom in the arch community repo is a version from October 2020, that's why. The git version works as expected ! :)

**Comment by victorbnl** [comment]
It works with picom-git too, thanks
