### ISSUE TITLE
How to enable window preview on task switcher?

### ISSUE THREAD

**Issue by ferwasy** [yshui/picom#646]
I've started using picom on XFCE for solving an issue regarding Firefox 88 (I was unable to make it work with XFCE default compositor). It is working fine, but something that I lost is window previews when clicking Alt+Tab. I didn't find any reference on how to enable them, that is why I ask here.
Thanks in advance!

**Comment by tryone144** [comment]
Window previews are bound to the built-in compositor of xfwm (see the *Show windows preview in place of icons when cycling* option in the compositor settings).
This isn't something picom has control over. To get this feature to work with different compositors would require changes in xfwm to detect the presence of an external compositor. For anyone interested, [here](https://gitlab.xfce.org/xfce/xfwm4/-/blob/master/src/tabwin.c#L658) might be a good place to start diving into the code.
