### ISSUE TITLE
dbus setting isn't supported in config

### ISSUE THREAD

**Issue by kurnevsky** [yshui/picom#669]
It seems `dbus` can be enabled only via command line argument, so this setting is misleading: https://github.com/yshui/picom/blob/24b445072664378186c6a408b816179e0181bc01/picom.sample.conf#L220

**Comment by kurnevsky** [comment]
As well as `glx-fshader-win`.

**Comment by absolutelynothelix** [comment]
better late than never, so
1) the `dbus` option is available from the configuration file starting from de434f7b1fa7170442c3c050c199bdffea1da12d;
2) the `glx-fshader-win` is not available from the configuration file and is not mentioned in the sample configuration file.

**Comment by yshui** [comment]
yeah, so `dbus` has been made available, `glx-fshader-win` is replaced by `window-shader-fg` which is available in config.

closing as fixed!
