### ISSUE TITLE
Picom Segfaults on Startup.

### ISSUE THREAD

**Issue by klay2000** [yshui/picom#682]
### Platform
Arch Linux

### GPU, drivers, and screen setup
nvida 5400m, nvidia-390xx drivers on aur, single laptop screen

### Environment
qtile 0.18.1

### picom version
vgit-ee7d9

<details>
<summary>Diagnostics</summary>
diagnostics output:
Segmentation fault (core dumped)
</details>

### Configuration:
<details>
    <summary>Configuration file</summary>
    default config
</details>

### Steps of reproduction
Run Picom from terminal

### Expected behavior
Picom runs

### Current Behavior
Picom segfaults

### Stack trace
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7386e56 in ?? () from /usr/lib/libGLX_indirect.so.0

**Comment by TheoCGaming** [comment]
Did you run the git version?

**Comment by klay2000** [comment]
Yep, sorry, forgot to close this. I installed it again a few weeks later and it worked.
