### ISSUE TITLE
Animations Support  (I know I know)

### ISSUE THREAD

**Issue by pijulius** [yshui/picom#688]
Hi Guys,

First of all thanks for the hard work on this, really appreciated!!!

I know there is another case related on this on a picom fork but I would like to start it here as this version is the original and most up-to-date version so would be great to have it implemented here. Also know that this may not be to everyone's taste as not everyone agrees to have this functionality in a compositor but I do think it would be a great addition and could be left inactivated by default and just use the config to activate for those who would want it.

Now, re the animations, I found this nice xcompmgr fork (bare version) and tried it out and it perfectly does Pop Up/Down and Slide Up/Down animations:
https://github.com/mpostaire/axcomp

Quickly looked around in the code but wasn't that easy (at least for me) to bring it over to here so would like to ask if someone who has better knowledge in this to take a look on it and maybe port it over? 

Popup and down animations look great for opening and closing windows also the slide down/up would be great for modal dialogs with transient status or menus so really hope there is a possibility to port it over.

I'm ready to chip in on both sides, getting some work done/testing and a reward of $100.

Thank you guys in advance!
Julius

**Comment by phisch** [comment]
There is a full issue about the topic already: https://github.com/yshui/picom/issues/217
The most promising picom fork working on animations is this one: https://github.com/dccsillag/picom/
Help that guy out, give him constructive feedback, test his stuff, fix bugs in his fork, contribute over there, so it can be implemented as good as possible and be merged back into picom.

Also might want to close this issue in favor of the other one.

**Comment by pijulius** [comment]
Oooo yes, you are right, totally missed that fork/case. Only found the one where they added real window animation (meaning resizing the windows in real time instead of scaling a screenshot of the window) and that's why I thought it would be worth a new case but the #217 is exactly what I was looking for.

So thanks again, will close this case now and play around with that fork :)
