### ISSUE TITLE
it has this when i open it type picom in the terminal 

### ISSUE THREAD

**Issue by gitdrug** [yshui/picom#700]
austin@Lenovo-xubuntu-laptop:~\λ picom
[ 09/24/2021 17:35:15.598 open_config_file_at WARN ] This compositor has been renamed to "picom", the old config file paths is deprecated. Please replace the "compton"s in the path with "picom"
[ 09/24/2021 17:35:15.599 parse_config_libconfig ERROR ] Option `no-dock-shadow` has been removed. Please use the wintype option `shadow` of `dock` instead.
[ 09/24/2021 17:35:15.599 main FATAL ERROR ] Failed to create new session.

**Comment by tryone144** [comment]
Picom is using your (old) configuration file for compton. As the error message states, the `no-dock-shadow` option has been removed from picom. Remove it from your config file and replace it with the `wintype` option you find in the [sample config](https://github.com/yshui/picom/blob/ad18d129cc549e4e00a0499df7de87f249a3a71f/picom.sample.conf#L415).

If you intend to continue using compton, it might be better to copy the configuration file to the new location (renaming it to `picom.conf` should be sufficient).
