### ISSUE TITLE
`inactive-opacity` and `frame-opacity` set to `0.7` in the default config

### ISSUE THREAD

**Issue by aakodadi** [yshui/picom#702]
In [`picom.sample.conf`](https://github.com/yshui/picom/blob/next/picom.sample.conf) the comments say that [`inactive-opacity`](https://github.com/yshui/picom/blob/ad18d129cc549e4e00a0499df7de87f249a3a71f/picom.sample.conf#L104) defaults to `1.0` and [`frame-opacity`](https://github.com/yshui/picom/blob/ad18d129cc549e4e00a0499df7de87f249a3a71f/picom.sample.conf#L108) is disabled by default. But then they are set to `0.7` a few lines below.

Although I understand that default value in this context means the hard-coded value used when the setting is absent, I still think that it is counterintuitive. I also think that (this is maybe more of a subjective opinion) fancy graphics effects should be disabled by default, and it's up to the user to enable them if they feel like it.

**Comment by yshui** [comment]
the sample config is a sample, not the default value. and it's supposed to be change if you don't like the looks. i am inclined to say this is not a problem.
