### ISSUE TITLE
rounded corner not working with experimental backend

### ISSUE THREAD

**Issue by skydie22** [yshui/picom#722]
can you make rounded corner support with experimental backend ? thanks

**Comment by dybdeskarphet** [comment]
rounded corners is not a picom feature, it's its forks' feature.

**Comment by yshui** [comment]
@dybdeskarphet rounded corners has already been merged.

@skydie22 Yes, we are working on getting it to work with the new backends, see #716 #658. Also this is duplicate of #622

**Comment by dybdeskarphet** [comment]
oh sorry, my bad

**Comment by skydie22** [comment]
thanks
