### ISSUE TITLE
plank broken with blur background

### ISSUE THREAD

**Issue by skydie22** [yshui/picom#727]
![Screenshot_2021-11-09_10-34-51](https://user-images.githubusercontent.com/73593413/140857492-c788e450-9efc-4631-9222-0b774cd02d6b.png)

I want to use a blur background on the plank but when I apply it it looks like in the picture

this is my configuration

#################################
#     Background-Blurring       #
#################################

Parameters for background blurring, see the *BLUR* section for more information.
 blur-method =
 blur-size = 12

blur-deviation = false
blur-background = true;
blur-background-fixed = false

blur-kern = "3x3box";
blur-method = "dual_kawase";
blur-strength = 5;

blur-background-exclude = [
    "! name~=''",
    "name   *= 'jgmenu'",
    "name   *= 'polybar'",
    #"name   *= 'rofi'",
    "name *= 'Chromium'",
    "name *= 'Chrome'",
    "class_g = 'conky'",
    "class_g = 'GLava'",
    "class_g = 'slop'",
    #"window_type = 'dock'",
    "window_type = 'desktop'",
    "_GTK_FRAME_EXTENTS@:c",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];

**Comment by NeoFax75** [comment]
I have the same problem with the newest 202408 build of picom. I am not sure it is a picom problem or how plank is designed though.

**Comment by yshui** [comment]
This is because plank doesn't provide shape information about its window. picom blurs the whole background of the window, plank has large parts of its window completely transparent, and that's what you are seeing. 

you can disable blur for plank specifically.
