### ISSUE TITLE
Blocking mouse input

### ISSUE THREAD

**Issue by ZorionTen** [yshui/picom#743]
Using it with Awesome Window Manager and Plank 

Plank has a thicc invisible border around it that blocks clicks. cant interract with overlapping parts of the windows. The limits of tha border can be seen by including plank for drawing shadows. Killing Plank OR picom removes the border

picom.conf

```
backend ="glx";
glx-no-stencil = true;
glx-copy-from-front = false;
glx-swap-method = "undefined";
active-opacity = 10;
frame-opacity = 0.8;
inactive-opacity-override = false;
blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;
blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'"
];
blur-kern = "3x3box";
blur-method = "kawase";
blur-strength = 5;
opacity-rule = [
  "90:class_g = 'urxvt'"
];

corner-radius = 10;

shadow = true;
shadow-radius = 60;
shadow-opacity = 0.5;
shadow-offset-x = -60;
shadow-offset-y = -25;

rounded-corners-exclude= [
	"class_g = 'Plank'",
	"class_g = 'awesome'"
];

blur-exclude = [
    "class_g = 'Plank'",
    "class_g = 'Ulauncher'"
];
fade-exclude = [
    "class_g = 'Plank'"
];
shadow-exclude = [
    "class_g = 'Plank'"
];
shadow-ignore-shaped = false;
```

**Comment by akdevservices** [comment]
The same problem.

**Comment by yshui** [comment]
if starting picom causes plank to change the size/shape of its window, it's probably a bug in plank.

**Comment by M3CHR0M4NC3R** [comment]
I can confirm this happens with cairo as well, I doubt it's specific to the dock.

**Comment by yshui** [comment]
picom does not change the actual size or shape of a window, nor the region a window receives input. please report this to the respective application instead of picom
