### ISSUE TITLE
Changes to the compton-desfault-win-shader.glsl does nothing ?

### ISSUE THREAD

**Issue by Root-voidX** [yshui/picom#749]
Hello, So i wanted to edit the above file to change the way invert-color inverts to preserve hue, but any changes to the file doesn't effect it. Is there another copy elsewhere I should be looking in my system? Also I assume changes to this won't effect me if I use xrandir ? 

Any help is appreciated!

**Comment by tryone144** [comment]
This file is not actually read by picom. It only contains an example window shader to be used with `--glx-fshader-win` option. This option takes a shader string as the parameter (i.e. the contents of said file).

```console
$ picom --glx-fshader-win "$(cat compton-default-fshader-win.glsl)"
```

**Comment by Root-voidX** [comment]
> This file is not actually read by picom. It only contains an example window shader to be used with `--glx-fshader-win` option. This option takes a shader string as the parameter (i.e. the contents of said file).
> 
> ```
> $ picom --glx-fshader-win "$(cat compton-default-fshader-win.glsl)"
> ```

Ahh thanks, Now it reads the changes =)

**Comment by absolutelynothelix** [comment]
closing as resolved.
