### ISSUE TITLE
segfault after failing to bind root pixmap (w/ `--experimental-backends`)

### ISSUE THREAD

**Issue by sharnoff** [yshui/picom#767]
Environment: arch linux, 5.16.2-arch1-1; xorg w/ GLX backend. `--version` is `vgit-dac85`.

Relevant errors (these occur at the same time):
```
failed to create drawable
[ 01/23/2022 16:02:27.424 glx_bind_pixmap ERROR ] Failed to create glpixmap for pixmap 0x04c00001
```

---

When the picom fails to bind the root pixmap, it segfaults.

I'm not sure the particular reasons why it fails, but it appears to happen frequently _sometimes_ -- I was able to get a backtrace with a debug build & found the culprit:

```
(gdb) bt
#0  0x0000557ba53d9e81 in default_set_image_property (base=0x557ba5f9d580, op=IMAGE_PROPERTY_EFFECTIVE_SIZE, 
    image_data=0x0, arg=0x7ffd44a2f6c0) at ../src/backend/backend_common.c:449
#1  0x0000557ba539e0a8 in root_damaged (ps=0x557ba5f71510) at ../src/picom.c:901
#2  0x0000557ba53c646d in ev_property_notify (ps=0x557ba5f71510, ev=0x557ba67b9290) at ../src/event.c:458
#3  0x0000557ba53c71ce in ev_handle (ps=0x557ba5f71510, ev=0x557ba67b9290) at ../src/event.c:725
#4  0x0000557ba53a06bf in x_event_callback (loop=0x7f0b752a0720, w=0x557ba5f71510, revents=1) at ../src/picom.c:1621
#5  0x00007f0b75294033 in ev_invoke_pending () from /usr/lib/libev.so.4
#6  0x00007f0b75297902 in ev_run () from /usr/lib/libev.so.4
#7  0x0000557ba53a38b5 in session_run (ps=0x557ba5f71510) at ../src/picom.c:2445
#8  0x0000557ba53a3bc6 in main (argc=2, argv=0x7ffd44a2fae8) at ../src/picom.c:2547
```

Here's what the relevant section of `root_damaged` looks like:

https://github.com/yshui/picom/blob/aa57d3f64ae962782c56c8aa6e94cf4491de1488/src/picom.c#L893-L905

The call to `bind_pixmap` fails here, returning a null pointer.

https://github.com/yshui/picom/blob/aa57d3f64ae962782c56c8aa6e94cf4491de1488/src/backend/gl/glx.c#L432-L435

...

https://github.com/yshui/picom/blob/aa57d3f64ae962782c56c8aa6e94cf4491de1488/src/backend/gl/glx.c#L453-L463

That null pointer (`ps->root_image`) is then dereferenced in the call to `set_image_property`:

https://github.com/yshui/picom/blob/aa57d3f64ae962782c56c8aa6e94cf4491de1488/src/backend/backend_common.c#L437-L449

The segfault itself occurs on line 449, with `tex = 0x00` (because `image_data = ps->root_image`).

I'm not sure what the correct error handling should be here -- I took a peek at how failing to bind a pixmap is handled elsewhere, and I assumed that we probably can't just use `WIN_FLAGS_IMAGE_ERROR`, as is done elsewhere:

https://github.com/yshui/picom/blob/aa57d3f64ae962782c56c8aa6e94cf4491de1488/src/win.c#L329-L335

Anyways, let me know if there's any other information you want - always happy to peek back through the system logs.

The debug builds were with the current commit (aa57d3f64ae962782c56c8aa6e94cf4491de1488) but I accidentally lost their logs (writing to stderr, didn't store it), and the bind failures have since stopped. The error message at the very top is from my system binary, which is obviously a different commit -- the failures occur with both though.

**Comment by yshui** [comment]
Thanks for reporting. I am not sure why creation of glxpixmap failed, but at least I can fix the error handling side.

**Comment by sharnoff** [comment]
Awesome, thanks!
