### ISSUE TITLE
Rounded corners show strange aliasing (in Firefox, only on some tabs)

### ISSUE THREAD

**Issue by frebib** [yshui/picom#770]
### Platform
Arch Linux, i3, picom-git from the AUR

### GPU, drivers, and screen setup
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) UHD Graphics 630 (CFL GT2) (0x3e9b)
    Version: 21.3.4
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics 630 (CFL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.3.4
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.3.4
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.3.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment
i3-gaps

### picom version
`vgit-3b9af`

<details>
<summary>Diagnostics</summary>
[ 28/01/22 10:33:04.075 get_cfg WARN ] Dual-kawase blur is not implemented by the legacy backends, you must use the `experimental-backends` option.
[ 28/01/22 10:33:04.160 init_render WARN ] Old backends only support blur method "kernel". Your blur setting will not be applied
**Version:** vgit-3b9af

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/frebib/.config/picom/picom.conf

### Drivers (inaccurate):

Intel

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Intel
* GL renderer: Mesa Intel(R) UHD Graphics 630 (CFL GT2)
* Accelerated: 1
</details>

### Configuration:
https://gist.githubusercontent.com/frebib/bc9ea031e6cb982d0937e40e76b24f37/raw

### Steps of reproduction

1. Set `corner-radius` to some non-zero value
2. Notice some tabs in Firefox (I didn't test other software extensively) show aliasing on the corners sometimes.

### Expected behavior

1. No aliasing

(Also the shadows don't conform to the corners, but that's another issue entirely.)

### Current Behavior

![image](https://user-images.githubusercontent.com/775104/151531687-ccd4c03e-1d68-4c96-a2da-0293ee317e15.png)

**Comment by Wolfdesroyer8** [comment]
This fork of picom fixes those issues https://github.com/Arian8j2/picom-jonaburg-fix
Its also in the aur under ``picom-jonaburg-fix``

**Comment by yshui** [comment]
@frebib I am thinking this might be picom trying to draw a border around the corners.

Can you run `xprop` on the window?

**Comment by frebib** [comment]
```
$ xprop
_NET_WM_USER_TIME(CARDINAL) = 181397368
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 1864, 990
GDK_TIMESTAMP_PROP(GDK_TIMESTAMP_PROP) = 0x61
_NET_WM_DESKTOP(CARDINAL) = 3
_NET_WM_STATE(ATOM) =
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x6400030
		bitmap id # of mask for icon: 0x6400037
		window id # of group leader: 0x6400001
_GTK_THEME_VARIANT(UTF8_STRING) = "dark"
WM_WINDOW_ROLE(STRING) = "browser"
XdndAware(ATOM) = BITMAP
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 104857646, 104857647
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x640002d
WM_CLIENT_LEADER(WINDOW): window id # 0x6400001
_NET_WM_PID(CARDINAL) = 555414
WM_LOCALE_NAME(STRING) = "en_GB.UTF-8"
WM_CLIENT_MACHINE(STRING) = "frebib-Cf"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 450 by 120
		program specified maximum size: 16384 by 16384
		program specified base size: 450 by 120
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "Navigator", "firefox"
WM_ICON_NAME(COMPOUND_TEXT) = "Inbox - Google Mail — Mozilla Firefox"
_NET_WM_ICON_NAME(UTF8_STRING) = "Inbox - Google Mail — Mozilla Firefox"
WM_NAME(COMPOUND_TEXT) = "Inbox - Google Mail — Mozilla Firefox"
_NET_WM_NAME(UTF8_STRING) = "Inbox - Google Mail — Mozilla Firefox"

```

**Comment by yshui** [comment]
Can you run `xwininfo` as well? thanks.

**Comment by frebib** [comment]
```
xwininfo: Window id: 0x640002c "Inbox - Google Mail — Mozilla Firefox"

  Absolute upper-left X:  28
  Absolute upper-left Y:  1108
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 1864
  Height: 990
  Depth: 32
  Visual: 0x331
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x640002b (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +28+1108  -1948+1108  -1948-62  +28-62
  -geometry 1864x990+28-62

```

**Comment by yshui** [comment]
Hmm it has nothing to do with border then. Does this happen on all corners or just the corner shown? Also are you using `--experimental-backends`?

**Comment by frebib** [comment]
Yep
```
# /home/frebib/.config/systemd/user/picom.service
[Unit]
Description=A lightweight compositor for X11
Requires=graphical-session.target
After=dbus.service graphical-session.target xorg.target

[Service]
ExecStart=/usr/bin/picom --experimental-backends --dbus
Restart=always
Slice=session.slice

[Install]
WantedBy=desktop.target
```
Config attached in the OP

**Comment by frebib** [comment]
Actually I just noticed it in this terminal window, except it's the inverse of black not white:
![image](https://user-images.githubusercontent.com/775104/153197095-689fe67f-c513-4c9a-b5bb-85e82ef967b1.png)

I wonder if this is some miscalculation in the anti-aliasing?

**Comment by yshui** [comment]
Hmm, can you get a trace of picom with apitrace?

**Comment by yshui** [comment]
I still think it has something to do with borders, maybe the border width calculation is wrong somehow.

**Comment by tryone144** [comment]
If this is a related to the rounded border, there is probably a problem in the way we get the border color (bottom left corner iirc). It seems to be affected by the website background color in firefox, as you mention.
Does this artifact appear on all four corners of the window?

**Comment by oncomouse** [comment]
I'm having this problem, too. Similar setup as OP (picom-git but awesome instead of i3).

I do see the artifact on all four corners.

I also noticed that the problem goes away if I turn off `--experimental-backends`.

**Comment by yshui** [comment]
@oncomouse can you get a trace with `apitrace`?

**Comment by frebib** [comment]
`apitrace trace /usr/bin/picom --experimental-backends`
I kinda guessed. Should I do something else? Happy to do it again.
It also segfaulted when I `^C` at the end, amusingly

**Comment by yshui** [comment]
Can you upload the `picom.trace` file generated in the directory you ran the command?

**Comment by frebib** [comment]
[picom.1.trace.gz](https://github.com/yshui/picom/files/8055355/picom.1.trace.gz)
gzipped so github actually accepts it

**Comment by yshui** [comment]
OK, I think I understand it now.

**Comment by yshui** [comment]
Should've been fixed. Can you test?

**Comment by frebib** [comment]
Yeah, looks much better! Thanks

**Comment by noctuid** [comment]
@frebib It still looks wrong in your screenshot though. I still see the same problem on all windows on the latest commit (only with `--experimental-backends`).

**Comment by yshui** [comment]
@noctuid what looks wrong? if you are talking about the shadow doesn't adhere to the corner then it's a different problem.

**Comment by BachoSeven** [comment]
> @noctuid what looks wrong? if you are talking about the shadow doesn't adhere to the corner then it's a different problem.

Is there an issue currently tracking that behaviour of the blur method not respecting the corners' radius?

**Comment by noctuid** [comment]
Yes, that's what I meant. I opened a separate issue to track it.

@BachoSeven See #775
