### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by j0ker70** [yshui/picom#773]
### Platform
Ubuntu 20.04

Trying to install picom.

But ```ninja -C build install``` isn't running.

```
➜ ninja -C build install
ninja: Entering directory `build'
[0/1] Installing files.
Installing src/picom to /usr/local/bin
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...
==== AUTHENTICATING FOR com.mesonbuild.install.run ===
Authentication is required to install this project
Authenticating as: pial,,, (pial)
Password:
polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie
==== AUTHENTICATION FAILED ===
Error executing command as another user: Not authorized

This incident has been reported.
FAILED: meson-install
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

I have installed all the dependencies before.

**Comment by tryone144** [comment]
Your normal user most likely does not have the needed permissions to install picom into `/usr/local/bin`.
You might want to run `ninja -C build install` with elevated privileges, i.e. as `root` with `sudo ...`.

The polkit error above has nothing to do with picom and is probably related to your specific system configuration with tries to gain the missing privileges automatically.

**Comment by j0ker70** [comment]
That worked. Thank you.

**Comment by z0xyz** [comment]
I've ran into the same issue, and prefixing `ninja -C build install` with `sudo` resulted in the same error. Altering the installation path to the alternate writable path `~/.local` resolved it.
