### ISSUE TITLE
Shadows do not respect rounded corners

### ISSUE THREAD

**Issue by noctuid** [yshui/picom#783]
In #770, yes I was talking about how the shadow is still as if there are not rounded corners with `--experimental-backends`:

![2022-02-14T19:44:32_-_picomconf](https://user-images.githubusercontent.com/4250696/153971473-e6d3db1b-11e4-48b5-8b06-b576a68b7ae5.png)

**Comment by wimstefan** [comment]
I can confirm the same behaviour with latest git commit.

#### Platform
Gentoo ~amd64

#### GPU, drivers, and screen setup
<details><summary>glxinfo -B</summary>
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 6144 MB
    Total available memory: 6144 MB
    Currently available dedicated video memory: 3947 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 510.54
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 510.54
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 510.54
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
</details>

#### picom details
<details><summary>Diagnostics</summary>
**Version:** vgit-aa316

##### Extensions:
* Shape: Yes
* XRandR: Yes
* Present: Present

##### Misc:
* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/swimmer/.config/picom/picom.conf

##### Drivers (inaccurate):
NVIDIA

##### Backend: glx
* Driver vendors:
 * GLX: NVIDIA Corporation
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
</details>

<details><summary>Configuration</summary>

backend = "glx";
vsync = true;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
detect-transient = true;
detect-client-leader = true;
xrender-sync-fence = true;
use-ewmh-active-win = true;
log-level = "warn";

shadow = true;
shadow-radius = 24;
shadow-opacity = 0.80
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-exclude = [
  "class_g = 'scribus'"
];

corner-radius = 24;
detect-rounded-corners = true;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "class_g = 'Polybar'",
  "class_g = 'Mixxx'",
];

fading = true;
fade-in-step = 0.80;
fade-out-step = 0.80;
fade-delta = 10

active-opacity = 0.90;
inactive-opacity = 0.90;
inactive-dim = 0.20;
transparent-clipping = true;
detect-client-opacity = true;
focus-exclude = [
  "class_g = 'Gimp'",
  "class_g = 'scribus'",
  "class_g = 'Rofi'",
  "name = 'Calendar'"
]

blur-method = "dual_kawase";
blur-strength = 4;
blur-background-exclude = [
  "class_g = 'scribus'",
];

wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 1.0; focus = true; full-shadow = true; };
  dock = { shadow = true; full-shadow = false; clip-shadow-above = true; }
  dnd = { shadow = false; }
  notification = { full-shadow = true; }
  popup_menu = { opacity = 0.8; }
  dropdown_menu = { opacity = 0.8; }
};
</details>

**Comment by jarrard** [comment]
Think this could similar to my issue posted here https://github.com/yshui/picom/issues/794

**Comment by akshat157** [comment]
I am facing the same issue on Arch Linux with AwesomeWM.

The issue as been discussed here at https://github.com/jonaburg/picom/issues/62 as well.

And there is a mention of a commit by @s0nny7 in yet another picom fork which apparently solves the problem -
https://github.com/ibhagwan/picom/pull/34/commits/d74c099083487783af7254cb55780ffb20100e53

I have tried the [patched fork](https://github.com/Arian8j2/picom-jonaburg-fix) by @Arian8j2 mentioned in the former discussion but it did not work for me.

Perhaps, if someone can take inspiration from the mentioned commit and write a solution for this fork, it would be great!

**Comment by elinostro** [comment]
I have the same issue as @akshat157 I just compiled @Arian8j2 fork but corner shadows issue remains. 

In [this](https://githubmemory.com/index.php/repo/jonaburg/picom/issues/62) post some one mentioned ibhagwan's [fork](https://github.com/ibhagwan/picom) works if the @Arian8j2's fork doesn't, but it only have Archilinux and Void Linux support to compile [sad emoji here].

**Comment by aleksfadini** [comment]
I have the same issue, had to revert to jonaburg fork because rounded borders + shadows essentially do not work with picom

**Comment by SaphiraKai** [comment]
The original commit that fixes this problem is [here](https://github.com/s0nny7/picom/commit/d74c099083487783af7254cb55780ffb20100e53).

I would modify it and make a PR myself, but unfortunately I'm just not familiar at all with the picom codebase. It would be excellent if someone with more knowledge could take a look at this and make an implementation for this fork!

**Comment by jarrard** [comment]
I had a crack at it. Here is what I came up with. This isn't a patch but a replacement backend.c file. 

[backend.c.rounded.txt](https://github.com/yshui/picom/files/8693879/backend.c.rounded.txt)

**Comment by SaphiraKai** [comment]
What branch is that file for? I tried plunking it into the `next` branch, but I got a bunch of `undeclared` errors for:
- `store_back_texture`
- `backend_round_context`
- `reg_bound_local`

**Comment by jarrard** [comment]
Yeah probably need change those variables.. Sorry busy until late tomorrow, can't look now.

**Comment by jarrard** [comment]
Ok well the below segment of code probably can be deleted as I think picom has a new way of storing and handling this. And I brought it over from the original as it seemed important to rounded corners.

Remove this below and test again, see what happens. LOL

`
		// Store the window background for rounded corners
		// If rounded corners backup the region first
		if (w->corner_radius > 0) {
			const int16_t x = w->g.x;
			const int16_t y = w->g.y;
			const auto wid = to_u16_checked(w->widthb);
			const auto hei = to_u16_checked(w->heightb);
			ps->backend_data->ops->store_back_texture(ps->backend_data, w,
							ps->backend_round_context, &reg_bound, x, y, wid, hei);
		}
`

**Comment by SaphiraKai** [comment]
No dice. Still have this error during compilation:
```
../src/backend/backend.c: In function ‘paint_all_new’:
../src/backend/backend.c:468:47: error: ‘reg_bound_local’ undeclared (first use in this function)
  468 |                         pixman_region32_fini(&reg_bound_local);
      |                                               ^~~~~~~~~~~~~~~
```w

**Comment by jarrard** [comment]
Yeah so basically its saying we have not declared what reg_bound_local is since its been removed in recent picom. 

Will need to sift through the code to find a substitute function. Feel free to make suggestions, I'm just poking at things in the dark here.

**Comment by fuegoio** [comment]
@SaphiraKai I just created a PR inspired by the commit you linked to. It works on my setup, could you check it works on your too ?
