### ISSUE TITLE
Feauture request automatic restart

### ISSUE THREAD

**Issue by Scorpion2185** [yshui/picom#791]
Is there a way to restart `picom`?

After you save the `picom.conf` file it could automatically restart.

Or a restart option `picom --restart`.
AFAIK there isn't a way.

**Comment by yshui** [comment]
> After you save the picom.conf file it could automatically restart.

picom already does.

**Comment by Scorpion2185** [comment]
Ah yes I can see the shadows restarting but some times changes don't apply.
