### ISSUE TITLE
Lag in glx backend

### ISSUE THREAD

**Issue by yshui** [yshui/picom#8]
### Platform

ArchLinux

### GPU, drivers, and screen setup

GTX 1060, single monitor

### Compton version

v1-57-g97cd342

### Compton configuration:

Reproducible with /dev/null

### Steps of reproduction

1. Start compton `--config /dev/null --backend glx`
2. Move a transparent window around

### Current Behavior

Xorg CPU usage shots up, and there is visible lag.

### Other details

Xrender doesn't seem to have the lag, although Xorg is still using a lot of CPU in Xrender backend.

**Comment by tryone144** [comment]
I cannot reproduce the lag on my Arch laptop with integrated *Intel HD Graphics 5500*. Although Xorg CPU usage is still rising (from about 1% to about 12%) when moving a transparent window.
IIRC, my desktop Arch with the proprietary Nvidia driver has a similar problem, but I can't test that now.
I guess, this might be related to the nvidia driver and pixmap copy of the transparent window background.

Tested with compton `v4-rc4` and `compton --config /dev/null --backend glx`.

**Comment by yshui** [comment]
can't reproduce anymore
