### ISSUE TITLE
Applications with Transparency/Opacity not rendered as such.

### ISSUE THREAD

**Issue by nPHYN1T3** [yshui/picom#802]
### Platform
Garuda Linux [Arch] (XFCE - without the XFCE)

### GPU, drivers, and screen setup
nVidia 510.54 running GTX 1660 & GTX 1060
3 XScreens with 8 monitors

### Environment
This started as Garuda XFCE but since anything GTK is now broken by design for multi XScreen/GPU I removed the XFCE and have been building around CTWM.

### picom version
vgit-7e568

<details>
<summary>Diagnostics</summary>
**Version:** vgit-7e568

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/shed/.config/picom.conf

### Drivers (inaccurate):

NVIDIA

### Backend: glx

* Driver vendors:
 * GLX: NVIDIA Corporation, NVIDIA Corporation
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce GTX 1660/PCIe/SSE2

</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = false;
shadow = false;
shadow-radius = 5;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-opacity = 0.5;
log-level = "warn";
log-file = "/tmp/picom.log";
shadow-exclude = [];
shadow-ignore-shaped = false;
inactive-opacity = 1;
active-opacity = 1;
frame-opacity = 10.4;
inactive-opacity-override = false;
blur-background-fixed = false;
blur-background-exclude = [];
fading = false;
fade-delta = 4;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-exclude = [ ];
mark-wmwin-focused = true;
mark-ovredir-focused = true;
use-ewmh-active-win = true;
detect-rounded-corners = true;
detect-client-opacity = false;
vsync = false;
dbe = false;
unredir-if-possible = false;
focus-exclude = [ ];
detect-client-leader = true;

wintypes:
{
  tooltip = { fade = false; shadow = false; opacity = 1; focus = true;};
  dock = { shadow = false; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 1; }
  dropdown_menu = { opacity = 1; }
};

xrender-sync-fence = true;
```
</details>

### Steps of reproduction
1. Run picom DISPLAY=:0.0 picom -b --config ~/.config/picom.conf ; DISPLAY=:0.1 picom -b --config ~/.config/picom.conf
2. Note windows that have alpha channel options such as alacrity or sakura will not render as such. Adjusting their settings fades the whole window just as increasing the inactive-opacity or active-opacity options which isn't desirable.

### Expected behavior
I expect applications with alpha channel settings to simply render as such. In the case of terminals backgrounds should become semi opaque while text remains completely opaque.

### Current Behavior
Everything is either 100 opaque or everything renders semi opaque. Transparency is ignored in applications that support it.

The only thing I ever get in the log is
[ 03/22/2022 19:38:04.349 glx_bind_pixmap ERROR ] Failed to query info of pixmap 0x01400279.
[ 03/22/2022 19:38:04.350 paint_one ERROR ] Failed to bind texture for window 0x07c01ac4.
[ 03/22/2022 19:38:04.350 paint_one ERROR ] Window 0x07c01ac4 is missing painting data.

**Comment by ghost** [comment]
Bueller...Bueller...Bueller?

**Comment by absolutelynothelix** [comment]
does this happen with picom built from the latest commit in the next branch?

**Comment by ghost** [comment]
Short answer, no clue. I'd have to build. uno...

Yup, exactly the same.

**Comment by absolutelynothelix** [comment]
thanks for checking because there is a lot of bugs fixed and things improved since the latest stable release.

does this happen with other backends? try the following configurations (with the picom that you've built):
* `--backend=egl`;
* `--legacy-backends --backend=glx`;
* `--backend=xrender`;
* `--legacy-backends --backend=xrender`.

and would be good to try an empty configuration file: `--config=/dev/null`.

**Comment by ghost** [comment]
Tried all those, same same same and same. The only thing that was "different" was ./picom --config=/dev/null kicked out (when I changed the opacity of a term)
[ 07/21/2023 12:25:33.301 x_log_error WARN ] X error 3 WINDOW request 2 minor 0 serial 11876

Just to make sure I built the correct version ./picom --version == vgit-5c03f

**Comment by absolutelynothelix** [comment]
let's stick to the picom that you've built and the configuration file that you've been using then.

upload a trace log (i.e. `--log-level=TRACE --log-file=picom.log` and reproduce the issue).

**Comment by ghost** [comment]
That was all with the fresh build. Log file is using the next build but my original conf.

[picom.log](https://github.com/yshui/picom/files/12131534/picom.log)

Just as a extra tidbit I was recently checking out some terms. QTerminal has separate settings for Application and Terminal transparency. "Terminal transparency" is basically what picom should be doing on any term that supports transparency. The only thing that actually does anything though is the "Application Transparency" which affects everything (fonts, menus, scrollbars, etc). Setting "Application Transparency" behaves as if I've made a rule in the picom.conf without having to make said rule.

*welp* I guess this will sit dead for another year...

**Comment by yshui** [comment]
Sorry, like it is with GTK, multiple X screen is not a supported use case. 

Still if you are willing to fix this, pull request is always welcome.

**Comment by ghost** [comment]
What does picom have to do with GTK? Dropping to a single XScreen doesn't fix/change anything.

**Comment by yshui** [comment]
@nPHYN1T3 do you get any errors logged after you switched to use a single X screen?

**Comment by yshui** [comment]
@nPHYN1T3 can you run this command:

```
xwininfo -id $(xwininfo -children | awk '/Parent/ { print $4 }')
```

then click on a window that's not rendered properly? post the output here.

**Comment by ghost** [comment]
Single XScreen the output is the same...nothing changes. I've run single to triple (one per GPU).
```
xwininfo: Window id: 0x600433 "CTWM frame"

  Absolute upper-left X:  0
  Absolute upper-left Y:  540
  Relative upper-left X:  0
  Relative upper-left Y:  540
  Width: 640
  Height: 540
  Depth: 24
  Visual: 0x21
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x20 (installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +0+540  -5120+540  -5120-0  +0-0
  -geometry 640x540+0-0
```

Same term (Sakura) from another XScreen
```
xwininfo: Window id: 0x60043f "CTWM frame"

  Absolute upper-left X:  5120
  Absolute upper-left Y:  0
  Relative upper-left X:  5120
  Relative upper-left Y:  0
  Width: 640
  Height: 764
  Depth: 24
  Visual: 0x1d8
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x1d7 (installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +5120+0  -0+0  -0-316  +5120-316
  -geometry 640x764-0+0
```

**Comment by yshui** [comment]
@nPHYN1T3 

```
  Depth: 24
```

So this is a problem with your window manager. I don't know how much Xorg lingo you understand, but if you want a transparent window (i.e. a window with 32 bit depth) to be displayed with transparency, you (as a window manager) need to reparent it with a frame window that also has 32 bit depth.

here, your window manager, ctwm, reparented it with a 24 bit depth frame, and that is why the window is not transparent.

**Comment by ghost** [comment]
Well the windows ARE transparent. This is the issue, it's ALL transparent or not at all. It doesn't distinguish between the bits like the background that should have the alpha applied vs the fonts which should not.

**Comment by yshui** [comment]
@nPHYN1T3 it is impossible for the compositor to tell what is text what is not.

**Comment by ghost** [comment]
I see that ;) (maybe I should have said I ***Don't*** see that because it's too transparent) [Sometimes bad jokes are hard.] Thanks for *CLEAR*ifying things (sorry I had to)

**Comment by yshui** [comment]
@nPHYN1T3 i realised you probably didn’t understand what I was saying. Alacritty window should be transparent without you twiddling with picom settings, i.e. you shouldn’t have to set window opacity.

the reason why it wasn’t is because your window manager, ctwm, does not support it.

**Comment by ghost** [comment]
I absolutely understood, what makes you think I didn't? (surely you didn't mistake my Dad jokes for not understanding)

As I said in my original post/report I'm well aware of GTK breaking XScreen enumeration since GTK 3.1ish. Due to this (already said in the initial post) I ditched XFCE (GTK based DE) for something that doesn't force you down the broken by design Wayland "future proofing" that is going on for the last few years. There isn't much that doesn't use GTK or that is "modern" but CTWM does everything I want and mostly how I want. Bit Depth isn't something really tossed around in the docs but seeing it only does 24 is a "kinda sucks but OK." The joke about "Clearifying things" was also a "Thanks for clarifying." Now that I know CTWM's lack of 32bit alpha depth is the culprate.

**Comment by yshui** [comment]
Aww sorry turns out I am the one who didn’t understand.

Never mind, I just wanted to make sure.

**Comment by ghost** [comment]
Tis all gud in de hud.
