### ISSUE TITLE
Remove Shadow on Telegram drop-down menu

### ISSUE THREAD

**Issue by jEsuSdA** [yshui/picom#806]
Hi!

I want to remove the estrange shadow under the drop-down menus in Telegram

![imagen](https://user-images.githubusercontent.com/5833446/160560701-2a751e3f-c2da-467b-9bd1-93a4d5983ee2.png)

I tried 

`	"class_g = 'Telegram' && (window_type = 'utility' || window_type = 'popup_menu') && argb",`

As you suggested me time before in other issue related with Firefox and Thunderbird, but it does not work in this case.

Any idea?

Thanks a lot!

**Comment by duxedo** [comment]
try class_g = 'telegram-desktop' instead. You can always get correct window class using xprop utility

**Comment by aScordino** [comment]
Just tried this and it did not work.

**Comment by jEsuSdA** [comment]
This solves this issue:

https://github.com/yshui/picom/issues/814#issuecomment-1120204111

```
shadow-exclude = [
    <bunch-of-rules>,
    "override_redirect = true",
];

```

**Comment by jEsuSdA** [comment]
Mark as closed!
Thanks a lot!!

**Comment by jEsuSdA** [comment]
Sorry! I just noticed this workaround disables ALL dropdown and menu shadoes.
I think this is not the solution. :S

**Comment by aScordino** [comment]
Hey, I have the solution, you just have to search for it throughout my dot
files [https://github.com/aScordino/dotfiles] in the `i3wm` branch.

Il gio 19 mag 2022, 14:29 jEsuSdA 8) ***@***.***> ha scritto:

**Comment by jEsuSdA** [comment]
Thank you so much, @aScordino 

This does the magic:

`"_NET_WM_WINDOW_TYPE:a *= '_KDE_NET_WM_WINDOW_TYPE_OVERRIDE'"`

Finally solved!! ;)

Thanks a lot!
