### ISSUE TITLE
Only Unredirect Fullscreen apps when in focus. Normal when minimized or unfocused! 

### ISSUE THREAD

**Issue by jarrard** [yshui/picom#823]
### Platform
EndeavourOS amd64

### GPU, drivers, and screen setup
6800XT MESA-GIT/DEV

### Environment
Plasma Desktop

### picom version
vgit-7e568

This is more of a feature request. Currently picoms unredirect FS behaviour has the entire desktop disable compositing and such when a FS exists. Is it possible to only have it do this when the application is IN FOCUS and not unfocused or minimized?

REASON for this is I often minimize my FS game to reach web or answer discord text replies etc etc etc... it be nice to do this at above 5fps and without all the black borders and mess over everything (consequence of no compositor).

**Comment by absolutelynothelix** [comment]
`--unredir-if-possible-exclude='!focused'` or
```
unredir-if-possible-exclude = [
    "!focused"
];
```
