### ISSUE TITLE
How to fix this problem

### ISSUE THREAD

**Issue by Saliizan** [yshui/picom#827]
her@her:~/Downloads/picom$ git submodule update --init --recursive
her@her:~/Downloads/picom$ meson --buildtype=release . build
The Meson build system
Version: 0.62.2
Source dir: /home/her/Downloads/picom
Build dir: /home/her/Downloads/picom/build
Build type: native build
Project name: picom
Project version: 9
C compiler for the host machine: cc (gcc 11.3.0 "cc (Debian 11.3.0-3) 11.3.0")
C linker for the host machine: cc ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program git found: YES (/usr/bin/git)
WARNING: You should add the boolean check kwarg to the run_command call.
         It currently defaults to false,
         but it will default to true in future releases of meson.
         See also: https://github.com/mesonbuild/meson/issues/9300
Has header "stdc-predef.h" : YES 
Compiler for C supports arguments -Wall: YES 
meson.build:63: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
Compiler for C supports arguments -Wcast-function-type: YES 
Compiler for C supports arguments -Wignored-qualifiers: YES 
Compiler for C supports arguments -Wmissing-parameter-type: YES 
Compiler for C supports arguments -Wnonnull: YES 
Compiler for C supports arguments -Wshadow: YES 
Compiler for C supports arguments -Wno-type-limits: YES 
Compiler for C supports arguments -Wold-style-declaration: YES 
Compiler for C supports arguments -Woverride-init: YES 
Compiler for C supports arguments -Wsign-compare: YES 
Compiler for C supports arguments -Wtype-limits: YES 
Compiler for C supports arguments -Wuninitialized: YES 
Compiler for C supports arguments -Wshift-negative-value: YES 
Compiler for C supports arguments -Wunused-but-set-parameter: YES 
Compiler for C supports arguments -Wunused-parameter: YES 
Compiler for C supports arguments -Wimplicit-fallthrough: YES 
Compiler for C supports arguments -Wno-unknown-warning-option: NO 
Compiler for C supports arguments -Wno-missing-braces: YES 
Compiler for C supports arguments -Wconversion: YES 
Compiler for C supports arguments -Wempty-body: YES 

Executing subproject test.h 

test.h| Project name: test.h
test.h| Project version: undefined
test.h| C compiler for the host machine: cc (gcc 11.3.0 "cc (Debian 11.3.0-3) 11.3.0")
test.h| C linker for the host machine: cc ld.bfd 2.38
test.h| Build targets in project: 0
test.h| Subproject test.h finished.

Found pkg-config: /usr/bin/pkg-config (0.29.2)
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency libev found: NO (tried pkgconfig and cmake)
Library ev found: YES
Library m found: YES
Run-time dependency x11 found: YES 1.7.5
Run-time dependency x11-xcb found: YES 1.7.5
Run-time dependency xcb-renderutil found: YES 0.3.9
Run-time dependency xcb-image found: YES 0.4.0
Run-time dependency xext found: YES 1.3.4
Run-time dependency pixman-1 found: YES 0.40.0
Run-time dependency xcb-render found: YES 1.14
Run-time dependency xcb-damage found: YES 1.14
Run-time dependency xcb-randr found: YES 1.14
Run-time dependency xcb-sync found: YES 1.14
Run-time dependency xcb-composite found: YES 1.14
Run-time dependency xcb-shape found: YES 1.14
Run-time dependency xcb-xinerama found: YES 1.14
Run-time dependency xcb-xfixes found: YES 1.14
Run-time dependency xcb-present found: YES 1.14
Run-time dependency xcb-glx found: YES 1.14
Run-time dependency xcb found: YES 1.14
Has header "uthash.h" : YES 
Run-time dependency libconfig found: YES 1.5
Run-time dependency libpcre found: YES 8.39
Run-time dependency gl found: YES 1.2
Run-time dependency dbus-1 found: YES 1.14.0
Build targets in project: 1

picom 9

  Subprojects
    test.h   : YES

  User defined options
    buildtype: release

Found ninja-1.11.0 at /usr/bin/ninja
her@her:~/Downloads/picom$ ninja -C build
ninja: Entering directory `build'
[28/28] Linking target src/picom
her@her:~/Downloads/picom$ sudo ninja -C build install
[sudo] password for her: 
ninja: Entering directory `build'
[0/1] Installing files.
Installing src/picom to /usr/local/bin
Installing /home/her/Downloads/picom/bin/picom-trans to /usr/local/bin
Installing /home/her/Downloads/picom/picom.desktop to /usr/local/share/applications
Installing /home/her/Downloads/picom/compton.desktop to /usr/local/share/applications
Installing /home/her/Downloads/picom/media/icons/48x48/compton.png to /usr/local/share/icons/hicolor/48x48/apps
Installing /home/her/Downloads/picom/media/compton.svg to /usr/local/share/icons/hicolor/scalable/apps
Running custom install script '/home/her/Downloads/picom/meson/install.sh'
her@her:~/Downloads/picom$ picom --version
vgit-cd505
her@her:~/Downloads/picom$ 

**Distribution: Debian 11**

**Comment by dybdeskarphet** [comment]
Which problem?

**Comment by absolutelynothelix** [comment]
closing as invalid and stale.
