### ISSUE TITLE
inactive-dim exclude rule

### ISSUE THREAD

**Issue by drannex42** [yshui/picom#829]
I have not been able to find any information on this is there ay way to manage excluding a window from an inactive-dim? For example, I have Firefox set to not have transparency when a YouTube page is open, but the page still dims, is there a way to disable that in a similar way?

**Comment by philiparvidsson** [comment]
Yes, I have this in my setup. Here's how to do it:

`
focus-exclude = [
  "_NET_WM_NAME@:s *= ' - YouTube'"
];

`

**Comment by drannex42** [comment]
Oh this is excellent. Thank you _very_ much. I will close this.

**Comment by erikdubois** [comment]
did the same thing for virtualbox

focus-exclude = [
  "_NET_WM_NAME@:s *= ' - YouTube'",
  "class_g = 'VirtualBox Machine'",
];
