### ISSUE TITLE
inactive-dim for one process with several windows

### ISSUE THREAD

**Issue by elig0n** [yshui/picom#832]
Applications that run one process but spawn multiple windows like the file managers thunar and pcmanfm
would dim or undim collectively no matter which client window of them is un/focused.

I'm running picom `vgit-44b49`

**Comment by tryone144** [comment]
Without having a look at your config, I suspect adding `detect-client-leader = false;` to your config changes this to the expected behaviour of dimming each window individually (see https://github.com/yshui/picom/issues/534#issuecomment-719457333).

**Comment by elig0n** [comment]
Thanks that did it !
