### ISSUE TITLE
Rounded corners don't work with animations + window closing bug as well

### ISSUE THREAD

**Issue by ohxxm** [yshui/picom#835]
![image](https://user-images.githubusercontent.com/68564017/175068007-2fbfe762-d7e8-4a6d-ae2b-434d3ebf9a5f.png)
When closing a window and rounded corners don't work either.

**Comment by absolutelynothelix** [comment]
vanilla picom doesn't have animations and it's unclear what's the issue. if you still have issues with vanilla picom, create a new issue and make sure to fill the template properly.

closing as invalid and stale.
