### ISSUE TITLE
Firefox popup_menu can't remove shadow/border with shadow = false;

### ISSUE THREAD

**Issue by okwellok** [yshui/picom#836]
### Platform

Archlinux AwesomeWM amd64
### GPU, drivers, and screen setup

Nvidia GeForce GTX 1060 Mobile, nvidia-dkms 515.48.07, only use External monitor
<details>
<summary>glxinfo -B</summary>
<pre><code>
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 6144 MB
    Total available memory: 6144 MB
    Currently available dedicated video memory: 5356 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 1060/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 515.48.07
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 515.48.07
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 515.48.07
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
</code></pre>
</details>
### Environment

AwesomeWM, zsh,
### picom version

vgit-7e568
<details>
<summary>Diagnostics</summary>
<pre><code>
[ 06/23/2022 18:08:34.197 get_cfg WARN ] Dual-kawase blur is not implemented by the legacy backends, you must use the `experimental-backends` option.
**Version:** vgit-7e568

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/xxx/.config/picom/picom.conf

### Drivers (inaccurate):

NVIDIA, modesetting

### Backend: glx

* Driver vendors:
 * GLX: NVIDIA Corporation
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce GTX 1060/PCIe/SSE2

</code></pre>
</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
// Paste your configuration here
corner-radius = 0;
# rounded-corners-exclude = [
#   "class_g = 'awesome'",
#   "class_g = 'firefox'",
#   "class_g = 'yuzu'",
#   "class_g = 'Shotcut'",
#   "class_g = 'YACReader'",
#   "class_g = 'Wine'",
#   # "class_g = 'Dunst'",
#   "class_g = 'Code'",
#   "class_g = 'wechat.exe'",
#   "class_g = 'scrcpy'",
#   "class_g = 'qimgv'",
#   "class_g = 'mpv'",
#   "class_g = 'warpd'",
# ];
# round-borders = 1;
# round-borders-exclude = [
# ];

#################################
#             Shadows           #
#################################

shadow = false;
shadow-radius = 12;
shadow-opacity = 0.8;
shadow-offset-x = -12;
shadow-offset-y = -12;

shadow-color = "#24273A";

shadow-exclude = [
	"name = 'Notification'",
	"class_g = 'Dunst'",
	# "class_g = 'firefox'",
	"class_g = 'edge'",
	"class_g = 'yuzu'",
	"class_g = 'slop'",
	"class_g = 'Wine'",
	"class_g = 'Clamtk'",
	"class_g = 'wechat.exe'",
	"class_g = 'Rofi'",
	"_GTK_FRAME_EXTENTS@:c",
	"_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];

#################################
#           Fading              #
#################################

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;
fade-exclude = [ "class_g = 'mpv'" ];

# no-fading-openclose = false;
# no-fading-destroyed-argb = true;

#################################
#   Transparency / Opacity      #
#################################

inactive-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = false;
active-opacity = 1.0;
inactive-dim = 0.0;

focus-exclude = [
	"class_g ?= 'rofi'",
	"class_g ?= 'slop'",
	"class_g ?= 'Steam'"
];

opacity-rule = [ 
  # "10:class_g    = 'eww-blur_full'",
  "90:class_g    = 'awesome'",
  "85:class_g    = 'yesplaymusic'",
  "100:class_g    = 'Wine'",
  "100:class_g    = 'edge'",
  "100:class_g    = 'wechat.exe'",
  "100:class_g    = 'Clamtk'",
  "78:class_g    = 'GNvim'",
  "100:class_g    = 'kitty'",
  "100:class_g    = 'Alacritty'",
  "85:class_g     = 'dmenu'",             
  "90:class_g     = 'pcmanfm-qt'",             
  "100:class_g     = 'yuzu'",             
  "90:class_g     = 'Blueberry.py'",             
  "80:class_g     = 'yesplaymusic'",             
  # "90:class_g     = 'fcitx5-config-qt'",             
  "85:class_g    = 'alixby'",            
  "90:class_g    = 'Lxappearance'",
  "90:class_g    = 'octopi'",
  "85:class_g     = 'YouTube Music'",
  "90:class_g     = 'iwgtk'",
  # "100:class_g    = 'code-oss'",
  # "80:class_g    = 'qBittorrent'",
  "90:class_g     = 'Lutris'",
  "100:class_g    = 'firefox'",
  "100:class_g    = 'scrcpy'",
  "85:class_g    = 'Pavucontrol'",
  "100:class_g    = 'warpd'"
]

#################################
#     Background-Blurring       #
#################################

blur: {
	method = "dual_kawase";
	# method = "box";
    strength = 8.0;
}

blur-background = false;
blur-background-frame = false;
blur-background-fixed = true;

blur-background-exclude = [
	"class_g = 'slop'",
	"_GTK_FRAME_EXTENTS@:c"
];

#################################
#       General Settings        #
#################################

backend = "glx";
vsync = true;
dbus = false;
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
unredir-if-possible = true;

unredir-if-possible-exclude = [
  "class_g = 'mpv'",
  "class_g = 'qimgv'",
  "class_g = 'Wine'",
  "class_g = 'sxiv'",
  "class_g = 'kitty'",
];

detect-transient = true;
detect-client-leader = true;
resize-damage = 1;

invert-color-include = [];

glx-no-stencil = true;
glx-no-rebind-pixmap = true;
xrender-sync-fence = true
use-damage = false;

# transparent-clipping = true;

log-level = "warn";
log-file = "/home/xxx/.cache/picom-log.log";
show-all-xerrors = true;

wintypes: {
	tooltip = { fade = true; focus = false; full-shadow = false;};
	normal = {  };
	dock = {  };
	popup_menu = { focus = false; opacity = 0.90; shadow = false};
	dropdown_menu = { focus = false; };
	above = {  };
	splash = {  };
	utility = { focus = false; blur-background = false; };
	notification = {  };
	desktop = { blur-background = false; };
	menu = { focus = false; };
	dialog = {  };
};

```
</details>

### Steps of reproduction

1. blur {method = "dual_kawase";}
2. backend = "glx";
3. picom --experimental-backends

### Expected behavior
Remove firefox bookmark menu shadow/border

### Current Behavior
set shadow = false; and popup_menu = {shadow = false;} , do not work.
When set backend = "xrender"; the problem is gone.  But the blur effect is gone.
### Other details

![picom](https://user-images.githubusercontent.com/83217712/175277003-b12e78a7-c493-4c6b-b246-4f711655b827.png)

**Comment by tryone144** [comment]
IIRC, Firefox draws its own shadows on these popup menus as well as rounds the corners.
See https://github.com/yshui/picom/issues/748 for a workaround to disable picom's shadows (and background blurring) for these windows. If you don't want these windows to have a shadow at all, you have to start looking into modifying firefox styles with userchrome.css.

**Comment by okwellok** [comment]
Thank you, I finally solved the problem by setting in blur-background-exclude
```
blur-background-exclude = [
		"(class_g = 'firefox' || class_g = 'Thunderbird') && (window_type = 'utility' || window_type = 'popup_menu') && argb",
	# "(class_g = 'Firefox' || class_g = 'Thunderbird') && (window_type = 'utility' || window_type = 'popup_menu') && argb",
];

```
