### ISSUE TITLE
`dual_kawase` blur on `glx` backend seems to have a max size

### ISSUE THREAD

**Issue by LoganDark** [yshui/picom#842]
### Platform
Alpine Linux 3.16 on Intel x86_64

### GPU, drivers, and screen setup
Single 4K laptop screen at 2x scaling. Discrete GPU is not being used

<details><summary><kbd>glxinfo -B</kbd></summary>

```
name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) UHD Graphics (CML GT2) (0x9bc4)
    Version: 21.3.8
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics (CML GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.3.8 (git-53b2b224dc)
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.3.8 (git-53b2b224dc)
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.3.8 (git-53b2b224dc)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

</details>

### Environment
Fluxbox on X11 (yes, that's it, I'm just using fluxbox)

### picom version
I can't tell (it says `vgit-555de5`)

<details>
<summary>Diagnostics</summary>

**Version:** vgit-555de5

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: None

### Drivers (inaccurate):

modesetting

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Intel
* GL renderer: Mesa Intel(R) UHD Graphics (CML GT2)
* Accelerated: 1

</details>

### Configuration:
I don't use a configuration file, but here is the invocation:

`picom --experimental-backends --backend glx --vsync --no-use-damage --corner-radius 10 --blur-background-fixed --blur-method dual_kawase --blur-size 128 -b`

Without `--backend glx` it tries to pick the xrender backend which causes issues.

### Steps of reproduction
1. Pick a large blur radius
2. Pick a larger one
3. Notice how they're both the same, so there is some max size

### Expected behavior

I should be allowed to set the blur radius as high as I want, even if it causes my GPU to suffer

### Current Behavior

Blur radius is clamped

### Stack trace
N/A

### Other details
Screenshot of blur radius 128:

![2022-07-07-071020_1579x1177_scrot](https://user-images.githubusercontent.com/4723091/177794345-29ac0826-b20c-4163-8de6-3df1962a287b.png)

Notice how it doesn't look like 128 at all. Setting it to 512 has no additional effect!

**Comment by tryone144** [comment]
dual_kawase has a discrete blur strength by design. For compatibility, we try to select a strength level that is **roughly** equivalent to the `--blur-size` radius for a standard gaussian blur. Ideally, you'd select the desired blur strength with `--blur-strength`. Currently, dual_kawase supports 20 strength levels. If you find, that the maximum does not satisfy you, I can take a look into calculating stronger parameters.

See [the code](https://github.com/yshui/picom/blob/cd50596f0ed81c0aa28cefed62176bd6f050a1c6/src/backend/backend_common.c#L375) for details on the parameters.

**Comment by LoganDark** [comment]
I'm looking for something similar to macOS's vibrancy:

![image](https://user-images.githubusercontent.com/4723091/178061835-87643e56-a0c7-42f9-8a63-2d1be48a0089.png)

As you can see, it's not a small radius blur :) although, it's not just a blur either. Anyway, I like the large blur radius.

I've [experimented with blurs before](https://www.shadertoy.com/view/fsdBzM); that one is relatively expensive even for dedicated GPUs, but still faster than [the multithreaded+SIMD CPU implementation](https://github.com/LoganDark/stackblur-iter) which I also made.

**Comment by LoganDark** [comment]
It would be cool to be able to provide custom shader programs for this, but that would require a lot of runtime support from picom, so.

(I'm allergic to C so I can't help with that unfortunately)

**Comment by tryone144** [comment]
> I'm looking for something similar to macOS's vibrancy:

Is `--blur-strength 20` not enough for this on your screen?

> It would be cool to be able to provide custom shader programs for this

I am pretty sure, this should not be too hard to add, after we have finalized a stable configuration interface in https://github.com/yshui/picom/pull/507. Running multiple custom shaders for window background and window contents should allow the mentioned features to be implemented without changes to the source — or some live shader effect testing with a clear window.

**Comment by LoganDark** [comment]
> Running multiple custom shaders for window background and window contents should allow the mentioned features to be implemented without changes to the source — or some live shader effect testing with a clear window.

Absolutely! I can imagine adding a shader for background blur, adding a shader for border/rounded corners, adding a shader for any shadow or anything etc. all layered on top of each other nice and neatly. This would require multiple shader types though, not just geometry and fragment but different stages (before/after the window, before/after other shaders). If this is something you have planned I would love to play around with it one day.

> Is `--blur-strength 20` not enough for this on your screen?

I'll test the next time I'm booted into Alpine. I have a 4K display with exactly 2X scale factor.

**Comment by LoganDark** [comment]
> Is `--blur-strength 20` not enough for this on your screen?

Woah, even blur strength 15 is quite nice.

![2022-07-13-084354_2572x1650_scrot](https://user-images.githubusercontent.com/4723091/178775438-20d3d038-2870-4242-9420-7dcae8bac25e.png)

Lots of color banding though. But it's still pretty. :)
