### ISSUE TITLE
Notification displayed even when i3lock is running

### ISSUE THREAD

**Issue by snprajwal** [yshui/picom#852]
### Platform
Arch Linux with kernel 5.8.10-arch1-1

### GPU, drivers, and screen setup
No GPU, using integrated Radeon graphics on AMD Ryzen 4700U
xf86-video-vesa 2.5.0-3
mesa 22.1.3-1
One external monitor to the left of laptop screen

### Environment
i3wm with i3bar, and dunst for notifications

### picom version
vgit-7e568

### Steps of reproduction
1. Start picom inside i3wm
2. Start dunst
3. Run i3lock
4. Send notification to dunst (either through dunstify or any other external program)

### Expected behavior
dunst notification is not displayed on i3lock screen

### Current Behavior
Notification bleeds through and is visible even when screen is locked

**Comment by yshui** [comment]
This is a i3/Xorg bug https://github.com/i3/i3lock/issues/204

You need to enable `unredir-if-possible`
