### ISSUE TITLE
GLX backend significantly heavier than XRENDER

### ISSUE THREAD

**Issue by Gwynsav** [yshui/picom#853]
Using NVIDIA proprietary drivers, and tested on both Arch and Void Linux, in both cases using bspwm.
Xrender uses around 7-8mb RAM, while GLX starts at 35~ and keeps climbing with time. Configuration doesn't seem to be relevant, I've tried a bunch of different settings and this doesn't seem to change much, although in the past I have seen GLX using up to 100mb when Vsync is on. For the record, both backends were tried with Vsync off, following this configuration:

```
# SHADOW ########################################################
shadow = true;
shadow-radius = 15;
shadow-opacity = .65;
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-exclude = [
   "class_g = 'rofi'",
];

corner-radius = 10;
rounded-corners = 1;
rounded-corners-exclude = [
   "window_type = 'dock'",
];

# TRANSPARENCY & BLUR ###########################################
blur-background = false;
blur-background-frame = false;

active-opacity = 1;
inactive-opacity = 1;
frame-opacity = 1;

# FADING ########################################################
fading = true;
fade-delta = 5;
fade-in-step = 0.03;
fade-out-step = 0.03;

# STUFF #########################################################
vsync = false;
backend = "glx";
use-damage = true;
unredir-if-possible = true;

# WINDOW RULES ##################################################
wintypes: {
        normal        = { shadow = true, full-shadow = true };
	notification  = { shadow = true  };
	dock	      = { shadow = true; full-shadow = true };
	dnd	      = { shadow = false };
	dialog	      = { shadow = false };
	tooltip       = { shadow = false };
	utility       = { shadow = false };
	popup_menu    = { shadow = false };
	dropdown_menu = { shadow = false };
};
```

I have also tried forks, but the problem persists. I'm beginning to suspect this might be hardware induced, particularly due to the fact that the issue persisted across clean installations of different distros.

**Comment by yshui** [comment]
Does this cause any problem for you?

**Comment by Gwynsav** [comment]
Not really, I just found it to be bizarre behaviour which other people don't seem to suffer from, so I wanted to asked in case it was something dumb that I had missed.
