### ISSUE TITLE
Picom lagging terribly on Intel iGPU & xrender backend

### ISSUE THREAD

**Issue by tontsa28** [yshui/picom#865]
### Platform
Arch Linux x86_64

### GPU, drivers, and screen setup
Intel UHD Graphics 630, Mesa version 22.1.4
`xf86-video-intel` not installed, has been tried but does not make a difference.
Output of `glxinfo -B`:
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) UHD Graphics 630 (CFL GT2) (0x3e9b)
    Version: 22.1.4
    Accelerated: yes
    Video memory: 15880MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics 630 (CFL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.1.4
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.1.4
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.1.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment
Using bspwm with Xorg, system does have a NVIDIA GTX 1050 Max-Q as well but this issue does not exist when running on NVIDIA.

### picom version
Picom version: `vgit-7e568`
Picom diagnostics:
```
**Version:** vgit-7e568

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/miika/.config/picom/picom.conf

### Drivers (inaccurate):

modesetting

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Intel
* GL renderer: Mesa Intel(R) UHD Graphics 630 (CFL GT2)
* Accelerated: 1
```

### Configuration:
```
shadow = false;

fading = true;
no-fading-openclose = false;

inactive-opacity = 1.0;
frame-opacity = 1.0;
active-opacity = 1.0;
opacity-rule = [
  "100:class_g = 'Alacritty'"
];

blur-method = "kernel";
blur-kern = "11x11gaussian";
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "window_type = 'fullscreen'",
  "class_g = 'Gnome-screenshot'",
  "_GTK_FRAME_EXTENTS@:c"
];

backend = "xrender";
glx-no-stencil = true;
glx-copy-from-front = false;

vsync = true;
mark-wmwin-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;
use-damage = true;
xrender-sync-fence = true;
no-ewmh-fullscreen = false;
log-level = "warn";
```

### Steps of reproduction
1. Use a system with Intel iGPU (my processor is a Core i5 9300H)
2. **Use xrender as backend**, glx works fine but has other performance issues that can be noticed when, for example, playing Minecraft, the FPS is normal but the game feels stuttery (not sure if I should open another issue about this since I would prefer to use the glx backend, if it only was usable).

### Expected behavior
Smooth experience with xrender backend.

### Current Behavior
One CPU core is running at 100% (because of picom), picom is using over 50 megabytes of RAM which seems unreasonably high and everything is extremely laggy, clicks and such can come with a delay of seconds and the FPS seems very low, maybe 1 or 2 frames per second. In this state, the system is completely unusable. The problem persists until picom is killed.

### Stack trace
The compositor does not crash but is extremely slow.

### Other details

**Comment by yshui** [comment]
blur is not very performant on xrender backend. is there any specific reason that prevents you from using the glx backend

**Comment by tontsa28** [comment]
I thought so, until I tried the `unredir-if-possible = true;` option and now the problems are gone so I guess I can use glx.

As a side question, why is there no `blur-background-include` option? I think this would be valuable since alacritty is really the only program I want the blur on. When I open Firefox, for example, I can see the blur before the UI comes up. Is the blur really there all the time or just for the time the window is opaque (in which case this wouldn't matter)?

**Comment by yshui** [comment]
>why is there no blur-background-include option?

#846 asks for the same thing I think.
