### ISSUE TITLE
Allow to suspend picom during runtime

### ISSUE THREAD

**Issue by adamnejm** [yshui/picom#868]
### Description
Allow user to query **picom** during runtime in order to suspend *(and resume)* it, without having to kill the instance.  

### Why
I want to be sure that picom is not running based on arbitrary conditions. To achieve this, I'm using a script that kills **picom** instance when certain X clients appear and I respawn **picom** once they're gone.  
This can be super slow however and sometimes take even 2 or 3 seconds for **picom** to initialize, which doesn't happen when using the `--unredir-if-possible` flag and is essentially instantaneous.  
  
### Usage suggestion
`picom --suspend` Makes **picom** behave just as it was unredirected  
`picom --resume` Resumes the usual **picom** behavior

Alternatively:
`picom --unredir-window <ID>` Marks a specific window to be unredirected when active
`picom --stop-unredir-window <ID>` Makes the window follow the regular unredirecting rules
This IMHO will limit what can be done with 3rd party scripts.  
The first option should be easier to implement and allow for more flexibility.

**Comment by yshui** [comment]
This is already possible:

suspend: `dbus-send --dest=com.github.chjj.compton._0 --type=method_call /com/github/chjj/compton com.github.chjj.compton.opts_set string:redirected_force uint32:0`
resume: `dbus-send --dest=com.github.chjj.compton._0 --type=method_call /com/github/chjj/compton com.github.chjj.compton.opts_set string:redirected_force uint32:2`

**Comment by adamnejm** [comment]
That's great! Sorry for the unnecessary post.
