### ISSUE TITLE
Document type of matching rules

### ISSUE THREAD

**Issue by danjenson** [yshui/picom#884]
This isn't a bug, I just can't seem to find in the picom help, config file, or in issues anywhere that explains the matching syntax thoroughly. I've seen `=` , `!<x> = <y>`,  `*=` ,  `?=` , and `~=` used in various configs, but can't seem to figure out when to use which type of matching pattern and what it does.  Thank you!

**Comment by tryone144** [comment]
[Man-page](https://github.com/yshui/picom/blob/next/man/picom.1.asciidoc#format-of-conditions) to the rescue.
I hope this is thorough enough. ;)
