### ISSUE TITLE
[Question / Feature request] Can I highlight the currently active window

### ISSUE THREAD

**Issue by thomasheartman** [yshui/picom#886]
Hi 👋🏼  Thanks for a great application and all the work that goes into it 😄 

I have a question that I haven't been able to find the answer to, and if the answer is that "this can't be done", then I also have a feature request.

## Question

Is there a setting in Picom to highlight (in some manner) the currently active window? 

### Goal / what I'd like to achieve

Ideally, I'd like a way for Picom to highlight the currently active window that doesn't clash with other functionality (such as window shadows). I'm imagining a window outline with an optional offset to give it some space from the window it highlights. 

Something like the black indicator around this icon

![image](https://user-images.githubusercontent.com/17786332/188278523-609ecd6a-ad16-41cc-90d7-b7780f8309e5.png)

or the square outline around this button:

![image](https://user-images.githubusercontent.com/17786332/188278547-600108c5-444f-477f-b8ed-a44101028144.png)

### Background

I use i3 (gaps) as my window manager, and don't have any title bars or other distinguishing features for which window is currently active. As such, it can be tricky to know at a glance which window currently has focus.

### Current workaround

I have a workaround that does an alright job at showing focus, but it does come with a few drawbacks. 

The main thing I do to help me identify the currently focused window is to use Picom's shadow functionality. I've set it to only show shadows for the currently active window, and I've set the shadow to be a color that stands out from the background. This way, it becomes more of an outline that helps me determine which window I'm working in. It looks like this:

![image](https://user-images.githubusercontent.com/17786332/188278260-f40b05b1-5494-4efa-a622-ffad3f57927f.png)

The main drawback of this method is that I'd like to have (regular, dark) shadows for all application windows, but I'm under the impression that you can't have multiple shadows defined, so I don't think that's compatible with this workaround.

I also make non-focused windows slightly dimmer and more translucent.

----

Thanks for any input you can give me in regards to this: it's all very much appreciated. 

I've attached some information about my system below, but because this is more of a question, I'm not sure how relevant it is. 

Let me know if you need any more info, and I'd be more than happy to provide it! 😄 

### Platform

NixOS Desktop 22.11 x86_64

### Environment

i3-gaps

### picom version

v9.1

<details>
<summary>Diagnostics</summary>
**Version:** v9.1

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/thomas/.config/picom/picom.conf

### Drivers (inaccurate):

modesetting

### Backend: glx

* Driver vendors:
 * GLX: NVIDIA Corporation
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce GTX 1050 Ti with Max-Q Design/PCIe/SSE2

</details>

**Comment by absolutelynothelix** [comment]
some wms (especially tiling ones) allow you to have different border color for active/inactive windows. iirc, at least bspwm is capable of this, maybe i3 too. picom allows you to dim inactive windows, see `inactive-dim`.

**Comment by thomasheartman** [comment]
Thanks for the response! Yeah, that's a good point! I looked around a bit now and I think a solution is offered under what is currently [section 4.22 of the i3 user guide: changing colors](https://i3wm.org/docs/userguide.html#client_colors). From what I can tell, that should provide me with what I'm looking for.

I seem to recall spending a fair few hours looking for something like this last time, but I must not have found it for some reason. Maybe I didn't think to check the actual window manager? 🤷🏼 

In that case, my needs seem to be covered, so I'll close this for now. 

Thanks again!
