### ISSUE TITLE
Round corners mentioned at #775 solved, now gives display a black square at borders

### ISSUE THREAD

**Issue by BuddhiLW** [yshui/picom#893]
I use XMonad, Archlinux, and installed picom by:
```
sudo pacman -S picom
```

![maim-region-20220918-143945](https://user-images.githubusercontent.com/59554283/190921258-5964b2a1-19a3-4c83-bc83-3982fae23607.png)

**Comment by yshui** [comment]
`picom` in the Arch repository doesn't yet have the round corner fix.
