### ISSUE TITLE
FR: Please port pcre dependency to pcre2. Pcre has been deprecated.

### ISSUE THREAD

**Issue by tim77** [yshui/picom#895]
### Platform

Fedora Linux
36 (Workstation Edition)
x86_64

### picom version

v9.1

### Summary

Upstream stopped the support for the old 'pcre' package. It only supports the new 'pcre2' version, so Fedora should deprecate it so it could later be retired and removed from Fedora entirely. 

### Rationale

Pcre has been deprecated since Fedora 38. Please consider porting to the new pcre2 version.

Fedora change that describes the pcre deprecation is located here: https://fedoraproject.org/wiki/PcreDeprecation

### Detailed Description

Upstream stopped supporting the old `pcre` package. The 8.45 is marked as a final release and nothing else will be added/fixed in it. This may lead to some unresolved CVEs, which would have to be resolved by the maintainers. Unfortunately, due to our limited capacity, we wouldn't have the time and experience to solve this by ourselves, so we need to deprecate this package. After the deprecation is done, the very next step would be starting the [retirement change](https://fedoraproject.org/wiki/PcreRetirement), so the package is removed from Fedora entirely.

The new `pcre2` package is out for more than 7 years now and most of the packages have already been ported to its redefined API. [Mail](https://lists.exim.org/lurker/message/20150105.162835.0666407a.en.html) about the changes in the pcre2.

### User Experience

Users will not be exposed to the possible vulnerable pcre package, because the pcre2 is supported by the upstream community.

**Comment by yshui** [comment]
Thanks for bringing this to my attention!

I did a quick check, looks like we don't use any of the advanced pcre stuff so it should be simple to replace. Only concern I have is pcre2's syntax is not 100% compatible with pcre's, so this could break someone's config file.

**Comment by yshui** [comment]
@tim77 hey, can you maybe have a look at #937 ?

**Comment by tim77** [comment]
Hey, i've built `picom` with pcre2 patch for [Rawhide](https://koji.fedoraproject.org/koji/taskinfo?taskID=94474551) so these who interesting in testing please do. Also built for F37 in [Copr](https://copr.fedorainfracloud.org/coprs/atim/playground/).
