### ISSUE TITLE
No shadows ...

### ISSUE THREAD

**Issue by fime-space** [yshui/picom#896]
### Platform
Debian LXQT v0.16.0

### GPU, drivers, and screen setup
Radeon RX570,  driver : radeon xf86-video-ati 19.1.0 , Mesa 20.3.5, a basic vga monitor from the window vista era (1200x900).

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: Radeon RX 570 Series (POLARIS10, DRM 3.40.0, 5.10.0-13-amd64, LLVM 11.0.1) (0x67df)
    Version: 20.3.5
    Accelerated: yes
    Video memory: 4096MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 3739 MB, largest block: 3739 MB
    VBO free aux. memory - total: 4009 MB, largest block: 4009 MB
    Texture free memory - total: 3739 MB, largest block: 3739 MB
    Texture free aux. memory - total: 4009 MB, largest block: 4009 MB
    Renderbuffer free memory - total: 3739 MB, largest block: 3739 MB
    Renderbuffer free aux. memory - total: 4009 MB, largest block: 4009 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 4096 MB
    Total available memory: 8192 MB
    Currently available dedicated video memory: 3739 MB
OpenGL vendor string: AMD
OpenGL renderer string: Radeon RX 570 Series (POLARIS10, DRM 3.40.0, 5.10.0-13-amd64, LLVM 11.0.1)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.3.5
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.3.5
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.3.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment

I'm using openbox with the lxqt desktop. I launched picom on the gnome terminal and i've used the qterminal to test if picom acted in a same way.

### picom version
```
fime@neptune:~/picom/build/src$ ./picom --version
vgit-5ac8b
```
(I builded it from the "next " branch) (note that i tried the stable debian apt builds but it acted in a same way.)

<details>
<summary>Diagnostics</summary>

```
**Version:** vgit-5ac8b

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: None

### Drivers (inaccurate):

AMDGPU, Radeon

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: AMD
* GL renderer: Radeon RX 570 Series (POLARIS10, DRM 3.40.0, 5.10.0-13-amd64, LLVM 11.0.1)
* Accelerated: 1
```

</details>

### Configuration:
no config file,
command used : `picom --corner-radius 5 -r 20 -o 0.5 --backend glx --blur-background --blur-size 10 --blur-method box` (i didn't used config file because i'm only testing it.

### Steps of reproduction
Sorry, but there's no particular way to reproduce it ...
I just compiled the bin and launched it ...

### Expected behavior
The compositor should display drop shadows under the windows

### Current Behavior
Everything is working excepted for the drop shadows ...

### Other details

Note that I tested other versions of compton/picom (the last compton version) and it didn't changer anything ...

Shadow are not working (using gnome terminal which haven't transparency)
https://user-images.githubusercontent.com/72309049/192333522-d288130b-a862-4b08-95da-2cd639399d55.mp4

But transparency is working (and other features like blur and rounded corners)
https://user-images.githubusercontent.com/72309049/192335250-385c6131-4b2b-4d7b-b423-2756e91e867f.mp4

**Comment by tryone144** [comment]
> no config file,
> command used : `picom --corner-radius 5 -r 20 -o 0.5 --backend glx --blur-background --blur-size 10 --blur-method box` (i didn't used config file because i'm only testing it.

Have you tried enabling the shadows with `-c`? The `-r` and `-o` options only set shadow parameters.

**Comment by fime-space** [comment]
sights ... i did't used that ...
actually, i tested picom on another computer and it was enabled by default so i did'nt thought it could change anything ... thanks you very much
