### ISSUE TITLE
Cannot run picom on Ubuntu (Err: Another composite manager is already running)

### ISSUE THREAD

**Issue by FilipNajj** [yshui/picom#897]
When typing `picom -b` in the terminal, I get the following:
`Another composite manager is already running`

### Steps I followed for installing picom:
1. git clone https://github.com/yshui/picom.git
2. sudo apt install libxext-dev libxcb1-dev libxcb-damage0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-randr0-dev libxcb-composite0-dev libxcb-image0-dev libxcb-present-dev libxcb-xinerama0-dev libxcb-glx0-dev libpixman-1-dev libdbus-1-dev libconfig-dev libgl1-mesa-dev libpcre2-dev libpcre3-dev libevdev-dev uthash-dev libev-dev libx11-xcb-dev meson
3. $ git submodule update --init --recursive
$ meson --buildtype=release . build
$ ninja -C build
$ ninja -C build install

### Platform
Ubuntu Desktop 22.04 64-bit
GNOME 42.4
Terminal: Alacritty
Windowing System: Wayland
Processor: Intel® Core™ i7
Graphics: Mesa Intel® UHD Graphics 620 (WHL GT2)

### glxinfo -B:
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) UHD Graphics 620 (WHL GT2) (0x3ea0)
    Version: 22.0.5
    Accelerated: yes
    Video memory: 3250MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.0.5
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.0.5
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```
### picom --diagnostics
```
**Version:** vgit-5ac8b

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/filip/.config/picom/picom.conf

### Drivers (inaccurate):

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Intel
* GL renderer: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
* Accelerated: 1

```

**Comment by tryone144** [comment]
> Another composite manager is already running

This is to be expected on your platform:

> GNOME 42.4
> Windowing System: Wayland

picom is an *X* compositor and only works with window managers running in *X11*. By design, it does not work with Wayland (Wayland's design, not that of picom).
Furthermore, Gnome does not support running an external compositor like picom, IIRC — at least not with its gnome-shell.

**Comment by FilipNajj** [comment]
so there is no way to make it work in Ubuntu? Because if it doesn't work with Gnome then I can't do anything about it?

**Comment by tryone144** [comment]
Unfortunately there is no way to make it work under Gnome. I am not sure if there is a gnome-specific way of blurring your terminal's background.
Alternatively you can try out another window manager or desktop environment that either supports a standalone compositor (like xfce), or supports blurring on its own (like kde).

**Comment by SIMULATAN** [comment]
There are [gnome-shell-extensions](https://extensions.gnome.org/) that add a lot of the features gnome doesn't have out of the box, blurring extensions are one of these things. For example, I found the [blur-provider](https://extensions.gnome.org/extension/3607/blur-provider/) extension, which seems to be doing what you want. Alternatively, just search for "blur" on the extension website.

**Comment by FilipNajj** [comment]
I have tried a couple extension including the one you mentioned. Unfortunately most of them do not support gnome 42 & higher for blurring effects

**Comment by FilipNajj** [comment]
I finally found it! I can't believe it actually works! I downloaded the extension "blur my shell". They now have the option to blur applications such as terminals.
